### ISSUE TITLE
Chapter1. 오브젝트와 의존관계 (1)

### ISSUE THREAD

**Issue by tmfrl1552** [FireInStove/toby-spring#1]
### 👑 스터디장
* 슬기 (@tmfrl1552)

### 📖 스터디 범위
* 1.1 초난감 DAO ~ 1.2 DAO의 분리

**Comment by yougahee** [comment]
## ✏️ 정리
###  분리와 확장
- 관심사의 분리
  - 모든 변경과 발전은 한 번에 한가지 관심사항에 집중해서 일어난다.
  - 관심이 같은 것끼리는 모으고, 관심이 다른 것은 따로 떨어져 있게 하는 것


## 디자인 패턴
- 템플릿 메소드 패턴
  - 슈퍼클래스에 기본적인 로직이나 흐름을 만들어 두고, 그 템플릿에 따라 서브 클래스가 구현
  - 스프링에서 애용되는 디자인 패턴
- 팩토리 메소드 패턴
  - 서브클래스에서 오브젝트를 어떻게 생성할 것인지 결정하는 방법	
  - 즉, Connection이라는 오브젝트(인터페이스)를 서브 클래스에서 구현할 수 있도록 넘김 (슈퍼클래스는 Connection이 어떻게 구현되는 지 관심 없음.)
  	- 이렇게 슈퍼클래스에 미리 정의한 메소드를 팩토리 메소드라고 한다. 



## 이야기거리
- 66~67p 에 구현된 UserDao 는 템플릿 메소드 패턴 과 팩토리 메소드 패턴이 같이 녹여든 것 코드라고 생각.
- 이유 
  - 상위클래스에 getConnection() 이라는 추상메소드(=템플릿) 이 존재하고, 이를 서브클래스에서 구현했으니 템플릿 메소드 패턴을 사용.
  - 68p. 그림 1-2 를 참고하면 팩토리 메소드 패턴이 잘 적용되었다고 말할 수 있다.

**Comment by tmfrl1552** [comment]
## 1.1 초난감 DAO
### 자바빈이란?
* 다음 두 가지 관례를 따라 만들어진 오브젝트
	* 디폴트 생성자 : 파라미터가 없는 디폴트 생성자를 갖고 있어야 한다. 툴이나 프레임 워크에서 리플렉션을 이용해 오브젝트 생성
 		 > 리플렉션 이란? 
 			* 구체적인 클래스타입을 알지 못해도 그 클래스의 메소드, 타입, 변수들에 접근할 수 있는 자바 API
 			* 코드 작성 시점에는 어떤 타입의 클래스를 사용할지 모르나, 런타임 시점에 지금 실행되고 있는 클래스를 가져와서 실행해야 할 때 사용
 	* 프로퍼티 : 자바빈이 노출하는 이름을 가진 속성. set으로 시작하는 수정자 메소드(setter)와 get으로 시작하는 접근자 메소드(getter)를 이용해 수정 또는 조회할 수 있다.


## 1.2 DAO의 분리
* 객체 지향의 세계에서는 오브젝트에 대한 설계와 이를 구현한 코드가 변한다.
* 사용자의 비즈니스 프로세스와 그에 따른 요구사항은 끊임없이 바뀌고 발전한다.
	* 객체 설계 시 가장 염두해야 할 사항은 '미래의 변화를 어떻게 대비할 것인가' 이다.
 	* 가장 좋은 대첵은 변화의 폭을 최소한으로 줄여주는 것이다. --> **'분리와 확장'** 을 고려한 설계 필요
* 관심사 분리
	* 관심이 같은 것끼리는 하나의 객체 안으로 또는 친한 객체로 모이게 하고, 관심이 다른 것은 가능한 따로 떨어져서 서로 영향을 주지 않도록 분리
	* 1. 중복 코드의 메소드 추출
		* 중복 코드를 하나의 메소드로 만들어, 중복 제거
		* 관심의 종류에 따라 코드를 분류해놓았기 대문에 한 가지 관심에 대한 변경이 일어날 경우 
		  그 관심이 집중되는 부분의 코드만 수정
> 리팩토링
	* 기존 코드를 외부의 동작방식에는 변화 없이 내부 구조를 변경해서 재구성하는 작업 또는 기술
	* 생산성이 올라가고, 코드의 품질이 높아지며 유지보수하기 용이해지고, 견고하면서도 유연한 제품 개발 가능
* **템플릿 메소드 패턴**
	* 슈퍼 클래스에 기본적인 로직의 흐름(커넥션 가져오기, SQL 생성, 실행, 반환)을 만들고,
	  그 기능의 일부를 추상 메소드나 오버라이딩이 가능한 protected 메소드 등으로 만든 뒤 서브클래스에서 이런 메소드를 
	  필요에 맞게 구현해서 사용하도록 하는 방법
	* 상속을 통해 슈퍼클래스의 기능을 확장할 때 사용하는 대표적인 방법
	* 변하지 않는 기능은 슈퍼클래스에 만들어두고 자주 변경되며 확장할 기능은 서브클래스에서 생성
	* 훅 메소드 : 슈퍼클래스에서 디폴트 기능을 정의해두거나 비워뒀다가 서브클래스에서 선택적으로 오버라이드할 수 있도록 만들어둔 메소드
* **팩토리 메소드 패턴**
	* 팩토리 메소드 : 서브 클래스에서 오브젝트 생성 방법과 클래스를 결정할 수 있도록 미리 정의해둔 메소드
	* 이 방식을 통해 오브젝트 생성 방법을 나머지 로직 즉, 슈퍼클래스의 기본 코드에서 독립시키는 방법
	 > 자바의 일반적인 팩토리 메소드와 팩토리 메소드 패턴의 팩토리 메소드는 서로 의미가 다름
		* 일반적인 팩토리 메소드 : 오브젝트를 생성하는 기능을 가진메소드
* 상속의 한계
	* 자바는 클래스의 다중 상속 미허용
	* 상속을 통한 상하위 클래스의 관계는 생각보다 밀접하다.
		* 슈퍼클래스 내부의 변경이 있을 때, 모든 서브클래스를 함께 수정하거나 다시 개발해야 할 수도 있음.
## 추가 참고 자료
* 템플릿 메소드 패턴과 팩토리 메소드 패턴의 정확한 차이가 궁금해서 참고한 자료 🤓
[템플릿 메소드 패턴, 팩토리 메소드 패턴](https://kimjye.tistory.com/entry/%ED%86%A0%EB%B9%84%EC%9D%98-%EC%8A%A4%ED%94%84%EB%A7%8131-1%EC%9E%A5)

**Comment by kyueun** [comment]
## DAO의 분리
객체 지향 기술은 추상세계 자체를 효과적으로 구성하고, 변경, 발전, 확장시킬 수 있다는 점에 의미가 있음
    -> 변화에 어떻게 대비할 것인가가 가장 중요
    => **분리**와 **확장**을 고려해서 설계해야 함

### 관심사의 분리
관심이 같은 것은 모이게 하고, 관심이 다른 것은 떨어져서 영향을 주지 않도록 분리

1. 관심사항 파악
    * 책의 예시의 경우, UserDao 의 관심사항 정리
2. 중복 코드의 메소드 추출
    * DB의 변경 등으로 코드 수정이 필요할 경우, 추출한 메소드 한 개만 변경해도 이슈 없도록 중복 코드 분리
3. 변경 사항 검증 - 리팩토링과 테스트
    * 리팩토링 : 기존의 코드를 외부의 동작 방식에는 변화 없이, 내부 구조를 변경해서 재구성하는 작업

### 상속을 통한 확장
사용처에서 자유롭게 변화가 가능하도록 하는 코드 작성

#### 디자인 패턴
* 설계 시 자주 만나는 문제를 해결하기 위해 사용할 수 있는 재사용 가능한 솔루션
* 대부분 클래스 상속 또는 오브젝트 합성의 구조로 확장성 추구
* 예시
    * 템플릿 메소드 패턴 : 슈퍼클래스에 기본 로직 흐름을 만들고, 기능의 일부를 추상 메소드나 protected 메소드로 생성 후 서브클래스에서 구현해서 사용하는 패턴
    * 팩토리 메소드 패턴 : 서브클래스에서 구체적인 오브젝트 생성 방법을 결정하게 하는 패턴

#### 상속의 한계점
* 다중상속 불가능 : 한 번 상속을 하면, 추후 다른 목적을 위한 상속이 불가능
* 클래스 간 밀접한 관계 : 서브클래스가 슈퍼클래스의 기능을 직접 사용 -> 슈퍼클래스 내부 변경이 서브클래스에 영향을 미침
* 서브클래스들의 코드 중복 : 한 슈퍼클래스를 상속하는 서브클래스가 많아지면, 상속을 통해 만들어진 구현 코드가 모든 서브클래스마다 중복

**Comment by flyingtw** [comment]
# 1. 초난감 DAO

- DAO(Data Access Object) 의 원초적인 기능을 알 수 있었다. 
  - 1- jdbc등을 이용한 db connection 생성
  - 2- PreparedStatement 라는 객체를 이용해 SQL생성
  - 3- state를 실행하거나 응답을 처리

- 테스트 코드의 가장 원초적인 방식을 알 수 있었다. 

- main 메서드를 통해 객체를 생성하고 CURD 작업을 수행하며 저장 및 조회 값이 일치하는지 확인하는것
하지만 문제. 
**원초적이다.**


# 2. DAO의 분리
- DAO 기능은 관심사에 따라 기능을 분리할 수 있다. 위의 DAO 의 원초적인 기능이라 나열한 3가지를 관심사로 구분지어 각 기능을 분리시킨다.
- 가장 첫번째로 jdbc등을 이용한 DB connection 관심사 분리
  - 중복 코드의 메소드를 추출하여 재사용 할 수 있다. 그로인해 getConnection()이라는 메서드로 연결 설정을 분리하였다. 
  → save(저장), get(조회) 의 기능에 connection 기능을 분리하여 db endpoint가 바뀌거나 다른 db를 사용하고 싶을때 getConnection 만 수정하면 가능하게 되었다. (현재의 dbConfig의 원초적인 역할)
- 리펙토링 자체는 거창한게 아닌 공통적인 관심사를 가진 메서드를 구분해내고 이를 뽑아 구조를 변경하는것임을 알게되었다.
하지만 여러 사람들이 getConeection 메서드를 각자 원하는 방식으로 구현할 수 없다. 
  → 상속을 통하여 다시 getConnection 메서드의 관심사를 분리

- Dao 클래스를 추상 클래스, 추상 메서드로 선언하여 DAO 자체의 색깔은 잃지 않도록, 하지만 자식 클래스의 입맛에 맞도록 구현할 수 있께 틀을 만들었다.
- 이때, 부모 클래스(슈퍼 클래스)에서 기본적인 로직을 선언한 후 기능의 '일부'를 추상 메소드나 자식이 오버라이딩 할수 있는 protected 메소드로 만들어놓고 자식이 직접 구현할 수 있게 만드는 패턴을
=> **템플릿 메소드 패턴** 이라 명한다.
이때 자식 클래스에서 부모 클래스에서 선언해놓은 connection 오브젝트를 직접 구현하는 방식이 바로
=> **팩토리 메소드 패턴** 이라 명한다.
- 두 자식 클래스가 같은 오브젝트 타입을 반환 하더라고 구 오브젝트를 구현하는 방식이 다르기 때문에 팩토리 메소드 패턴이라 명명할 수 있다.
- 즉, 부모 클래스 입장에서 메서드 구현을 자식에게 떠넘기는걸 템플릿 메소드 패턴이라 하고 그 자식이 만든 구현체의 메서드를 부모가 사용하되 - 자식이 만드는 방식은 자유롭게 냅두는걸 팩토리 메소드 패턴이라 하는것 같다.
- 하지만, java의 상속은 생각보다 꼰대고 여러 부모를 둘 수 없게 제한이 되어있으니...단순히 connection 기능만 상속 받기엔 다른 여러 기능을 상속받을 수 없다는 문제가 발생한다... 또한 UserDao 에 getConnection이 선언되어 있고 그 자식들이 구현한다 치면 다른 CompanyDao 에서 connection 기능을 사용하려면 또다시 getConnection을 중복되게 선언해야한다. 이건 심각한 문제다.

**Comment by aimhigh53** [comment]
**1. DAO?**
 Data Access Object
  DB를 사용해 데이터를 조회하거나 조작하는 기능을 전담하도록 만든 오브젝트 
* DTO:  DTO는 계층 간 데이터 교환을 담당하는 Java Beans
* VO: VO는 값 자체를 표현하는 객체(DTO랑 슷비)
 * Entity : Entity는 데이터베이스 테이블의 행을 표현하는 객체

**2. DAO 분리  관심사분리**
객체지향에 적용해보면, 관심이 같은 것끼리는 하나의 객체 안으로 또는 친한 객체로 모이게 하고, 관심이 다른 것은 가능한 한 따로 떨어져서 서로 영향을 주지 않도록 분리하는 것  중복코드의 메소드추출/리팩토링과 테스트: 공통 기능을 담당하는 메소드로 중복된 코드를 뽑아내는 것  

**3. 상속을 통한 확장**
  템플릿 메소드 패턴
		- 상속을 통해 슈퍼클래스의 기능을 확장할 때 사용하는 가장 대표적인 방법이다.
                 - 서브 클래스에서 필요에 맞게 추상 메소드를 구현해서 사용하는 방법을 디자인한 것이다.

팩토리 메소드 패턴 		
                 - 서브클래스에서 구체적인 오브젝트 생성 방법을 결정하게 하는 것을 디자인 한 것이다.
  
상속의 단점
		- 현재 상속 받고 있는 슈퍼클래스의 다른 목적이 필요할 경우 해당 슈퍼클래스를 상속받아야 하는데, 자바에서는 다중 상속이 지원되지 않는다. 		
		- 서브클래스와 슈퍼클래스는 밀접한 관계를 가지고 있다. 즉, 슈퍼 클래스의 수정이 서브 클래스에 영향을 미친다.
