### ISSUE TITLE
Chapter6. AOP (6.5 스프링 AOP)

### ISSUE THREAD

**Issue by tmfrl1552** [FireInStove/toby-spring#11]
## 👑 스터디장
- 슬기(@tmfrl1552)

## 📖 스터디 범위
- 6.5 스프링 AOP

## 🕧 스터디 일정
- 23/8/17 (목) 09시 ~

**Comment by yougahee** [comment]
## ✏️ 11주차 (6.5)


## 빈 후처리기(BeanProstProcessor 인터페이스)
 - 빈이 만들어진 후에 빈 오브젝트를 다시 가공할 수 있게 해준다.
 - 빈 후처리기 자체를 빈으로 등록

 - DefaultAdvisorAutoProxyCreator 자동 프록시 생성 방법
 	1) 스프링에서 빈을 생성할때마다 후처리기에 빈을 보낸다.
 	2) 포인트컷을 통해 적용대상인지 확인
 	3) 대상이면 프록시 생성기에서 현재 빈에 대한 프록시를 만들기
 	4) 만들어진 프록시와 어드바이저를 연결 
 	- 일일이 ProxyFactoryBean을 등록하지 않아도 타깃 오브젝트에 자동으로 프록시가 적용되게 할 수 있다.

- 특징
	- 빈 오브젝트의 프로퍼티를 수정할 수 있고, 별도의 초기화 작업을 수행할 수 있다.
	- 만들어진 빈 오브젝트 자체를 바꿀 수도 있다.


## Pointcut
- 클래스 필터와 메소드 매처의 기능을 가지고 있다.
- 클래스 필터 : 프록시 적용할 클래스인지?
- 메소드 매처 : 어드바이스를 적용할 메소드인지?
``` java
public interface pointcut {
	ClassFilter getClassFilter();
	MethodMatcher getMethodMatcher();
}
```


## DefaultAdvisorAutoProxyCreator 동작방식
1. 등록된 빈 중에서 Advisor 인터페이스를 구현한 것을 모두 찾는다.
2. PointCut을 적용하며, 프록시 적용 대상을 선정한다.
3. 프록시 선정 대상이라면, 프록시를 만들어 원래 빈 오브젝트와 바꿔치기 한다. 
4. 원래 빈 오브젝트는 프록시를 통해서만 접근 가능하게 바뀐다.


## 학습 테스트의 중요성
- 자동으로 무엇을 해준다고 하면 정말 그런지 한 번쯤 직접 확인해보는 습관을 들이자

## 포인트컷 표현식 - AspectJExpressionPointcut
- 클래스와 메소드의 선정 알고리즘을 포인트컷 표현식을 이용해 한 번에 지정할 수 있게 해준다.
- 포인트컷 지시자를 이용해 작성
	- execution() 을 자주 사용함.
		- 이는 메소드를 실행에 대한 포인트컷이라는 의미
	- * : 와일드 카드 / .. : 무시
	- ex) execution(public int spring.learningtest.gaga.Target.getName(String) throws exception)
- 그 외 표현식
	- bean()
	- @annotation


## Aspect란?
- 핵심 기능은 아니지만, 애플리케이션을 구성하는 중요한 한가지이고, 핵심기능에 부가되어 의미를 갖는 특별한 모듈을 가리킨다.
- Advice와 PointCut을 함께 가짐


## AOP란? 
- 부가적인 기능을 분리해서 Aspect라는 독특한 모듈로 만들어서 설계하고 개발하는 방법
- OOP를 돕는 보조적인 기술 
- IoC/DI 컨테이너, Dynamic Proxy, Decorator Pattern, Proxy Pattern, 자동 프록시 생성기법, 빈 오브젝트 

## 또 다른 AOP (아마 CGLib을 말하는 게 아닐까?)
1. 바이트 코드 조작 -> 직접 수정 -> 컨테이너 사용되지 않는 환경에서 손쉽게 사용 가능
2. 훨씬 강력하고 유연한 AOP 가능

**Comment by kyueun** [comment]
## 스프링 AOP
프록시 팩토리 빈 방식의 문제점
1. 부가기능이 타깃 오브젝트마다 생성 -> `ProxyFactoryBean` 어드바이스를 통해 해결
2. 타깃 오브젝트마다 비슷한 `ProxyFactoryBean` 빈 설정정보 추가

### 빈 후처리기
- 스프링 빈 오브젝트로 만들어지고 난 후, 빈 오브젝트를 다시 가공할 수 있음
- `BeanPostProcessor` 인터페이스 구현

`DefaultAdvisorAutoProxyCreator`
- 어드바이저를 이용한 자동 프록시 생성기
- 빈 후처리기 자체를 빈으로 등록, 빈 후처리기가 등록되어 있으면 스프링이 빈 오브젝트 생성될 때마다 빈 후처리기에 후처리 작업 요청
- 빈 후처리기를 통해서 빈 오브젝트 프로퍼티 수정, 초기화, 다른 오브젝트로 바꿔치기 가능
    - 스프링 빈 오브젝트의 일부를 프록시로 포장하고, 프록시를 빈으로 대신 등록
- 프록시 자동생성
    1. 빈으로 등록된 모든 어드바이저 내의 포인트컷을 이용해 전달받은 빈이 프록시 적용 대상인지 확인
    2. 프록시 적용 대상이면, 내장된 프록시 생성기에 현재 빈에 대한 프록시를 만들게 함
    3. 만들어진 프록시에 어드바이저 연결
    4. 프록시 오브젝트를 스프링 컨테이너에 반환
    5. 스프링 컨테이너는 프록시 오브젝트를 빈으로 등록, 사용

### 포인트컷
```java
public interface Pointcut {
    
    ClassFilter getClassFilter();
    MethodMatcher getMethodMatcher();
}
```
- `getClassFilter()` : 프록시 적용 대상 클래스인지 확인
    - 클래스 필터에서 통과하지 못하면 프록시를 만들 필요가 없음 -> 어떤 메소드에도 부가기능이 적용되지 않기 때문
- `getMethodMatcher()` : 어드바이스 적용할 메소드인지 확인

### 포인트컷 표현식
- 표현식 언어를 사용해 포인트컷 작성
- 프레임워크 `AspectJ` 에서 제공하는 것을 가져와 일부 문법 확장해서 사용

포인트컷 지시자를 이용해 작성
- `execution()`
    - `execution([접근제한자 패턴] 타입패턴 [타입패턴.]이름패턴 (타입패턴 | "..", ...) | [throws 예외 패턴])`
        - [접근 제한자 패턴] : `public`, `protected`, `private` ... - 생략 가능
        - 타입패턴 : 리턴 값의 타입 패턴
        - [타입패턴.] : 패키지, 클래스 이름 패턴 -  생략 가능
        - 이름패턴 : 메소드 이름 패턴
        - (타입패턴 | "..", ...) : 파라미터 타입 패턴 순서대로, 와일드카드 사용 가능
        - [throws 예외 패턴] : 예외 이름 패턴 - 생략 가능
    - ex. `execution(public int springbook.learningtest.spring.prointcut.Target.minus(int,int) throws java.lang.RuntimeException)`
- `bean()` : 빈 이름으로 비교
    - ex. `bean(*Service)`
- `annotation()` : 해당 어노테이션이 붙은 모든 메소드
    - ex. `annotation(org.springframework.transaction.annotation.Transactional)`

### AOP
애스펙트 지향 프로그래밍
- 애스펙트 : 어플리케이션의 핵심기능을 담고 있지는 않지만, 핵심기능에 부가되어 의미를 갖는 모듈
- 어드바이저는 아주 단순한 형태의 애스펙트

핵심기능 코드 사이의 부가기능을 독립적인 모듈인 애스펙트로 구분해서 설계, 개발하는 방법
- AOP는 OOP를 돕는 보조적인 기술, OOP를 대체하는 개념이 아님

### AOP 적용 기술
1. 프록시를 이용한 AOP
    - ex. 스프링 AOP : 빈을 프록시로 바꿔주는 간접적인 방법
2. 바이트코드 생성과 조작을 통한 AOP
    - ex. AspectJ : 타깃 오브젝트를 뜯어고쳐 부가 기능을 직접 넣어주는 직접적인 방법 사용
        - 클래스 파일 자체를 수정하거나, 클래스가 JVM에 로딩되는 시점을 가로채서 바이트코드를 조작
        - 스프링과 같은 DI 컨테이너의 도움 없이 AOP 적용 가능
        - 프록시 방식보다 훨씬 강력하고 유연

### AOP 네임스페이스
스프링에서 AOP를 위해 적용되는 빈들(자동 프록시 생성기, 어드바이스, 포인트컷, 어드바이저, ...)을 간편하게 등록
- \<aop:config\>, \<aop:pointcut\>, \<aop:advisor\> 태그 정의하면 빈 자동 등록

**Comment by tmfrl1552** [comment]
# 6.5 스프링 AOP
### 빈 후처리기를 이용한 자동 프록시 생성기
관심을 가질만한 확장 포인트는 바로 BeanPOstProcessor 인터페이스를 구현해서 만드는 '빈 후처리기'
	* 스프링 빈 오브젝트로 만들어지고 난 후에, 빈 오브젝트를 다시 가공할 수 있게 해줌

* DefaultAdvidorAutoProxyCreator 
	* 스프링이 제공하는 빈 후처리기 중 하나
	* 어드바이저를 이용한 자동 프록시 생성기 
	* 빈 후처리기 자체를 빈으로 등록
		* 스프링은 빈 후처리기가 빈으로 등록되어 있으면 빈 오브젝트가 생성될 때 마다 
		  빈 후처리기에 보내서 후처리 작업 요청
		* 만들어진 빈 오브젝트 자체를 바꿔치기 할 수도 있음
	* 스프링이 생성하는 빈 오브젝트의 일부를 프록시로 포장하고, 프록시를 빈으로 대신 등록 
	  ➡️ 자동 프록시 생성 빈 후처리기
	* 빈 후처리기는 프록시가 생성되면 원래 컨테이너가 전달해준 빈 오브젝트 대신, 프록시 오브젝트를 컨테이너에게 돌려줌
		* 컨테이너는 최종적으로 빈 후처리기가 돌려준 오브젝트를 빈으로 등록하고 사용

<br>

### 확장된 포인트컷
포인트컷은 '클래스 필터'와 '메소드 매처' 두 가지를 돌려주는 메소드 존재

```java
public interface PointCut {
	ClassFilter getClassFilter(); // 프록시를 적용할 클래스인지 확인
	MethodMatcher getMethodMatcher(); // 어드바이스를 적용할 메소드인지 확인
}
```

* DefaultAdvidorAutoProxyCreator는 클래스와 메소드 선정 알고리즘을 모두 갖고 있는 포인트 컷 필요
	* 그런 포인트컷과 어드바이스가 결합되어 있는 어드바이저 등록

<br>

### 어드바이저를 이용하는 자동 프록시 생성기 등록
* 빈 클래스가 프록시 선정 대상이라면 프록시를 만들어 원래 빈 오브젝트와 바꿔치기
* 원래 빈 오브젝트는 프록시 뒤에 연결돼서 프록시를 통해서만 접근하게 바뀜
	* 타깃 빈에 의존한다고 정의한 다른 빈들은 프록시 오브젝트를 대신 DI

<br>

### 어드바이스와 어드바이저
* 어드바이저를 이용하는 자동 프록시 생성기인 DefaultAdvidorAutoProxyCreator에 의해 자동 수집되고,
  프록시 대상 선정 과정에 참여, 자동생성된 프로시에 다이내믹하게 DI 돼서 동작하는 어드바이저가 됨.

<br>

### 자동 프록시 생성기를 사용하는 테스트
자동 프록시 생성기라는 스프링 컨테이너에 종속적인 기법 사용
* ➡️ 예외상황을 위한 테스트 대상도 빈으로 등록해줄 필요가 있음 
* 타깃을 코드에서 바꿔치기할 방법도 없을 뿐더러, 
	  자동 프록시 생성기의 적용이 되는지도 빈을 통해 확인 필요

<br>

### 자동생성 프록시 확인
> 트랜잭션 어드바이스를 적용한 '프록시 자동생성기'를 빈후처리기 매커니즘을 통해 적용

#### 최소한 두가지 확인 필요
1. 트랜잭션이 필요한 빈에 트랜잭션 부가기능 적용됐는지 확인
2. 아무 빈에나 트랜잭션이 부가기능이 적용된 것은 아닌지 확인

<br>

## 포인트컷 표현식을 이용한 포인트컷
스프링은 아주 간단하고 효과적인 방법으로 포인트컷 클래스와 메소드를 선정하는 알고리즘을 작성할 수 있는 방법 제공

### 포인트컷 표현식
* 정규식이나 JSP의 EL과 비슷한 일종의 표현식 언어를 사용해서 포인트컷을 작성할 수 있도록 하는 방법
* AspectJ라는 유명한 프레임워크에서 제공하는 것을 가져와 일부 문법을 확장해서 사용
	* ➡️ 'AspectJ 포인트컷 표현식' 이라고도 부름
<br>

### 포인트컷 표현식 문법
* AspectJ 포인트컷 표현식은 '포인트컷 지시자'를 이용해 작성
* 포인트컷 지시자 중 가장 대표적으로 사용되는 것은 execution()

```java
execution([접근제한자 패턴] 리턴타입패턴 [타입패턴.]메소드이름패턴 (파라미터타입패턴 | "..", ...)
[throws 예외 패턴])
```
	* [] 괄호는 옵션항목이므로 생략 가능
	* | 는 OR 조건
	* 파라미터 타입 패턴 (필수 항목)
		* () ➡️ 파리미터가 없는 메소드를 지정 		
		* '..' ➡️ 파라미터 타입과 개수에 상관 없이 모두 다 허용
		* '...' ➡️ 뒷 부분의 파라미터 조건만 생략

<br>

### 포인트컷 표현식 테스트
``` java
execution(* *..TargetInterface.*(..))
```
* 빈으로 등록된 클래스의 단순한 이름만 비교했던 방식돠 달리 포인트컷 표현식은 인터페이스, 슈퍼클래스의 타입도 인식
	* 클래스 이름 패턴이라기 보다는 '타입 패턴'이라고 부르는 것.

<br>

### 포인트컷 표현식을 이용하는 포인트컷 적용
#### 포인트컷 표현식의 장/단점
* 장점
	* 로직이 짧은 문자열에 담기기 때문에 클래스나 코드를 추가할 필요가 없어서 코드와 설정이 모두 단순해짐
* 단점
	* 문자열도 된 표현식이므로 런타임 시점까지 문법의 검증이나 기능이 확인되지 않음

<br>

### AOP: 애스팩트 지향 프로그래밍
#### 애스팩트(Aspect)
* 핵심기능에 부가되어 의미를 갖는 특별한 모듈
* 그 자체로 애플리케이션의 핵심 기능을 담고 있지는 않지만, 애플리케이션을 구성하는 중요한 한기지 요소
* 부가기능을 정의한 코드인 '어드바이스' + 어드바이스를 어디에 적용할지를 결정하는 '포인트컷' 을 함께 가지고 있음

#### AOP (Aspect Oriented Programming)
* 애플리케이션의 핵심적인 기능에서 부가적인 기능을 분리해서 
  애스팩트라는 독특한 모듈로 만들어 설계하고 개발하는 방법
* 애플리케이션을 다양한 측면에서 독립적으로 모델링하고, 설계하고, 개발할 수 있도록 만들어주는 것
* 애플리케이션을 특정한 관점을 기준으로 바라볼 수 있게 해준다는 의미에서 ➡️ 관점 지향 프로그래밍 이라고도 부름

<br>

## AOP 적용 기술
### 프록시를 이용한 AOP
* 프록시로 만들어서 DI로 연결된 빈 사이에 적용해 타깃의 메소드 호출과정에 참여해서 부가기능 제공
* 스프링 AOP는 프록시 방식의 AOP
	* 독립적으로 개발한 부가기능 모듈을 다양한 타깃 오브젝트의 메소드에 다이내믹하게 적용해주기 위해 
	  가장 중요한 역할을 맡고있는게 '프록시'

<br>

### 바이트코드 생성과 조작을 통한 AOP
* 가장 강력한 AOP 프레임워크로 꼽히는 AspectJ는 프록시를 사용하지 않는 대표적인 AOP 기술
	* 프록시처럼 간접적인 방법이 아닌, 타깃 오브젝트를 뜯어고쳐서 부가적인 기능을 직접 넣어주는 집적적인 방법
	* 컴파일된 타킷의 클래스 파일 자체를 수정하거나 클래스가 JVM에 로딩되는 시점을 가로채서
	  바이트 코드를 조작하느 복잡한 방법 사용

* 바이트코드 조작과 같은 복잡한 방법 사용 이유
	* 1. 바이트코드를 조작해서 타깃 오브젝트를 직접 수정 시 스프링과 같은 DI 컨테이너의 도움을 받아 
	     자동 프록시 생성 방식을 사용하지 않아도 AOP 적용 가능
	* 2. 프록시 방식 보다 훨씬 강력하고 유연한 AOP 가능
		* 오브젝트의 생성, 필드 값의 조회와 조작, 스태틱 초기화 등의 다양한 작업에 부가기능 부여 가능
		* 프록시 AOP의 핵심 매커니즘 사용 > 클라이언트가 호출할 때 사용하는 메소드로 제한 

> 일반적인 AOP 적용하는데는 프록시 방식의 스프링 AOP로 충분

<br>

## AOP 용어
#### 타깃
* 부가 기능을 부여할 대상

#### 어드바이스
* 타깃에게 제공할 부가기능을 담은 모듈
* 어드바이스는 오브젝트로 정의하기도 하지만 메소드 레벨에서 정의할 수도 있음

#### 조인 포인트
* 어드바이스가 적용될 수 있는 위치
* 타깃 오브젝트가 구현한 인터페이스의 모든 메소드는 조인포인트가 됨

#### 포인트컷
* 어드바이스를 적용할 조인 포인트를 선별하는 작업 또는 기능을 정의한 모듈
* 스프링 AOP 조인포인트는 메소드 실행이므로, 스프링의 포인트컷은 메소드 선정 기능 가짐

#### 프록시
* 클라이언트와 타깃 사이에 투명하게 존재하면서 부가기능을 제공하는 오브젝트
* DI를 통해 타깃 대신 클라이언트에게 주입, 클라이언트의 메소드 호출을 대신 받아 타킷에 위임해주면서
  부가기능 부여

#### 어드바이저
* 포인트컷과 어드바이스를 하나씩 갖고 있는 오브젝트
* 어떤 부가기능(어드바이스)을 어디에(포인트컷) 전달할 것인가를 알고 있는 AOP의 가장 기본이 되는 모듈

#### 애스펙트
* AOP의 기본 모듈
* 한개 또는 그 이상의 포인트컷과 어드바이스의 조합으로 만들어지며 보통 싱글톤 형태의 오브젝트로 존재

<br>

### AOP 네임스페이스
스프링에서는 AOP를 위해 기계적으로 적용하는 빈(자동 프록시 생성기, 어드바이스, 포인트컷, 어드바이저)들을
간편한 방법으로 등록 가능

* aop 스키마 전용 태그를 사용하는 경우 > 포인트컷을 독립적인 태그로 두고 어드바이저 태그에서 참조하는 대신 
	  어드바이저 태그와 결합하는 방법도 가능
* 하나의 포인트컷을 여러개의 어드바이저에서 공유하는 경우 독립적인 <aop:pointcut> 태그로 등록

``` java
<aop:config>
	<aop:pointcut id="transactionPointcut">
					expression="execution(* *..*ServiceImpl.upgrade*(..))" />
	<aop:advisor advice-ref="transactionAdvice" pointcut-ref="transactionPointcut" />
</aop:config>
```

**Comment by aimhigh53** [comment]
## 6.5 스프링 AOP
### 자동 프록시 생성
    * 타킷마다 거의 비슷한 내용의 프록시팩토리빈 설정정보를 추가해야함
### 빈후처리기를 이용항 자동프록시 생성기
    * BeanPostProcesser 인터페이스를 구현해 만드는 빈후처리기
    * 스프링빈으로 만들어 빈을 가공
    * DefaultAdvisorAutoProxyCreator 스프링에서 제공하는 빈후처리기
        * 어드바이저를 이용한 자동 프록시 생성기
        * 빈이 생성될떄마다 빈후처리기로 보내 후처리작업을 요청
        * 빈 프로퍼티를 강제로 수정, 별도의 초기화 작업가능 ⇒ 이를 활용해 프록시를 빈으로 대신 등록
    * 동작
        1. 빈후처리기가 있으면 스프링은 빈을 만들때 후처리기로 보낸다.
        2. 모든 어드바이저내의 포인트컷으로 프록시 적용대상인지 확인
        3. 빈에대한 프록시를 만들고 어드바이저를 연결
        4. 원래 빈 대신 프록시를 컨테이너에게 반환
###  포인트컷
    * 메소드 Matcher와 클래스 필터를 가지고있음
###  DefaultAdvisorAutoProxyCreator
    * 어드바이저를 이용하는 자동프록시 생성기 등록
### 자동 프록시 테스트
* UserService 등록
        * 기호는 스태틱 멤버클래스를 지정할때 사용
        * 특정 테스트 클래스에서만 사용되는 거면 스태틱 멤버클래스로 정의하는 것이 편리
    * 자동프록시 확인 자동으로 된다고하면 한번쯤 직접확인해 보는 습관을 가지자!
        * 확인사항
            1. 트랙잭션 부가기능이 적용되는지 → 롤백테스트
            2. 아무 빈에나 적용된게 아닌지 확인
###  포인트컷 표현식을 이용한 포인트컷
    * 위는 이름패턴을 각각 클래스 필터, 메서드 매처로 비교해서 선정함
    * 세밀하게 적용하려면 리플렉션 API 를 쓸수 있으나 번거로움
    * 표현식 언어를 사용해 포인트컷을 작성하는 것이 포인트컷 표현식
    * 스프링의 포인트컷 표현식은 AspectJ라는 프레임워크에서 제공한걸 사용
    * 표현식 문법
        * execution() 가장 대표적으로 사용
        * [접근제한자 패턴] 타입패턴 [타입패턴.]이름패턴 (타입패턴 | ".. ", ... )[throws 예외 패턴]
        * 리플렉션의 Class.getMethod 로 메소드의 풀 시그니처 확인가능
    * 적용
        * 특정 어노테이션으로 포인트컷 선정하는 것도 가능 @Transactioal
        * 단점은 런타임시점까지 문법의 검증이나 기능확인이 되지않음
        * 클래스 이름 패턴이 아니라 타입패턴으로 등록됨
            * 슈퍼클래스 구현인테페이스도 포함
###  AOP란 무엇인가?
    * 트랙잭션 서비스 추상화
        * 트랙잭션 기술이 비즈니스로직에 종속 → 인터페이스와 DI로 분리
    * 프록시 데코레이터 패턴
        * 투명한 부가기능 부여를 가능하게 하는 데코레이터 : 클라이언트 → {데코레이터[트랜잭션] - 타킷}
    * 다이나믹 프록시와 팩토리빈
        * 비즈니스 로직 인터페이스의 모든 메소드마다 기능부여하는 코드추가
            * 불필요한 메서드에도 일일히 구현
        * 프록시 클래스를 자동으로 만들자!
            * 런타임시 JDK 다이나믹프록시
                * 동일기능 프록시를 여러 타킷에 적용시 타깃단위로 중복
            * 스프링팩토리빈
                * 어드바이스 + 포인트컷을 프록시에서 분리 및 공유사용
    * 자동프록시 생성
        * 빈마다 일일히 팩토리빈 등록해야함
            * 빈생성 후처리기 기법 적용 → 포인트컷이라는 독립정보로 완전분리
    * 부가기능 모듈화
        * 서로 낮은 결합도, 유연성, 확장성
        * 부가기능이기 때문에 스스로 독립적으로 존재하기는 힘듬
    * AOP: 에스팩트 지향 프로그래밍
        * 부가기능 모듈을 에스펙트라고 부르기 시작
        * 핵심기능은 아니지만 중요한 요소
        * 여러 부가기능은 결국 핵심 기능과 함께 어우러져 동작
        * 핵심기능에서 부가기능을 분리해서 에스팩트로 개발하는 방법 → 에스팩트 지향 프로그래밍
        * OOP를 돕는 보조적인 기술
###  AOP 적용기술
    * 프록시를 이용한 AOP
        * 타깃 메서드에 다이나믹하게 적용해주기 위해 중요한 역할
        * 스프링 AOP는 프록시 방식이다
    * 바이트코드 조작 AOP (AspectJ)
        * JVM 로딩시점을 가로채서 바이트코드를 조작
        * 컨테이너 사용되지 않는 환경에서도 가능
        * 다양한 작업에 부가기능 부여가능
==
`
    1. 바이트코드 조작 AOP
장점:
성능: 클래스 로드 시간에 바이트코드가 수정되기 때문에 일반적으로 프록시 기반 접근 방식에 비해 런타임 오버헤드가 적습니다.
투명성: 변경 사항은 바이트코드 수준에서 이루어지므로 특별한 프록시 클래스 없이도 응용 프로그램에 더 투명할 수 있습니다.
적용성: 특정 인터페이스를 구현하는 개체뿐만 아니라 거의 모든 개체에 적용할 수 있습니다.
단점:
복잡성: 바이트코드로 작업하려면 JVM(Java Virtual Machine)에 대한 깊은 지식이 필요하므로 구현 및 디버그가 더 복잡할 수 있습니다.    
        
      -> 2. 프록시 기반 AOP
장점:
단순성: 프록시 기반 AOP는 개체 수준에서 작동하므로 이해하고 작업하기가 더 쉬운 경우가 많습니다.
유연성: 런타임에 프록시를 추가하거나 제거할 수 있으므로 보다 동적인 동작이 가능합니다.
`
==

###  AOP 용어
    * 조인포인트
        * 어드바이스가 적용될수 있는 위치
    * 어드바이스
        * 부가기능을 담은 모듈
