### ISSUE TITLE
Chapter 6. AOP (6주차)

### ISSUE THREAD

**Issue by yougahee** [FireInStove/toby-spring#12]
## 👑 스터디장
- 가희(@yougahee)
## 📖 스터디 범위
- ~6장 끝까지
## 🕧 스터디 일정
- 23/8/24 (목) 09시 ~

**Comment by yougahee** [comment]
## ✏️ 12주차 (~6장 끝)

## 트랜잭션 
- 더 이상 쪼갤 수 없는 최소 단위의 작업

### 트랜잭션 전파 
- 트랜잭션 경계에서 이미 진행 중인 트랜잭션이 있을 때 또는 없을 때 어떻게 동작할 것인가를 결정하는 방식

1) PROPAGATION_REQUIRED
- 가장 많이 사용되는 트랜잭션 전파 속성
- 진행 중인 트랜잭션이 없으면 새로 시작하고, 이미 시작된 트랜잭션이 있으면 이에 참여한다.

2) PROPAGATION_REQUIRES_NEW
- 항상 새로운 트랜잭션을 시작한다.

3) PROPAGATION_NOT_SUPPORTED
- 트랜잭션을 무시
- 해당 옵션이 있는 이유 : 특정 메소드에 대해 트랜잭션 없이 동작하도록 하는 게 좋다.

### 격리 수준
- 모든 DB 트랜잭션은 격리수준을 갖고 있어야 한다.

### DefaultTransactionDefinition
- 격리수준 : ISOLATION_DEFALUT
	- ???
- timeout : 없음
	- 해당 옵션은 PROPAGATION_REQUIRED 또는 PROPAGATION_REQUIRES_NEW 을 사용해야 의미가 있다.

### transactionInterceptor
- 트랜잭션 경계설정 어드바이스
- transactionAdvice와 비슷하지만, 트랜잭션 정의를 "메소드 이름 패턴"을 이용해서 다르게 지정할 수 있는 방법을 추가로 제공해준다.

- TransactionAttribute > 트랜잭션 속성을 정의한 프로퍼티
	- rollbackOn
		- 어떤 예외가 발생하면 롤백을 할 것인가 결정하는 메소드
- 예외처리 방식
	1) 런타임 예외가 발생하면 트랜잭션은 롤백 (체크 예외는 제외)
	2) rollbackOn() >> 다른 예외처리


## 포인트 컷 & 트랜잭션 속성 전략
1) 트랜잭션용 포인트 컷 표현식에 메소드나 파라미터, 예외에 대한 패턴을 정의하지 않는 게 좋다.
	- 가능하면 인터페이스 타입을 기준으로 타입 패턴을 적용하는 것이 좋다.
	- bean() 표현식으로 쓰면 좋다.
2) 공통된 메소드 이름 규칙을 통해 "최소한"의 트랜잭션 어드바이스와 속성을 정의한다.
	- 트랜잭션 속성이 다양하게 사용될 경우는 많이 없다. (관리만 힘들 뿐.)
	- 가장 단순한 속성을 정의해주고, 예외 케이스를 정의해나가는 것이 좋음.

3) AOP는 같은 오브젝트 내의 메소드를 호출할 때는 적용되지 않는다.
	- 많이 했던 실수!


## 트랜잭션 애노테이션
### @Transactional
- 타깃 : 메소드, 타입(클래스, 인터페이스)
- 사용되는 pointcut : TransactionAttributeSourcePointcut
- 포인트컷과 트랜잭션 속성을 애노테이션 하나로 지정할 수 있다.
- 트랜잭션 부가기능 적용 단위 : 메소드

## 트랜잭션 fallback 
1) 메소드 확인
2) 있으면 끝! 없으면 클래스 확인
3) 있으면 끝! 없으면 인터페이스 메소드 확인
4) 없으면 인터페이스 타입 확인
	- 단, 프록시 방식의 AOP가 아니면, 인터페이스 타입은 확인하지 않으니 잘 파악할 것


## 선언적 트랜잭션
- 정의 
	- AOP를 이용해 코드 외부에서 트랜잭션의 기능을 부여해주고, 속성을 지정할 수 있게 하는 방법
- 스프링은 트랜잭션 전파 속성을 적용할 수 있도록 하여, 중복코드를 없애고 편의성 향상

## 트랜잭션 매니저
- 트랜잭션 매니저를 이용해서 트랜잭션에 참여하거나 트랜잭션을 제어하는 방법을 사용할 수도 있다.
- 대부분 사용할 일은 없지만, 테스트에서 유용하게 사용할 수 있음.


## 롤백 테스트
- 테스트 코드로 트랜잭션을 제어해서 적용할 수 있는 테스트 기법이다. 
- 트랜잭션 안에서 작업이 완료되면 무조건 롤백시킴

## 테스트 코드에서의 트랜잭션
- 테스트에서의 @Transactional은 강제 롤백됨!!(wow!!)
- 그렇다면, 테스트한 작업들을 DB에 반영하고 싶다면?
	- @Rollback(false) 을 사용하면 된다.
	- 테스트 상위 클래스에 @TransactionConfiguration(defaultRollback=false) 작성해주면 됨
- @NotTransactional
	- 테스트 메소드에 부여하면 클래스 레벨의 설정을 무시함.
	- 스프링 3.0에서는 제거됨 
	- 사실상 따로 분리하는 것을 권장.

## TIP!
- 단순 조회 작업만 하는 메소드에도 모두 트랜잭션을 적용하는 게 좋다.
	- 읽기 전용으로 트랜잭션 속성을 설정해두면 성능향상을 가져옴
- transaction 의 기능은 부가적인 기능이기에 문제가 있을 때가 되어서 파악할 수 있으니 리뷰를 꼭 하자! 
- 테스트는 어떤 경우에서도 서로 의존하면 안된다.

**Comment by flyingtw** [comment]
# 6.6 트랜잭션 속성
## 6.6.1 트랜잭션 정의
- 트랜잭션은 더이상 쪼갤 수 없는 최소 단위의 작업
### 트랜잭션 전파
- 트랜잭션 진행중에 다른 트랜잭션이 동작할경우 같이 롤백을 할지 안할지를 정의하는것이 트랜잭션 전파 속성이다.
#### PROPAGATION_REQUIRED
- 진행중인 트랜잭션이 없으면 새로 시작, 이미 시작된게 있으면 같이 참여
#### PROPAGATION_REQUIRES_NEW
- 항상 새로 시작
#### PROPAGATION_NOT_SUPPORTED
- 트랜잭션 없이 동작
- 여러 트랜잭션이 동시에 진행될때 하나는 무조건 진행되어야 할때 사용
### 격리수준
- 트랜잭션은 성능을 위해서 적절한 격리수준을 설정하는게 좋다. 
- ISOLATION_DEFAULT : DataSource에 설정된 디폴트 격리수준을 사용하는것
### 제한시간
- 트랜잭션 시동의 제한시간을 설정하는것
### 읽기전용
- 트랜잭션 내에서 데이터를 조작하는걸 막을 수 있다.
## 6.6.2 트랜잭션 인터셉터와 트랜잭션 속성
- 메소드별로 서로 다른 트랜잭션을 정의하러면 어드바이스의 기능을 확장해야 한다.
### TransactionInterceptor
- 스프링은 비즈니스 로직중간에 예외가 발생할경우 체크 예외를 통해 롤백을 시키지 않아도 되게 하는방식이 있다.
- 하지만 commit을 하고싶지 않을때가 있기때문에 rollbackOn()을 사용한다.
### 메소드 이름 패턴을 이용한 트랜잭션 속성 지정
- + : 런타임 예외라도 커밋하게 만들 수 있다.
- - : 기본 원칙을 따르지 않는 예외를 정의해주는 것이다.
## 6.6.3 포인트컷과 트랜잭션 속성의 적용 전략
- 트랜잭션 포인트컷 표현식에 타입 패턴이나 빈 이름을 사용하여 트랜잭션을 관리할 수 있으며, 보통 인터페이스에 적용하는걸 권장한다.
- 공통된 메소드 이름 규칙을 이용하여 처리하는게 편하지만 일반적이지 않은 오브젝트가 존재하기도 하는데 이럴땐 트랜잭션 어드바이스와 포인트컷을 새롭게 추가해줄 필요가 있다.
- 타깃 오브젝트 안에서 메소드 호출이 일어나는 경우에는 프록시 AOP를 통해 부여해준 부가기능이 적용되지 않는다.
## 6.6.4 트랜잭션 속성 적용
- 트랜잭션은 서비스 단위로 적용하는것이 좋다.
# 6.7 애노테이션 트랜잭션 속성과 포인트컷
- 클래스나 메소드에 따라 속성이 다른 트랜잭션을 사용해야 할 경우은 이름패턴을 적합하지 않다.
(service에 일괄적으로 적용하는등..)
## 6.7.1 트랜잭션 애노테이션
- @Transactional : 메소드, 클래스, 인터페이스에 트랜잭션의 속성을 커스텀하게 적용시킬 수 있다.
### 대체 정책
- 애너테이션을 반복적으로 모든 메서드에 붙일 순 없는 노릇이다.
- 따라서 4가지의 대체 정책을 이용하게 해준다.
- 작은단위의 메서드부터 올라가면서 트랜잭션 적용 대상인지를 확인한다.
## 6.7.2 트랜잭션 애노테이션 적용
- 큰단위의 클래스에 범용적인 트랜잭션 어노테이션을 걸고 메서드 단위에선 세부적인 트랜잭션 어노테이션을 걸도록 하자.
# 6.8 트랜잭션 지원 테스트
## 6.8.1 선언적 트랜잭션과 트랜잭션 전파 속성
- AOP를 이용해 코드 외부에서 트랜잭션의 기능을 부여해주고 속성을 지정할 수 있게 하는 방법이 선언적 트랜잭션이고, 반대로 트랜잭션 템플릿이나 데이터 기술의 트랜잭션 API를 사용해 직접 코드안에서 사용하는 방법은 프로그램에 의한 트랜잭션이라고 한다.
- 선언적 트랜잭션을 사용하는게 바람직하다.

**Comment by kyueun** [comment]
## 트랜잭션 속성
### 트랜잭션
더 이상 쪼갤 수 없는 최소 단위의 작업
- 트랜잭션 경계 안에서 진행된 작업은 `commit()`을 통해 모두 성공하든지 `rollback()`을 통해 모두 취소되어야 함

트랜잭션 속성
1. 트랜잭션 전파 : 트랜잭션의 경계에서 이미 진행 중인 트랜잭션이 있거나 없을 때 동작 방식
    - `PROPAGATION_REQUIRED` : 진행 중 트랜잭션이 없으면 시작, 있으면 참여, 기본 전파 속성
    - `PROPAGATION_REQUIRES_NEW` : 항상 새로운 트랜잭션을 시작
    - `PROPAGATION_NOT_SUPPORTED` : 진행 중 트랜잭션이 있어도 무시, 트랜잭션 없이 동작
2. 격리 수준 : 동시에 여러 트랜잭션을 진행시킬 때, 문제가 없도록 제어
    - `ISONATION_DEFAULT` : DataSource의 디폴트 격리수준을 따름, 기본 격리 수준
3. 제한 시간 : 트랜잭션 수행 제한 시간, 없는 게 기본 설정
4. 읽기 전용 : 트랜잭션 내에서 데이터 조작하는 시도를 막아줄 수 있음

TransactionInterceptor
- 스프링의 트랜잭션 경계설정 어드바이스
- 프로퍼티
    - PlatformTransactionManager
    - Properties : 트랜잭션 속성 정의
- 예외 처리 방식
    - 기본 원칙
        - 런타임 예외 발생 : 롤백
        - 체크 예외 발생 : 비즈니스 로직에 따른 리턴 방식으로 인식, 트랜잭션 커밋
    - `rollbackOn()` : 기본 원칙과 다른 예외처리를 가능하게 해줌
- 메소드 이름 패턴을 이용해 속성 지정
    - `PROPAGATION_*` : 전파 방식
    - `ISOLATION_*` : 격리 수준
    - `readOnly` : 읽기 전용 ( 생략 가능 )
    - `timeout_*` : 제한 시간, 초 단위 시간 입력 ( 생략 가능 )
    - `-Exception1` : 체크 예외 중 롤백 대상
    - `+Exception2` : 런타임 예외 중 롤백시키지 않을 예외

포인트컷과 트랜잭션 속성의 적용 전략
1. 트랜잭션 포인트컷 표현식은 타입 패턴이나 빈 이름 이용
    - `execution()`, `bean()`
2. 공통된 메소드 이름 규칙을 통해 최소한의 트랜잭션 어드바이스, 속성 정의
    - 몇 가지 속성을 정의하고, 메소드 명명 규칙을 만들어 적용해서 하나의 어드바이스로 모든 빈에 속성 지정
    - 가끔 패턴이 다른 경우에만 어드바이스와 포인트컷 새롭게 추가
3. 프록시 방식 AOP는 같은 타깃 오브젝트 내 메소드를 호출할 때는 적용되지 않음
    - 프록시를 통한 부가기능 적용은 클라이언트( =인터페이스를 통해 타깃 사용하는 다른 오브젝트 )로부터 호출이 일어날 때만 가능
    - 같은 타깃 오브젝트 내 메소드 호출하는 경우에는, 프록시를 거치지 않으므로 적용되지 않음
    - 적용해야 하는 경우에는, 스프링 API로 프록시 레퍼런스 가져온 다음에 호출하거나, 프록시 외 방식 AOP 기술 적용 필요

## 애노테이션 트랜잭션 속성과 포인트컷
### @Transactional
- 타깃 : 메소드, 타입
- 기본적으로 트랜잭션 속성의 정의하는 것이지만, 동시에 포인트컷 자동등록에도 사용
- 트랜잭션 부가기능 적용 단위 : 메소드

fallback 정책
- 타깃 메소드 -> 타깃 클래스 -> 선언 메소드 -> 선언 타입 순서에 따라 `@Transactional` 적용됐는지 메소드 속성 차례로 확인
- 가장 먼저 발견되는 속성정보 사용

### 트랜잭션 지원 테스트
- 선언적 트랜잭션 : AOP를 이용해 코드 외부에서 트랜잭션 기능 부여, 속성 지정 가능
- 프로그램에 의한 트랜잭션 : 개별 데이터 기술의 트랜잭션 API를 사용해 직접 코드 안에서 사용

테스트를 위한 트랜잭션 애노테이션
- `@Transactional` : 일반 타깃 클래스, 이넡페이스에 적용된 것처럼 경계 설정
- `@Rollback` : 롤백 여부 지정 가능 - `@Rollback(true)`=롤백, `@Rollback(false)`=커밋
- `@TransactionConfiguration` : 롤백에 대한 공통 속성 지정 가능
- `@NotTransactional` : 클래스 레벨의 `@Transactional` 무시, 트랜잭션을 시작하지 않고 테스트 진행
     - 스프링 3.0에서 제거 대상
     - 트랜잭션을 시작하지 않게 하려면 `@Transactional(propagation=NEVER)` 해도 됨

**Comment by tmfrl1552** [comment]
# 6.6 트랜잭션 속성
## 트랜잭션 정의
### 트랜잭션 전파
트랜잭션의 경계에서 이미 진행 중인 트랜잭션이 있을 떄 또는 없을 땨 어떻게 동작할 것인가를 결정하는 방식

#### PROPAGATION_REQUIRED
* 진행중인 트랜잭션이 없으면 새로 시작하고, 이미 시작된 트랜잭션이 있으면 이에 참여
	* 가장 많이 사용되는 트랜잭션 전파 속성
	* DefaultTransactionDefinition 트랜잭셩의 전파 속성

#### PROPAGATION_REQUIRED_NEW
* 항상 새로운 트랜잭션 시작
* 독립적이 트랜잭션이 보장돼야 하는 코드에 적용

#### PROPAGATION_NOT_SUPPORTED
* 트랜잭션 없이 동작, 진행 중인 트랜잭션이 있어도 무시
* 특별한 메소드만 트랜잭션 적용해서 제외하려면?
	* 모든 메소드에 트랜잭션 AOP가 적용되게 하고, 특정 메소드의 트랜잭션 전파 속성만 
	  PROPAGATION_NOT_SUPPORTED 로 설정해서 트랜잭션 없이 동작하게 생성

* 트랜잭션 매니저를 통해 트랜잭션 시작 시 getTransaction 사용 이유
	* ➡️ '트랜잭션 전파 속성'이 있기 떄문



### 격리 수준
> 모든 DB 트랜잭션은 격리 수준을 갖고 있어야 한다.

* 기본적으로 DB에 격리수준이 설정되어 있지만 JDBC 드라이버나 Datasource 등에서 재설정 가능,
  필요하다마녀 트랜잭션 단위로 격리수준 조정 가능
* DefaultTransactionDefinition 격리 수준 : ISOLATION_DAFAULT
	* DataSource에 설정되어 있는 디폴트 격리수준 따름


### 제한시간
* DefaultTransactionDefinition 기본 설정은 무제한
* PROPAGATION_REQUIRED / PROPAGATION_REQUIRED_NEW 사용시 의미가 있음

### 읽기전용
* 읽기전용 설정 시 트랜잭션 내에 데이터를 조작하는 시도를 막을 수 있음
* 데이터 액세스 시굴에 따라 성능 향상


* 트랜잭션 정의를 바꾸고 싶다면?
	* 디폴트 속성을 갖고 있는 DefaultTransactionDefinition 사용하는 대신,
	  'TransactionDefinition 오브젝트를 DI' 받아서 사용
	* 해당 방법으로 트랜잭션 속성 변경 시, TransactionAdvice를 사용하는 모든 트랜잭션 속성이 
	  한꺼번에 바뀐다는 문제가 있음
	* 해당 문제를 해결하는 방법 ➡️ 메소드 이름 패턴에 따라 다른 트랜잭션 정의가 적용되도록 생성

<br>

## 트랜잭션 인터셉터와 트랜잭션 속성
### TransactionInterceptor
> 스프링에서 편리하게 트랜잭션 경계설정 어드바이스로 사용할 수 있도록 만들어짐

* 트랜잭션 정의를 메소드 이름 패턴을 이용해서 다르게 지정할 수 있는 방법 추가 제공
* PlatformTransactionManager와 Properties 타입의 투 가지 프로퍼티 제공
* Properties 타입인 두 번째 프로퍼티 이름은 transactionAttributes로, 속성을 정의한 프로퍼티
* rollbackOn() 메소드 : 어떤 예외가 발생하면 롤백을 할 것인가를 결정하는 메소드
* TransactionAttribute 이용 시 트랜잭션 부가기능의 동작 방식을 모두 제어 가능

#### TransactionInterceptor이 제공하는 두 가지 예외처리 방식
* 1. 런타임 예외 발생 시 트랜잭션 롤백
* 2. 타깃 메소드가 런타임 예외가 아닌 체크 예외를 던지는 경우,
  이것을 예외 상황이라고 해석하지 않고, 일종의 비즈니스 로직에 따른 의미가 있는 리턴 방식의 한가지로 인식하여
  트랜잭션을 커밋

이런 기본 예외처리 원칙을 따르지 않는 경우,
TransactionAttribute의 rollbackOn() 속성을 둬서 기본 원칙과 다른 예외처리 가능하게 함
	
* 특정 체크 예외의 경우 ➡️ 트랜잭션 롤백
* 특정 런타임 예외의 경우 ➡️ 트랜잭션 커밋


### 메소드 이름 패턴을 이용한 트랜잭션 속성 지정
> Properties 타입의 transactionAttributes 프로퍼티는 메소드 패턴고 트랜잭션 속성을
  키와 값으로 갖는 컬렉션

트랜잭션 속성은 다음과 같은 문자열로 정리

``` java

PROPAGATION_NAME, ISOLATION_NAME, readOnly, timeout_NNNN, -Exception1, +Exception2

```

* PROPAGATION_NAME
	* 트랜잭션 전파 방식, 필수 항목
* ISOLATION_NAME
	* 격리 수준, 생략 가능, 생략 시 디폴트 격리 수준 지정
* readOnly
	* 읽기 전용 항목, 생략 가능, 디폴트는 읽기 전용 아님
* timeout_NNNN
	* 제한 시간, 생략 가능, 초 단위 시간을 뒤에 붙임
* -Exception1
	* 체크 예외 중에서 롤백 대상으로 추가할 것을 넣음, 한 개 이상 등록 가능
* +Exception2
	* 런타임 예외지만 롤백 시키지 않을 예외 등록, 한 개 이상 등록 가능

<br>

## 포인트컷과 트랜잭션 속성의 적용 전략
### 트랜잭션 포인트컷 표현식은 타입 패턴이나 빈 이름 이용
* 트랜잭션용 포인트컷 표현식에는 메소드나 파라미터, 예외에 대한 패턴을 정의하지 않는게 바람직
* 가능하면 클래스보다는 인터페이스 타입을 기준으로 타입 패턴 적용하는 것이 좋음
	* 인터페이스는 클래스에 비해 변경 빈도가 적고 일정한 패턴을 유지하기 쉬움
* bean() 표현식은 빈 이름을 기준으로 선정하므로 클래스나 인터페이스 이름에 일정한 규칙을 만들이 어려운 경우 유용 		* 이름이 비슷한 빈이 있는 경우 주의

### 공통된 메소드 이름 규칙을 통해 초소한의 트랜잭션 어드바이스와 속성 정의
* 기준이 되는 몇 가지 트랜잭션 속성을 정의하고 그에 따라 적절한 메소드 명명 규칙을 만들어 두면
  하나의 어드바이스 만으로 애플리케이션의 모든 서비스 빈에 트랜잭션 속성 지정 가능
 * 트랜잭션 읽기 전용 속성 부여됐는데, 데이터 조작이 일어난 경우 예외 발생

### 프록시 방식 AOP는 같은 타깃 오브젝트 내의 메소드를 호출할 때는 적용되지 않음
* 프록시 방식의 AOP에서 프록시를 통한 부가 기능의 적용은 클라이언트로부터 호출이 일어날 때만 가능
* 타깃 오브젝트가 자기 자신의 메소드를 호출할 때는 프록시를 통한 부가기능의 적용이 일어나지 않음
* 타깃 안에서의 호출에는 프록시가 적용되지 않는 문제 해결 방법
	* 1. 스프링 API 이용해 프록시 오브젝트에 대한 레퍼런스 가져온 뒤 
	     같은 오브젝트의 메소드 호출도 프록시 이용하도록 강제하는 방법
	     * ➡️ 별로 추천되지 않음
	* 2. AspectJ 같은 타깃의 바이트코드를 직접 조작하는 방식의 AOP 기술 적용

<br>

## 트랜잭션 속성 적용
### 트랜잭션 경계 설정의 일원화
* 비즈니스 로직을 담고 있는 '서비스 계층 오브젝트의 메소드'가 트랜잭션 경계를 부여하기에 적절한 대상
	* 특정 계층의 경계를 트랜잭션 경계와 일치시키는 것이 바람직
* 트랜잭션은 보통 서비스 계층의 메소드 조합을 통해 만들어지기 때문에 DAO가 제공하는 주요 기능은
  서비스 계층에 위힘 메소드를 만들어둘 필요가 있음

<br>

# 6.7 애노테이션 트랜잭션 속성과 포인트컷
## 트랜잭션 애노테이션

### @Transactional
* 타깃은 메소드와 타입
	* 메소드, 클래스, 인터페이스에 사용 가능
* 스프링은 해당 애노테이션이 부여된 모든 오브젝트를 자동으로 타깃 오브젝트로 인식
* 사용되는 포인트컷 : TransactionAttributeSourcePointcut
	* 스스로 표현식과 같은 선정기준을 갖고 있진 않음
* 기본적으로 트랜잭션 속성을 정의하는 것이지만, 동시에 포인트컷의 자동등록에도 사용


### 대체 정책
* @Transactional 적용 시 4단계 대체 정책 이용
* 메소드의 속성을 확인할 때 타깃 메소드, 타깃 클래스, 선언 메소드, 선언 클래스 순서에 따라
  @Transactional이 적용됐는지 차례로 확인, 가능 먼저 발견되는 속성정보 사용
* 기본적으로 @Transactional 적용 대산은 클라이언트가 사용하는 인터페이스가 정의한 메소드이므로
  타깃 크래스보다 인터페이스에 두는게 바람직
  * 하지만 인터페이스 사용하는 프록시 방식의 AOP가 아닌 방식으로 트랜잭션 적용 시 인터페이스에 정의한 
    @Transactional은 무시되므로, 안전하게 '타깃 클래스의 @Transactional 두는 방법 권장'

 
# 6.8 트랜잭션 지원 테스트
* 선언적 트랜잭션
	* AOP를 이용해 코드 외부에서 트랜잭션의 기능을 부여해주고 속성을 지정할 수 있게 하는 방법
* 프로그램에 대한 트랜잭션
	* TransactionTemplate이나 개별 데이터 기술의 트랜잭션 API를 사용해 직접 코드 안에서
	  사용하는 방법

➡️ 특별한 경우가 아니라면 선언적 방식의 트랜잭션 사용하는 것이 바람직

<br>

## 트랜잭션 동기화와 테스트
### 트랜잭션 매니저와 트랜잭션 동기화
트랜잭션 추상화 기술의 핵심은 '트랜잭션 매니저'와 '트랜잭션 동기화'

* 진행 중인 트랜잭션이 있는지 확인하고, 트랜잭션의 전파 속성에 따라서 이에 참여할 수 있도록 만들어주는 것도
  트랜잭션 동기화 기술 덕분
* 메소드를 만들지 않고 예시의 세 메소드의 트랜잭션을 통합하는 방법
	* UserService의 메소드를 호출하기 전에 트랜잭션 미리 시작
	* 테스트에서 트랜잭션 매니저 이용해 트랜잭션을 시작시키고 이를 동기화


### 트랜잭션 동기화 검증
* JdbcTemplate 과 같이 스프리이 제공하는 데이터 액세스 추상화 적용한 DAO에도 동일한 영향 미침
* JdbcTemplate은 트랜잭션이 시작된 것이 있으면 트랜잭션에 자동으로 참여하고, 
  없으면 트랜잭션 없이 자동커밋 모드로 JDBC 작업 수행
* 조금 다르지만, JdbcTemplate 메소드 단위로 마치 트랜잭션 전파 속성이 REQUIRED 인 것 처럼 동작


### 롤백테스트
* 테스트 내의 모든 DB 작업을 하나의 트랜잭션 안에서 동작하게하고
  테스트가 끝나면 무조건 롤백해버리는 테스트
* 롤백테스트는 DB 작업이 포함된 테스트가 수행돼도 DB에 영향을 주지 않으므로 장점이 많음


<br>

## 테스트를 위한 트랜잭션 어노테이션
### @Transactional
* 테스트 클래스 또는 메소드에 @Transactional을 부여해주면 마치 타깃 클래스나 인터페이스에 적용된 것 처럼
  테스트 메소드에 트랜잭션 경계가 자동으로 설정
* 테스트 내에 진행하는 모든 트랜잭션 관련 작업을 하나로 묶음


### @Rollback
* 테스트용 트랜잭션은 테스트가 끝나면 자동으로 롤백
	* 테스트에 적용된 @Transactional은 기본적으로 트랜잭션을 강제 롤백시키도록 설정
* 해당 어노테이션은 트랜잭션을 커밋시켜서 테스트에서 진행한 작업을 DB에 반영시켜줌
* 기본값은 true
* 롤백은 원치 않는다면 @Rollback(false)

### @TransactionConfiguration
* 롤백에 대한 공통 속성을 지정( 클래스 레벨, @Rollbackd은 메소드레벨 )
* 디폴트 롤백 속성은 false로 해두고, 테스트 메소드 중에서 일부만 롤백을 적용하고 싶으면
  메소드에 @Rollback을 부여해주면 됨

### @NotTransactional
* 클래스 레벨의 @Tansactional 설정을 무시하고 트랜잭션을 시작하지 않은 채로 테스트 진행
* 스프링 3.0에서 제거 대상이므로 사용하기가 조금 꺼림칙
* 스프링 개발자들은 트랜잭션 테스트와 비트랜잭션 테스틀르 아예 클래스 구분해서 만들도록 권장
* @Tansactional의 NEVER 전파 속성 지정 시, @NotTransactional와 마찬가지로 트랜잭션 지원하지 않음
	* @Tansactional(propagation=Propagation.NEVER)


### 효과적인 DB 테스트
* 단위 테스트와 통합 테스트는 아예 클래스 구분하여 따로 만드는게 좋음
* DB가 사용되는 통합테스트는 가능한 한 롤백 테스트로 만드는게 좋음
* 테스트는 어떤 경우도 서로 의존하면 안됨
* 코드가 바뀌지 않는 한 어떤 순서로 진행되더라도 테스트는 일정한 결과를 내야 함

**Comment by aimhigh53** [comment]
6.6.1 트랜잭션 전파
* PROPAGATION_REQUIRED
    * 가장많이 사용되는 트랜잭션 전파 속성
    * 진행 중인 트랜잭션이 없으면 새로 시작, 이미 시작된 트랜잭션이 있으면 이에 참여
* PROPAGATION_REQUIRES_NEW
    * 항상 새로운 트랜잭션을 시작한다.
    * 독립적인 트랜잭션이 보장돼야 하는 코드에 적용
* PROPAGATION_NOT_SUPPORTED
    * 트랜잭션 없이 동작하도록 만든다.
    * 모든 메소드에 AOP 적용 후 특정 메소드에는 AOP를 적용하고 싶지 않을 경우 많이 사용한다.
2. 격리 수준 
* 서버환경에서 여러개 트랜잭션이 진행 될 때, 작업에 대한 격리 수준 
* DefaultTransactionDefinition에 설정된 격리수준은 ISOLATION_DEFAULT
*  ISOLATION_DEFAULT는 DataSource에 디폴트 격리수준을 따르는 설정
3. 제한시간
* 트랜잭션을 수행하는 제한시간을 설정
* DefaultTransactionDefinition의 기본 설정은 제한시간이 없다.
* 트랜잭션을 직접 시작할 수 있는 PROPAGATION_REQUIRED, PROPAGATION_REQIRES_NEW를 써야 의미가 있음  
 
4. 읽기전용
* 트랜잭션 내에서 데이터를 조작하는 시도를 막아준다. 
* 데이터 엑세스 기술에 따라 성능이 향상될 수 있다.
 
TransactionInterceptor
* PlatformTransactionManager와 Properties 타입의 두가지 프로퍼티를 갖음
* Properties 타입인 프로퍼티 이름은 transactionAttributes이며,  TransactionDefinition의 네가지 항목 + rollbackOn() 를 갖고 있는 TrasactionAttribute 인터페이스로 정의
* rollbackOn()을 활용하면 특정 체크 예외의 경우 트랜잭션을 롤백시킬 수 있음, 특정 런타임 예외에 대해서 트랜잭션 커밋시킬 수도 있음
* Properties 타입의 transactionAttributes 프로퍼티는 메소드 패턴과 트랜잭션 속성을 키와 값으로 갖는 컬렉션
    1. PROPAGATION_NAME: 트랜잭션 전파 방식, PROPAGATION_으로 시작한다. (필수)
    2. ISOLATION_NAME: 격리수준, ISOLATION_으로 시작한다. (생략가능, 디폴트: 격리수준)
    3. readOnly: 읽기전용 항목 (생략가능, 디폴트:읽기전용)
    4. timeout_NNNN: 제한시간, timeout_으로 시작하고 초 단위 시간을 뒤에 붙인다. (생략가능)
    5. -Exception1: 체크 예외중 롤백 대상으로 추가할 것을 넣는다 (한개 이상 가능)
    6. +Exception1: 런타임 예외지만 롤백시키지 않을 예외를 넣는다 (한개 이상 가능)



6.7 어노테이션 트랙잭션 속성과 포인트컷
- 세밀하게 튜닝된 트랜잭션 속성을 적용해야 하는 경우도 있다.
- 포인트컷 자체가 지저분해지고 설정파일도 복잡해짐
   => 직접 타깃에 트랜잭션 어노테이션을 지정하자
 
6.7.1 트랜잭션 어노테이션
- @Transactional 

- 사용되는 포인트컷은 TransactionAttributeSourcePoincut 이고 표현식과 같은 선정기준은 갖고있지 않다.

- 포인트컷과 트랜잭션 속성을 어노테이션 하나로 지정가능
- 유연한 속성 제어는 가능하지만..
   => 코드는 지저분, 동일 속성정보를 가진 어노테이션을 반복적으로 메서드마다 부여해야함 
- 4단계의 Fallback 정책을 지원, 메서드의 속성을 확인할때
1. 타깃 메소드
2. 타깃 클래스
3. 선언 클래스
4. 선언 타입
  순서에 따라서 적용됐는지 차례로 확인후 가장먼저 발견되는 속성정보를 사용

- @Transactional은 먼저 타입레벨에 정의하고 공통속성을 따르지 않는 메서드만 메서드레벨에 부여
- 타깃 클래스보다는 인터페이스에 @Transactional 설정을 두는게 바람직하다
- 인터페이스를 이용하는 프록시 방식의 AOP가 아닌 트랜잭션 방식을 적용하면 무시되므로 타깃클래스에 적용
보통 타깃 메서드에 어노테이션을 사용하고 있는데...
6.7.2 트랜잭션 어노테이션 적용
- 클래스에 적용할경우 디폴트로 모든 메소드에 적용

6.8 트랜잭션 지원 테스트
6.8.1 선언적 트랜잭션과 트랜잭션 전파속성
- REQUIRED로 전파속성 지정하면 앞에 트랜잭션이 있으면 참여, 없으면 새로운 트랜잭션 시작
- DB 트랜잭션은 단위 업무와 일치해야 한다.
- AOP를 이용해 코드 외부에서 속성 지정하는 방법을 선언적 트랜잭션
     트랜잭션 API를 사용해 직접 코드안에서 사용하는 방법을 프로그램 트랜잭션
- 전파속성을 단순조회라도 ReadOnly로 명시하자(성능향상)
 
6.8.2 트랜잭션 동기화와 테스트
- 트랜잭션 추상화 핵심은 트랜잭션 매니저와 트랜잭션 동기화이다.
- PlatformTransactionManager 인터페이스를 구현한 트랜잭션 매니저를 통해 일관된 트랜잭션 제어
- 동기화를 통해 트랜잭션 정보를 저장소에 보관해두었다가 DAO에서 공유 할수 있었다.
 
6.8.3 테스트를 위한 트랜잭션 어노테이션
- 통으로 테스트 클래스에 트랜잭션 관련 설정 하고싶을때 => @TransactionConfiguration
