### ISSUE TITLE
Chapter 7. 스프링 핵심 기술의 응용(7주차)

### ISSUE THREAD

**Issue by aimhigh53** [FireInStove/toby-spring#13]
## 👑 스터디장
- 인석(@aimhigh53)
## 📖 스터디 범위
- ~7.2장 끝까지
## 🕧 스터디 일정(온라인)
- 23/8/31 (목) 09시 ~

**Comment by aimhigh53** [comment]
## ✏️ 13주차 

## 7.1 SQL과 DAO의 분리

### 왜 필요한데?
- 데이터 액세스 로직은 바뀌지 않더라도 DB의 테이블, 필드 이름과 SQL문장이 바뀔 수 있음..
이러한 이유로 데이터 엑세스를 하는 코드를 책임과 역할이 다른 부분끼리 분리하고, 확장이 용이하도록 인터페이스로 연결하고, DI로 런타임에 연결하도록 했다. 그리고 DB 테이블과 필드 정보를 담고 있는 SQL 문장까지 분리하는게 목적인 코드를 소개함

### XML 설정을 이용한 분리
- XML과 SQL 분리, 빈의 SQL 문장 주입, DAO에 주입하여 사용
- SQL 맵 프로퍼티방식
   -> 프로퍼티에 MAP<,>추가, Set() 등을 하여 주입해서 사용
- SQL 제공 서비스
   -> FOR SQL SERVICE 분리
   -> SQL과 DI 설정정보가 섞여 있으면 보기에도 지저분하고 관리하기도 좋지않음, 그래서 SQL 분리
   ->  SQL을 제공하는 기능을 담당하는 별도의 서비스로 독립시킬 필요가 있다. 동적으로 갱신도 가능하고 확장성이 뛰어난 서비스를 만드는 것이 목표
   ->K:V형식에서 K를 이용해 가져오는방식

## 7.2 인터페이스의 분리와 자기참조 빈

### XML파일 매핑

-JAXB는 xml에 담긴 정보를 파일에서 읽어오는 방법 중 하나. xml 정보를 오브젝트처럼 다룰 수 있어 편리함.
- 언마샬링(unmarchalling) : XML to 자바 오브젝트
- 마샬링 : 자바 오브젝트 to XML
- sql맵 xml과 sql 맵을 위한 스키마를 jaxb 컴파일러로 컴파일하면, 바인딩용 클래스가 생성된다.
  -->content-type: application/xml때문에 썼던 경험이 있다. 개 거지같았음

- DAO가 sql 요청할 때마다 매번 xml파일을 다시 읽는건 비효율적. 한번 읽은건 어딘가에 저장해두고 DAO에서 요청이 올 때 사용해야한다.

- 처음 SQL을 읽어들이는걸 우선은 생성자에서 하고 동작, 변환된 SQL오브젝트는 맵에 저장해놨다가 DAO요청이 오면 전달하는 방식으로.

### 빈 초기화 방식
- SQL 맵 XML파일
- XML SQL 서비스 -> 생성자 초기화 방법 //XML의 변화에 대응하기 위해 DI 설정가능 할 수 있도록
- @PostConstruct
 
예시코드

`import javax.annotation.PostConstruct;

public class SampleService {

    private String message;

    @PostConstruct
    public void init() {
        message = "Initialized after construction!";
        System.out.println("@PostConstruct method called");
    }

    public void displayMessage() {
        System.out.println(message);
    }

    public static void main(String[] args) {
        // Normally, the container would handle lifecycle events and the calling of the @PostConstruct method.
        // Here we manually instantiate the class to mimic this for the sake of the example.
        SampleService service = new SampleService();
        service.init();  // manually calling the method marked with @PostConstruct
        service.displayMessage();
    }
}
`
-  어느시점에 초기화를 해야하는가
 -> 스프링이 제어권을 가지고 있으므로 스프링에게 맡겨야함

### 인터페이스 분리

-자기참조 빈으로 시작하기
--> 다중 인터페이스 구현과 간접 참조
--> XmlSqlService 클래스 하나가 SqlReader, SqlRegistry, SqlService 세 개의 인터페이스를 구현하도록 만든다.

### 디폴트 의존관계
- 확장 가능한 기반 클래스
 ->SqlRegistry와 SqlReader를 이용하는 가장 간단한 SqlService 구현 클래스를 만들어본다.

- 디폴트 의존관계를 갖는 빈 만들기
 -> BaseSqlService는 sqlReader와 sqlRegistry 프로퍼티의 DI를 통해 의존관계를 자유롭게 변경해가면서 기능을 확장할 수 있다.
3개의 빈을 등록해줘야 한다는 점이 귀찮게 느껴진다.
디폴트 의존관계 : 외부에서 DI 받지 않는 경우 기본적으로 자동 적용되는 의존관계
sqlmapFile 역시 디폴트값을 저장해두고 교체할 수 있도록 setter를 추가해준다.
DefaultSqlService는 BaseSqlService를 상속받았기 때문에 빈 등록 시점에 필요한 프로퍼티로 교체해 줄 수 있다.(출:https://dotheright.tistory.com/351)

**Comment by yougahee** [comment]
## ✏️ 13주차 (7.1 ~ 7.2)


## DAO와 SQL의 분리
1) 방법1
- 코드의 수정 없이 XML 설정으로 SQL을 뺀 후, 사용하기
- 외부에서 해당 SQL문을 DI하여 사용해야 하는 단점이 있음

2) 방법2
- SQL 맵 프로퍼티 방식
- XML 설정으로 key와 value를 설정해 둔 후, Map<key, value> 로 저장해두고, 필요할 때 Key 조회를 통해 사용하기
- 단, 오타나 실수를 한눈에 보기 힘들다.

#### 위 2가지 방법의 문제점
- SQL 문장을 XML 설정 부분에 넣어놓는 것은 좋지 않다.

3) 방법3 : SQL 서비스 인터페이스
- SQL문을 읽어오는 함수가 있는 인터페이스 생성
- 인터페이스 구현 클래스 > 내부 SQL Map에서 쿼리문을 가져올 수 있도록 구현
	- 해당 클래스를 빈으로 등록하고, 그 안에 쿼리문 Map으로 작성
- 과연 이 방법도 좋을까?


4) 방법 4 : SQL용 전용 포맷 파일
- SQL 전용 XML 파일을 만들어, JAXB로 컴파일 하면 .java 파일이 생성된다.
- @XmlAccessorType 등을 사용하여 개발하면 된다.

### JAXB란?
- XML 문서 정보를 거의 동일한 구조의 오브젝트로 직접 매핑
- 언마샬링
	- XML 문서를 읽어서 자바의 오브젝트로 변환하는 것
- 마샬링
	- 바인딩 오브젝트를 XML 문서로 변환하는 것

### 위의 SQL 전용 XML 변환하기
- 빈이 생성될 때, 초기 작업을 한번만 하는 것이 좋다.
- @PostConstruct 로 !!!
	- 빈 오브젝트를 생성하고, DI 작업을 마친 후 해당 애노테이션이 붙은 메소드를 자동으로 실행해 줌


### XML 말고, 다른 포맷의 파일에서 읽어오게 하려면 어떻게 해야할까?
- 기존에 사용하고 있던 서비스의 책임을 분리하여 사용
- 등록, 조회 하는 함수 따로
- 책 587p 에 나와있는 리스트 7-32 전략패턴!

### 디폴트 의존관계
- 외부에서 DI 받지 않는 경우 기본적으로 자동 적용되는 의존관계
- 특정하게 사용하고 주입받지 않고 디폴트로 사용할 만한 것을 구현
- 단점
	- 설정을 통해 다른 구현 오브젝트를 사용하게 해도 생성자에서 일단 다 만들어버림

### 요건 상식이다!
- 인터페이스는 타입을 상속하는 것이다. (다형성)

**Comment by kyueun** [comment]
# 7. 스프링 핵심 기술의 응용
 ## SQL과 DAO의 분리
 DAO : 데이터를 가져오고 조작하는 작업의 인터페이스
 - 데이터 액세스 로직이 그대로라도, DB의 테이블, 필드명, SQL 문장 바뀔 수 있음
 - 이런 경우, DAO로 데이터 가져오면 DAO 코드가 수정되어야 함
 - SQL, DAO 따로 관리

 1. XML 설정을 이용한 분리
    - SQL을 XML 설정파일로 -> SQL을 코드에서 분리
    - 새로운 SQL 필요할 때마다 프로퍼티 추가, DI를 위한 변수, 수정자 메소드 만들어줘야 함
2. SQL 맵 프로퍼티
    - 키 값을 이용해 SQL 가져옴
    - 실행 전에는 오류 확인하기 힘듦
3. SQL 서비스 인터페이스
    - XML에 SQL 넣어놓으면 변경 등 관리 힘듦
    - 인터페이스 통해 SQL 가져옴

## 인터페이스의 분리와 자기참조 빈
JAXB
- XML 문서정보를 거의 동일한 구조의 오브젝트로 매핑
- 언마샬링 : XML -> 자바 오브젝트
- 마샬링 : 바인딩 오브젝트 -> XML

XML 문서 정보를 언제 가져올 것인지?
- 생성자에서 예외 발생할 수 있는 초기화 작업 다루는 것은 좋지 않음
- 초기 상태를 가진 오브젝트 생성 후, 별도 초기화 메소드 사용
    - `@PostConstruct` : 빈의 오브젝트 생성, DI 작업 마친 후 자동 실행되는 메소드

인터페이스 분리
- 인터페이스에서 SQL 가져오고 저장하는 것까지 관리
- SQL 가져오는 기술 변화 OR 저장하는 방식 변경의 경우 모두 코드 수정 필요 ->  단일 책임 원칙 위반
- 조회 / 등록 & 저장 분리

디폴트 의존관계
- 외부에서 DI 받지 않는 경우 기본적으로 자동 적용되는 의존 관계
- 코드를 통해 의존관계 직접 주입
- DI 필요한 상황이 아닌 경우 편리
- 생성자에서 일단 디폴트 의존 오브젝트 다 생성 -> DI 필요한 경우 쓰이지 않는 오브젝트가 만들어지게 됨

**Comment by tmfrl1552** [comment]
# 7. 스프링 핵심 기술의 응용

## SQL과 DAO의 분리
### XML 설정을 이용한 분리

XML 설정파일로 빼내는 것

* SQL은 문자열로 되어 있으니 설정 파일에 프로퍼티 값으로 정의해서 DAO에 주입
* 설정 파일에 있는 SQL을 코드와는 독립적으로 수정
* 단점
	* 매번 새로운 SQL 필요할 때마다 프로퍼티를 추가하고 DI를 위한 변수와 수정자 메소드 추가 필요
	* 애플리케이션을 다시 시작하기 전에는 변경이 매우 어려움ㄴ

<br>

### SQL 맵 프로퍼티 방식

SQL을 하나의 컬렉션으로 담아두는 방법
> 키 값을 이용해 SQL 문장 조회

* XML 설정 시, 스프링이 제공하는 <map> 태그 사용
	* 스프링은 다양한 컬렉션 타입의 프로퍼티 값을 정의하는 태그 제공
* 장점
	* SQL을 일일이 프로퍼티로 등록하는 방법에 비해 작업량도 적고 코드도 간단
* 단점
	* 메소드에서 SQL을 가져올 때 문자열로 된 키 값을 사용하므로 오타와 같은 실수가 있어도
	  해당 메소드가 실행되기 전에는 오류 확인이 힘듬

<br>

### SQL 제공 서비스

SQL을 따로 분리해둬야 독립적으로 SQL 문의 리뷰나 SQL 튜닝 작업 수행하기도 편리
➡️ SQL 서비스의 독립적인 구현을 위한 'SQL 서비스 인터페이스' 생성

#### SQL 서비스 인터페이스
어떤 기술적인 조건이나 제약사항도 담겨 있지 않고,
어떤 방법을 사용하든 상관없이 DAO가 요구히는 SQL을 돌려주기만 하면 됨.

<br>

## 인터페이스의 분리와 자기참조 빈
### XML 파일 매핑

#### JAXB
XML 문서의 구조를 정의한 스키마를 이용해서 매핑할 오브젝트의 클래스까지 자동으로 만들어주는 컴파일러도 제공

* 스키마 컴파일러를 통해 자동생성된 오브젝트에는 매핑정보가 애노테이션으로 담겨있음
* JAXB API는 애노테이션에 담긴 정보를 이용해서 XML과 매핑된 오브젝트 트리 사이의 자동변환 작업 수행

#### 언마샬링
* 언마샬링 : XML 문서 -> 자바 오브젝트 변환
* 마샬링 : 바인딩 오브젝트 -> XML 문서로 변환

<br>

### 빈의 초기화 작업

* 생성자에서 예외가 발생할 수도 있는 복잡한 초기화 작업을 다루는 것은 좋지 않음
	* 오브젝트 생성 중, 생성자에서 발생하는 예외는 다루기가 힘듬
	* 상속하기도 불편, 보안 문제 생김
	* 💡 바람직한 방법
		* 1️⃣ 초기 상태를 가진 오브젝트 생성
		* 2️⃣ 초기화 메소드 사용하여 초기화

* 읽어들일 파일의 위치와 이름이 코드에 고정
	* 코드의 로직과 여타 이유로 바뀔 가능성이 있는 내용은 외부에서 DI로 설정해주도록 수정

* 초기화 메소드 언제 실행 ?
	* 빈 오브젝트를 생성하고 DI 작업을 수행해서 프로퍼티를 모두 주입해준 뒤에
	  미리 지정한 초기화 메소드를 호출
	* 스프링이 제공하는 빈 후처리기 중 애노테이션을 이용한 빈설정을 지원해주는 빈 후처리기 이용
		* context 네임스페이스 사용하여 설정파일에 추가 (<context:annotation-config />)
			* 코드의 애노테이션을 이용해서 부가적인 빈 설정 또는 초기화 작업을 해주는 후처리기 등록

* @PostConstruct
	* context 콘피그 설정에 의해 사용할수 있는 애노테이션
	* java.lang.annotation 패키지에 포함된 공통 애노태이션의 한가지
	* JavaEE5, JDK6에 포함된 표준 어노테이션
	* 빈 오브젝트의 초기화 메소드 지정 시 사용
	* 빈 오브젝트 생성 후 DI 작업을 마친 뒤에 @PostConstruct가 붙은 메소드를 자동 실행
	* 생성자와는 달리 프로퍼티까지 모두 준비된 후에 실행된다는 면에서 매우 유용

<br>

### 변화를 위한 준비: 인터페이스 분리
#### 책임에 따른 인터페이스 정의

* 1️⃣ SQL 정보를 외부의 리소스로부터 읽어오는 것
* 2️⃣ 읽어온 SQL을 보관해두고 있다가 필요할 떄 제공

#### SqlRegistry 인터페이스
SQL을 제공받아 등록해뒀다가 키로 검색해서 돌려주는 기능 담당

#### SqlReader 인터페이스
SqlRegistry 오브젝트를 메소드 파라미터로 DI 받아서 읽어들일 SQL을 등록하는데 사용

<br>

### 자기참조 빈으로 시작하기
SqlService 서비스의 클래스와 의존관계
<img width="475" alt="Toby_SqlService" src="https://github.com/FireInStove/toby-spring/assets/52412936/b195fed0-ed40-49a1-881b-3b274c47ccf8">

<br>

### 디폴트 의존관계
외부에서 DI 받지 않는 경우 기본적으로 자동 적용되는 의존관계

* DI란 클라이언트 외부에서 의존 오브젝트를 주입해주는 것이지만,
  자신이 사용할 디폴트 오브젝트를 스스로 DI 하는 방법도 있음
* 단점 한가지
	* 설정을 통해 다른 구현 오브젝트를 사용하게 해도 디폴트 서비스 생성자에서 일단 디폴트 의존 오브젝트를 다 생성
		* @PostConstruct 초기화 메소드를 이용해 프로퍼티가 설정됐는지 확인하고,
		  없는 경우에만 디폴트 오브젝트를 만드는 방법 사용

**Comment by flyingtw** [comment]
스터디

# 7.1 SQL과 DAO의 분리
- 데이터를 가져오고 조작하는 작업의 인터페이스 역할을 하는게 DAO이다.
- 하지만 DAO에서도 DB 테이블, 필드이름, SQL 문장이 바뀔 수 있다.
- SQL을 적절히 분리해 DAO 코드와 다른 파일이나 위치에 두고 관리할 수 있다면 좋다.
## 7.1.1 XML 설정을 이용한 분리
- 가장 기초 방법은 SQL을 스프링의 XML 설정파일로 빼는것이다.
- 스프링은 설정을 이용해 빈에 갑을 주입해줄 수 있다.
### 개별 SQL 프로퍼티 방식
- add()메서드 내부에서 외부(UserDaoJdbc)에서 DI받은 SQL 문장을 담은 sqlAdd를 사용하게 한다.
- 하지만 매번 새로운 SQL이 필요할때마다 프로퍼티를 추가하고 DI를 위한 변수와 수정자 메소드도 만들어줘야하는 불편함이 있다.
### SQL 맵 프로퍼티 방식
- SQL을 하나의 컬랙션으로 담아둬보자
- Map 타입으로 프로퍼티를 추가해서 사용
## 7.1.2 SQL 제공 서비스
- 위와같이 분리하면 다 좋긴한데 프로퍼티에 SQL과 DI 설정정보가 섞여 있으면 보기에도 지저분하고 관리하기에도 좋지 않다.
- 스프링의 설정파일로 부터 생성된 오브젝트와 정보를 애플리케이션을 다시 시작하기 전에는 변경이 매우 어렵다는점도 문제이다.
- SQL 제공 기능을 본격적으로 분리해서 다양한 SQL 정보 소스를 사용할 수 있게 만들어보자
### SQL 서비스 인터페이스
- 클라이언트인 DAO를 SQL서비스의 구현ㅇ네서 독립적으로 만들도록 인터페이스를 사용하고, DI로 구현 클래스의 오브젝트를 주입해주어야 한다.
- key를 넣으면 SQL를 return해주는 인터페이스 서비스
- 이제 UserDao를 포함한 모든 DAO는 SQL을 어디에 저장해두고 가져오는지에 대해서는 전혀 신경쓰지 않아도 된다. 구체적인 구현 방법과 기술에 상관없이 sqlService 인터페이스 타입의 빈을 DI받아서 필요한 SQL을 가져다 쓰기만 하면 된다.

# 7.2 인터페이스의 분리와 자기참조 빈
## 7.2.1 XML 파일 매핑
- XML 설정파일에서 <bean> 태그안에 SQL 정보를 넣어놓고 활용하는건 좋은 방법은 아니다.
- SQL을 저장해놓는 독립적인 파일을 사용하는것이 좋다.
- JAXB….흠..
## 7.2.4 변화를 위한 준비 : 인터페이스 분리
- 책임에 따른 인터페이스를 분리할 필요가 있다.
- 첫째는 SQL 정보를 외부의 리소스로부터 읽어오는 것이다. SQL을 읽고 가져오는것 자체를 하나의 책임으로 보자
- 둘째는 SQL 을 보관해두고 있다가 필요할때 제공해주는것이다. 검색하는 방법과 성능에 대해서도 여러가지 고려할 사항이 있다.
- 변경 가능한 기능은 전략패턴으로 별도의 오브젝트로 분리해줘야 한다.
- Reader, Registry 두가지로 분리한다.
- SqlReader는 SqlRegistry 오브젝트를 메소드 파라미터로 DI받아서 읽어들인 SQL을 등록하는데 사용하도록 만들어야 한다.
## 7.2.5 자기참조 빈으로 시작하기
- 인터페이스를 구현함으로써 같은 타입으로 존재하지만 다른 구현을 가진 오브젝틀르 만들 수 있다는 다형성을 활용할 수 있다.
- 즉, 서비스 클래스에서 사용할 연관된 모든 인터페이스를 다 implement 받은다음 각각의 인터페스를 구현하되, 각자의 인터페이스간의 관계사이의 사용되는 오브젝트들은 클래스 내부에 존재는 나 자신의 오브젝트라도 외부에서 주입받은것처럼 생각하여 각각의 메소드들을 구현한다. 즉, 자기 스스로를 참조하는 빈이다.
## 7.2.6 디폴트 의존관계
- DI란 클라이언트 외부에서 의존 오브젝트를 주입해주는 것이지만 자신이 사용할 디폴트 의존 오브젝트를 스스로 DI 하는 방법도 있다.
- DefaultSqlService가 바로 SqlService를 구현하지 않고 BaseSqlService를 상속했으며 Base의 sqlReader와 sqlRegister 프로퍼티를 그대로 갖고잇고 이를 이용해서 원한다면 언제든지 모든 프로퍼티를 변경할 수 있다.
- 하지만 default를 무조건 다 생성한다는 단점이 있다.
