### ISSUE TITLE
Chapter 7. 스프링 핵심 기술의 응용

### ISSUE THREAD

**Issue by kyueun** [FireInStove/toby-spring#14]
## 👑 스터디장
- 규은(@kyueun )
## 📖 스터디 범위
- ~7.5장
## 🕧 스터디 일정
- 23/9/7 (목) 09시

**Comment by flyingtw** [comment]
# 7.3 서비스 추상화 적용
- XML 파일을 다른 방식으로 가져올 방법은 없을까?
## 7.3.1 OXM 서비스 추상화
- XML과 자바오브젝트 매핑 기술은 다양한게 있다.
- XML과 자바 오브젝트를 매핑해서 상호 변환해주는 기술을 간단히 OXM이라고 한다.
- 자바 오브젝트를 XML로 변환하는 Mashller, XML을 자바 오브젝트로 변환하는 Unmarshaller
- 서비스 추상화는 로우레벨의 기술을 필요에 따라 변경해서 사용하더라도 일관된 애플리케이션 코드를 유지할 수 있게 해준다.
## 7.3.2 OXM 서비스 추상화 적용
- SqlReader 구현 오브젝트에 대한 의존관계를 고정시켜버리는 방법을 상용해보자
- OxmSqlService 클래스 안에 OxmSqlReader를 포함시켜 한개의 빈만 사용되게 만든다.
- Reader 를 final로 선언하여 변경 불가능하다. 강하게 결합되어 하나의 빈으로 등록되고 한번에 설정할 수 있다.
## 7.3.3 리소스 추상화
- 리소스에 접근하는 방식을 통일해보자.
- 리소스 : 자바에 존재하는 일관성 없는 리소스 접근 api를 추상화 인터페이스로 만든것
- 애플리케이션 컨텍스트가 사용할 절정정보 파일을 지정하는것부터 시작해서 스프링의 거의 모든 api는 외부 리소스 정보가 필요할때 이 추상화 클래스를 이용한다.
- Resource는 빈이 아니라 값으로 취급된다. 즉, 추상화 할 수 가 없다.
- 빈으로 등록했다면 각기 다른 Resource 인터페이스의 구현 클래스를 지정해주면 된다. 
- 그래서... URL클래스와 유사하게 접두어를 이용해 Resource 오브젝트를 선언하는 방법이 있다.
- 그 후 문자열로 정의된 리소스를 실제 Resource 타입 오브젝트로 변환해주는 ResourceLoader를 제공한다.
- String location -> Resource로 변환
- classpath!!
- pom.xml 같은 파일도 리소스 로더를 이용해  Resource 형태로 읽어온다.
- 리소스의 종류와 상관없이 stream으로 가져올 수 있다.
-  Resource 구현체는 실제 리소스가 아니다. 디폴트 값이 설정되어있을 수 있다.
- http 같은 웹 리소스도 가져올 수 있다.
# 7.4 인터페이스 상속을 통한 안전한 기능확장
- 원래 모든 구현 클래스들은 초기에 리소스로부터 SQL정보를 읽어오면 이를 메모리에 두고 그대로 사용한다.
## 7.4.1 DI와 기능의 확장
- DI를 적용할 때는 가능한 한 인터페이스를 사용하게 해야 한다.
- 두개의 오브젝트가 인터페이스를 통해 느슨하게 연결돼야 한다.
- 인터페이스를 사용하는 첫번째 이유는 다형성을 얻기 위해서이다.
- 자바의 클래스는 하나 이상의 인터페스르를 구현할 수 있다.
- 인터페이스라는 창을 통해 여러 클래스들이 관심사가 있는 메서드만 구현하게 하면 좋다!
- 목적과 관심이 각기 다른 클라이언트가 있다면 인터페이스를 통해 이를 적절하게 분리해줄 필요가 있고, 이를 객체지향 설계 원칙에서는 인터페이스 분리 원칙이라고 부른다!
## 7.4.2 인터페이스 상속
- 기존 인터페이스를 상속을 통해 확장하는 방법도 존재한다. 인터페이스의 인터페이스
- Base를 상속받은  update 인터페이스가 있다고 하면 필요한 클라이언트는 필요한 인터페이스를 선택해서 사용하면 된다. 각자의 관심사!
# 7.5 DI를 이용해 다양한 구현 방법 적용하기
- 여러 SQL을 동시에 접근하는 기능이 있다며 동시성 문제가 발생할 수 있다.
## 7.5.1 ConcurrentHashMap을 이용한 수정 가능 SQL 레지스트리
- 동시성을 확보하기 위해 락을 걸어놓는걸 추천한다
## 7.5.2 내장형 데이터베이스를 이용한 SQL 레지스트리 만들기
-  H2같은 내장형  DB는 안정적이다.
- 자체 DB이기 때문에 connection 과같은 별도의 로직이 필요없다.
- 테이블과 초기 데이터를 세팅하는 스크립트가 필요하다. (빌더를 사용)
## 7.5.3 트랜잭션 적용
- 여러부분에서 동시에 수정을 가하는 작업은 무조건 트랜잭션 처리가 필요하다.
- SQL을 수정하는 부분도 역시 트랜잭션 안에서 처리가 되어야 한다.
- 내장형 DB는 트랜잭션 적용이 쉽다.

**Comment by yougahee** [comment]
## ✏️ 14주차 (7.3 ~ 7.5)

## OXM(Object-XML Mapping)
- XML과 자바 오브젝트를 매핑해서 상호 변환해주는 기술
- 4가지 종류
	- Castor XML : 설정파일이 필요 없는 인트로스펙션 모드를 지원하기도 하는 매우 간결하고 가벼운 바인딩 프레임워크
	- JiBX : 뛰어난 퍼포먼스를 자랑하는 XML 바인딩 기술
	- XmlBeans : 아파치 XML 프로젝트 중 하나
	- Xstream : 관례를 이용해서 설정이 없는 바인딩을 지원하는 XML 바인딩 기술의 하나
- 추상화
	- 어떤 OXM 기술이든 언마샬을 한줄로 끝낼 수 있다.
	``` java
		var sqlmap = this.unmarshaller.unmarshal(xmlSource);
	```

## 리소스 추상화
- 사고의 전환 : 꼭 시스템의 특정 폴더의 XML 을 읽어오리라는 보장은 없다.
- 방향성 : XML 포맷 문서를 어느 곳에서든(ex. http, ftp 등) 가져올 수 있도록 하기 
- 방법 : Resource Interface 만들기
	- 리소스가 존재하는지, 읽을 수 있는지, 열려있는지 확인 하는 메소드
	- 리소스 출처 : file, URI, URL 
- 적용 방법
	- ResourceLoader 사용하기
	


## ResourceLoader

### 접두어
- file:
- classpath:
- 없음(서블릿 컨텍스트의 루트를 기준으로)
- http:
### 대표적인 예 
- Spring 의 Application Context


## DI와 인터페이스 프로그래밍
- DI를 적용할 때 가능한 한 인터페이스를 사용하게 해야한다.
- DI는 특별한 이유가 없는 한 항상 인터페이스를 사용한다고 기억하자.
- 동일한 오브젝트에 의존하지만 각자의 관심과 필요에 따라서 사용하고 이를 통해 유연한 확장이 가능해진다.
	- 그렇다고는 하는데, 실제로 유연하게 확장할 수 있도록 사용하는 케이스를 못봐서 그런지.... 한번 꼭 보고 싶다.. (이론적으로는 알겠는데, 이걸 어떻게 잘 녹여서 사용할지 잘 모르겠음 ㅜ)
		- 못 봐서,,? -> 사실 라이브러리들을 보면 되긴 하지만,, 뭔가 서비스적으로 그걸 녹여서 개발하려고 하면 어떻게 녹여야 할지 잘 모르겠음

### 인터페이스를 사용하는 이유
1) 다형성을 얻기 위해
	- 여러 개의 구현을 바꿔가면서 사용할 수 있도록
2) 클라이언트와 의존 오브젝트 사이의 관계를 명확하게 해줄 수 있다.
	- 각기 다른 관심과 목적을 가지고 어떤 오브젝트에 의존하고 있을 수 있다는 의미


## 동시성
### ConcurrentHashMap
- thread-safe한 HashMap
- 조회 시, 락을 걸지 않음(조회는 여러 스레드가 동시에 읽을 수 있음)
- 쓰기 작업 시, 락을 건다.
- 성능이 나쁜편은 아니지만, 저장되는 데이터의 양이 많아지고 잦은 조회와 변경이 일어나는 환경이라면 한계가 있다.


## 내장형 DB
### 종류
- Derby
- HSQL
- H2

### 내장형 DB를 이용하여 SqlRegistry 만들기
- EmbeddedDatabase 타입으로 DI 받기
	- 인터페이스 분리 원칙을 지키기 위해
- 트랜잭션 적용

**Comment by kyueun** [comment]
## 서비스 추상화 적용
### OXM
- XML <-> 자바 오브젝트 매핑 기술
    - JAXB
    - Cator XML
    - JiBX
    - XmlBeans
    - Xsteream
- 목적이 동일 하므로 제공하는 기능들도 유사 
- 스프링에서 OXM 추상화 서비스 인터페이스 제공
    - Marshaller : 자바 오브젝트 -> XML
    - Unmarshaller : XML -> 자바 오브젝트

### 리소스 추상화
특정 경로에 있는 파일이 아닌, 다양한 위치의 리소스에 대한 접근 인터페이스 필요

Resource
- 스프링이 정의한 리소스 접근 추상화 인터페이스
- 빈이 아니라 값으로 취급 
    - 외부에서 구현체 지정 불가능 
    - 문자열로 정의된 리소스를 Resource로 변환해주는 `ResourceLoader` 제공
        - `file:`, `classpath:`, `http:` 등 접두어 처리

<details>
<summary>sample</summary>

```java    
    public class OxmSqlService implements SqlService {

        private final OxmSqlReader sqlReader = new OxmSqlReader();
        private SqlRegistry sqlRegistry = new HashMapSqlRegistry();

        public void setUnmarshaller(Unmarshaller unmarshaller) {

            this.sqlReader.setUnmarshaller(unmarshaller);
        }

        private class OxmSqlReader implements SqlReader {

            private Unmarshaller unmarshaller;
            private Resource sqlmap = new ClassPathResource(DEFAULT_FILE, OtherClass.class);
    //        private String sqlmapFile = DEFAULT_FILE;
        
            private static final String DEFAULT_FILE = "sqlmap.xml";

            public void read(SqlRegistry sqlRegistry) {
                
                Source source = new StreamSource(sqlmap.getInputStream());
                Sqlmap sqlmap = (Sqlmap) this.unmarshaller.unmarshal(source);

                for (SqlType sql : sqlmap.getSql()) {

                    sqlRegistry.registerSql(sql.getKey(), sql.getValue());
                }
            }

            void setUnmarshaller(Unmarshaller unmarshaller) {

                this.unmarshaller = unmarshaller;
            }
        }
    }

    public interface SqlService {}

    public interface SqlReader {

        void read(SqlRegistry sqlRegistry);
    }

    public interface Unmarshaller {

        Object unmarshal(Source source);
    }

    public interface SqlRegistry {

        void registerSql(String key, String value);
    }

    public class HashMapSqlRegistry implements SqlRegistry {

        private Map<String, String> sqlMap = new HashMap<>();

        public void registerSql(String key, String value) {

            this.sqlMap.put(key, value);
        }
    }

    public class Sqlmap {

        List<SqlType> sql = new ArrayList<>();

        public List<SqlType> getSql() {

            return this.sql;
        }
    }

    public class SqlType {

        private String key;
        private String value;
        
        public String getKey() {
            
            return this.key;
        }
        
        public String getValue() {
            
            return this.value;
        }
    }
```
</details>

## 인터페이스 상속을 통한 안전한 기능 확장
DI 적용할 때는 가능한 인터페이스 사용
- 다형성 : 하나의 인터페이스를 통해 구현을 바꿔가며 사용
- 인터페이스 분리 원칙 : 클라이언트와 의존 오브젝트 간 관계를 명확하게

### 인터페이스 상속
인터페이스 여러 개 만드는 대신 상속을 통한 확장

<details>
<summary>sample</summary>

```java
public interface Registry {

    public void registerSql();
}

public interface ReadableRegistry extends Registry {

    public void read();
}

public interface UpdatableRegistry extends Registry {

    public void update();
}

public class MysqlRegistry implements ReadableRegistry, UpdatableRegistry {

    @Override
    public void read() {}

    @Override
    public void update() {}

    @Override
    public void registerSql() {}
}
```
</details>

 ## DI를 이용해 다양한 구현 방법 적용하기
 운영 중 서비스의 SQL 변경 시, 발생 가능 문제점
 - 동시성 문제
    - ConcurrentHashMap 통해 멀티스레드 환경에서 안전하게 조작 가능
 - 데이터 양이 많고, CRUD 잦은 경우 Map 으로는 한계
    - 내장형 DB에 저장 -> 데이터는 메모리에 저장 (성능), Map에 비해 안정적
    - EmbeddedDatabase 인터페이스 사용
- 여러 SQL 변경 시, 중간에 예외 발생하면 일부만 반영, 일부는 미반영
    - 트랜잭션 적용

**Comment by aimhigh53** [comment]
## ✏️ 14주차 

## 7.3 서비스 추상화 적용

### OXM 서비스 추상화
- XML과 자바 오브젝트를 매핑해서 상호 변환하는 기술을 OXM이라고함
- Unmarshaller도 Marshaller인 이유는 Jaxb2Marshaller는 두 인터페이스 모두 구현하고 있기 때문이다.
  -  구현클래스만 빈 등록, 코드 수정없이 구현 기술을 적용할 수 있음
  -  castor 구현..


### OXM 서비스 추상화 적용

 - OXM 기술에 의존적이라고 해서 꼭 OXM 코드를 직접 가지고 있을 필요는 없다.
        => 간접적으로 DI를 받아야한다
- JAXB를 포함해서 다섯 가지 기술 모두 유사한 기능과 API를 제공함
- 유사한 기능과 API를 제공하기 때문에, 이를 추상화 하는 서비스 추상화할 수 있음
- 스프링에서 트랜잭션, 메일 전송뿐 아니라 OXM에 대해 서비스 추상화 기능을 제공함


### 리소스 추상화
- Reader의 공통문제는 UserDao와 같은 클래스패스에 존재하는 파일로 제한됨
  -  스프링은 리소스 접근 API를 추상화해서 Resource라는 인터페이스를 정의
  -  Resource는 빈 x, 값으로 취급된다.
  -  구현클래스 문제는 스프링에는 접두어(file,classpath 등)를 이용해 선언하는 방법이 있다.
        => 문자열 안에 리소스 종류와 위치를 함께 표현하고 이를 실제 타입으로 변환해주는 ResourceLoader
  -  Resource 객체가 실제 리소스는 아님



## 7.4 인터페이스 상속을 통한 안전한 기능 확장

### DI와 기능의 확장
- 스프링과 같은 DI 프레임워크를 적용하고 빈 설정파일을 이용해 애플리케이션을 구성했다고 해서 DI를 바르게 활용하는게 아닐 수 있음 
- DI의 가치를 제대로 얻으려면 먼저 DI에 적합한 오브젝트 설계가 필요함 
- DI를 의식하는 설계
    - 다형성을 얻기 위해
    - 인터페이스 분리 원칙을 통해 클라이언트와 의존 오브젝트 사이의 관계를 명확하게 해줄 수 있기때문에


### 인터페이스 상속

- 목적과 관심이 각기 다른 클라이언트가 있다면 인터페이스를 통해 이를 적절하게 분리해줄 필요가 있고 이를 객체지향 설계 원칙에서는 인터페이스 분리 원칙이라고 함
￼


## 7.5 DI를 이용해 다양한 구현 방법 적용하기

### 동시성 문제

ConcurrentHashMap을 이용한 수정 가능 SQL 레지스트리
* 멀티스레드 환경에서 안전하게 HashMap을 조작하려면 Collections.synchronizedMap()등을 이용해 외부에서 동기화를 해야함. 
    * 하지만 이렇게 HashMap의 전 작업을 동기화하려면 고성능 서비스에서는 성능에 문제가 생긴다.
* 일반적으로 ConcurrentHashMap 사용이 권장된다. ConcurrentHashMap은 데이터 조작 시 전체 데이터에 대해 락을 걸지 않고 조회는 락을 아예 사용하지않는다.
    * 그래서 어느 정도 안전하면서 성능이 보장되는 동기화된 HashMap으로 이용하기에 적당하다.

내장형 DB를 사용해서 구현하기
* 저장되는 데이터 양이 많아지고 잦은 조회와 변경이 일어나는 환경이라면 db를 쓰자.
* 하지만 SQL 저장해두고 관리할 목적이라면 별도의 DB를 구성하면 배보다 배꼽이 더 큰 일이 될 수도 있다. 그래서 이런 경우에는 DB의 장점과 특징을 그대로 갖고 있으면서 애플리케이션 외부에 별도로 설치하고 셋업하는 번거로움이 없는 내장형 DB를 사용하는 것이 적당하다.
* 내장형 DB는 애플리케이션에 내장되어서 애플리케이션과 함께 시작되고 종료되는 DB를 말한다. 데이터는 메모리에 저장되기 때문에 IO로 인한 부하가 적어 성능이 뛰어나다.

**Comment by tmfrl1552** [comment]
# 7.3 서비스 추상화 적용
## OXM 서비스 추상화
(JAXB 외에도) 자주 사용되는 XML과 자바 오브젝트 매핑 기술

* Castore XML : 설정 파일이 필요 없는 인트로스펙션 모드를 지원하기도 하는 매우 간겨라고 가벼운 바인딩 프레임워크
* JiBX : 뛰어난 퍼포먼스를 자랑하는 XML 바인딩 기술
* XmlBeans : 아파치 XML 프로젝트의 하나. XML의 정보셋을 효과적으로 제공
* Xstream : 관례를 이용해서 설정이 업는 바인딩을 지원하는 XML 바인딩 기술의 하나


#### OXM 
* XML 과 자바오브젝트를 매핑해서 상호 변환해주는 기술
* Object XML Mapping
* 스프링은 OXM에 대해서도 서비스 추상화 기능 제공
	* 추상 인터페이스를 제공하기 때문에 테스트 작성 편리

<br>

## OXM 서비스 추상화 적용
### 멤버 클래스를 참조하는 통합 클래스

OxmService가 SqlReader 타입의 의존 오브젝트를 스태틱 멤버 클래스로 내장하고
자신만이 사용할수 있도록 생성

* 의존 오브젝트를 자신만이 사용하도록 '독점'하는 구조로 생성
	* 밖에서 볼 떄는 하나의 오브젝트로 보이지만, 
	  내부에서는 의존 관계를 가진 두 개의 오브젝트가 깔끔하게 결합돼서 사용
	* 유연성은 조금 손해를 보더라도 내부적으로 낮은 결합도를 유지한 채로 응집도가 높은 구현을 만들 때 유용
* 위의 구조로 생성하는 이유
	* OXM을 이용하는 서비스 구조로 '최적화'하기 위함
	* 하나의 클래스로 만들기 때문에 빈의 등록과 설정은 단순해지고 쉽게 사용


### 위임을 이용한 BaseSqlService의 재사용

loadSql()과 getSql() 이라는 SqlService의 핵심 메소드 구현 코드가 BaseSqlService와 동일

* 코드의 양도 많고 변경도 자주 일어난다면?
	* ➡️ '중복성' 은 심각한 문제가 될 수 있음
* 위임 구조를 이용해 코드의 중복 제거 가능
* 부가 기능 프록시처럼 많은 타깃에 적용할 것도 아니고,
  특화된 서비스를 위해 한 번만 사용할 것이므로 유연한 DI 방식은 포기
  	* OxmSqlService와 BaseSqlService를 한 클래스로 묶는 방법 생각해보자.

<br>

### 리소스 추상화

* 자바에는 다양한 위치에 존재하는 리소스에 대해 '단일화된 접근 인터페이스' 제공해주는 클래스 미존재
* 그나마 URL을 이용해 웹상의 리소스에 접근 가능한 'java.net.URL' 클래스 존재
	* 장점 : http, ftp, file과 같은 접두어를 지정하여 다양한 원격 리소스에 접근 가능
	* 단점 : 자바의 클래스패스 안에 존재하는 리소스나 서블릿 컨텍스트의 리소스 또는 
	        임의의 스트림으로 가져올 수 있는 리소스를 지정하는 방법이 없음,
	        리소스 파일의 존재 여부를 미리 확인할 수 있는 기능 미존재

#### 리소스
* 스프링은 자바에 존재하는 일관성 없는 리소스 접근 API를 추상황해서 
  Resource 추상화 인터페이스 정의
* 애플리케이션 컨텍스트가 사용할 설정정보 파일을 지정하는 것부터 시작해서
  스프링의 거의 모든 API는 외부의 리소스 정보가 필요할 때, Resource 추상화 이용
* Resource는 스프링에서 빈이 아니라 값으로 취급
	* OXM이나 트랜잭션처럼 서비스를 제공해주는 것이 아닌 단순한 정보를 가진 값으로 지정 

#### 리소스 로더
* 스프링은 접두어를 이용해 Resource 오브젝트를 선언하는 방법 존재
* 문자열 안에 리소스의 종류와 리소스의 위치를 함께 표현
* 문자열로 정의된 리소스를 실제 Resource 타입 오브젝트로 변환해주는 'ResourceLoader' 제공

```java
package org.springframework.core.io;

public interface ResourceLoader {
	Resource getResource(String location);
	...
}
```

* location에 담긴 스트링 정보를 바탕으로 그에 적절한 Resource 로 변환
* 접두어가 없는 경우
	* 리소스 로더의 구현 방식에 따라 리소스를 가져오는 방식 상이
* 접두어가 있는 경우
	* 리소스 로더의 종류에 상관 없이 접두어가 의미하는 위치와 방법 이용해 리소스 읽어옴
	* 접두어 예 : file:, classpath:, 없음(접두어가 없는 경우), http:
* ResourceLoader의 대표적인 예는 스프링의 애플리케이션 컨텍스트
	* ApplicationContext는 ResourceLoader 인터페이스 상속
	* 스프링 설정 정보가 담긴 XML 파일도 리소스 로더를 이용해 Resource 형태로 읽어옴
	* 그 밖에 애플리케이션 컨텍스트가 외부에서 읽어오는 모든 정보는 리소스 로더 이용
	* Resource 타입은 빈으로 등록하지 않고 <property> 태그의 value를 사용해 문자열로 값을 넣는데,
	  문자열로 된 리소스 정보를 Resource 오브젝트로 변환하여 프로퍼티에 주입할 때도,
	  애플리케이션 컨텍스트 자신이 리소스 로더로서 변환과 로딩 기능 담당
* Resource는 단지 리소스에 접근할 수 있는 '추상화된 핸들러'
	* 리소스 오브젝트가 만들어져 있다고 해도, 실제로 리소스 미존재할 수 있음

<br>

# 7.4 인터페이스 상속을 통한 안전한 기능 확장
## DI와 기능의 확장
### DI와 인터페이스 프로그래밍
DI 적용할 때는 가능한 한 인터페이스를 사용
(DI를 DI답게 만들려면 두 개의 오브젝트가 인터페이스를 통해 느슨하게 연결)

* 인터페이스를 사용하는 이유
	* 다형성
		* 하나의 인터페이스를 통해 여러 개의 구현을 바꿔가며 사용할수 있게 하는 것이
		  DI가 추구하는 첫 번째 목적
		* 템플릿 메소드 패턴이 대표적인 방법
	* 인터페이스 분리 원칙을 통해 클라이언트와 의존 오브젝트 사이의 관계를 명확히 해줌
		* 인터페이스는 하나의 오브젝트가 여러 개를 구현할 수 있으므로, 
		  하나의 오브젝트를 바라보는 창이 여러가지 일 수 있음.
		* 각기 다른 관심과 목적을 가지고 어떤 오브젝트에 의존하고 있을 수 있음
* 인터페이스 분리 원칙
	* 목적과 관심이 각기 다른 클라이언트가 있다면 인터페이스를 통해 적절하게 분리

<br>

## 인터페이스 상속
* 인터페이스 분리 원칙이 주는 장점
	* 모든 클라이언트가 자신의 관심에 따른 접근 방식을 불필요한 간섭 없이 유지
	* 기존 클라이언트에 영향을 주지 않은 채로 오브젝트의 기능을 확장하거나 수정 가능

<br>

# 7.5 DI를 이용해 다양한 구현 방법 적용하기
운영 중인 시스템에서 사용하는 정보를 실시간으로 변경하는 작업을 만들 때,
가장 먼저 고려해야할 사항은 바로 '동시성 문제'⭐️


## ConcurrentHashMap을 이용한 수정 가능 SQL 레지스트리
* Collection.synchronizedMap() 
	* 멀티스레드 환경에서 안전하게 HashMap 조작 가능하나, 고성능 서비스에서 성능 문제 생김
	* 전체 컬렉션을 대상을 lock/unlock
* ConcurrentHashMap
	* 데이터 조작 시 일부만 lock/unlock
	* 조회시에는 락을 아예 사용하지 않음

<br>

## 내장형 데이터베이스를 이용한 SQL 레지스트리 만들기 
* 내장형 DB
	* 애플리케이션에 내장돼서 애플리케이션과 함께 시작되고 종료되는 DB
	* 데이터는 메모리에 저장되므로 IO로 인해 발생하는 부하가 적어서 성능이 뛰어남
	* 동시에 Map과 같은 컬렉션이나 오브젝트를 이용해 메모리에 데이터를 저장해두는 방법에 비해
	  매우 효과적이고 안정적인 방법으로 등록/수정/검색이 가능
	* 최적화된 락킹, 격리수준, 트랜잭션을 적용 가능
	* 단순한 자바 오브젝트와 컬렌션, 배열 등을 사용할 때보다는 애플리케이션에 부담을 줄 수 있겠지만,
	  메모리 안에서 동작하도록 최적화된 내장형 DB라면 큰 문제 없음
* 스프링의 내장형 DB 지원 가능
	* 자바에서 많이 사용되는 내장형 데이터베이스
		* Derby, HSQL, H2
	* JDBC 드라이버를 제공하고 표준 DB와 호환되는 기능을 제공하므로, 
	  JDBC 프로그래밍 모델을 그대로 따라서 사용
* 스프링은 내장형 DB를 초기화하는 작업을 지원하는 편리한 내장형 DB 빌더 제공
	 1. 대표적인 세 가지 내장형 DB를 사용할 때 필요한 URL과 드라이버 등을 초기화 해주는 기능
	 2. 데이터 초기화를 위해 테이블 등을 생성하거나 초기 데이터를 삽입하는 SQL을 실행
	 3. 모든 준비가 끝나면 내장형 DB에 대한 DataSoure 오브젝트를 돌려줌
	 4. DataSoure 인터페이스를 상속해서 shutdown() 이라는 내장형 DB 용 메소드를 추가한
		 EmbededDatabase 인터페이스 제공


#### XML 설정을 통한 내장형 DB의 생성과 적용
* <jdbc:embeded-database> 태그에 의해 만들어지는 EmbededDatabase 타입 빈은
  스프링 컨테이너가 종료될 때, 자동으로 shutdown() 메소드가 호출되도록 설정
  	* 내장형 DB 종료 시 별도의 코드나 설정 불필요
