### ISSUE TITLE
Chapter 7. 스프링 핵심 기술의 응용 (9주차)

### ISSUE THREAD

**Issue by flyingtw** [FireInStove/toby-spring#15]
## 👑 스터디장
- 태완
## 📖 스터디 범위
- 7.6 ~ 7.7장
## 🕧 스터디 일정
- 23/9/14 (목) 09시

**Comment by flyingtw** [comment]
# 7.6 스프링 3.1의 DI
- 스프링은 DI 원칙을 충실히 따랐기 때문에 호환성을 유지하며 발전될 수 있었다.
## 애노테이션의 메타정보 활용
- 어노테이션은 애플리케이션을 핵심 로직을 담은 자바 코드와 이를 지원하는 IoC 방식의 프레임워크, 그리고 프레임워크가 참조하는 메타정보라는 세가지로 구성하는 방식에 잘 어울린다.
- 초창기엔 오브젝트간 관게 설정용 DI 메타정보 설정에 XML이 유용했다.
- XML보다 어노테이션 하나로 간단하게, 더 많은 정보를 제공할 수 있다.
- 어노테이션으로 간결한 코드 사용이 가능하지만 우선순위등의 룰을 미리 숙지하고 있어야 하는등 학습할거리가 많아져버렸다.

## 7.6.1 자바 코드를 이용한 빈 설정
- 첫번째. XML을 없애자
- @Cinfiguration 클래스가 XML 정보를 뜻한다.
- <bean> 프로포퍼티는 @Bean으로 대체
- @Autowired를 이용해서 XML에 정의된 빈을 컨테이너가 java 클래스에 주입하게 한다.
- @Autowired는 필드의 타입을 기준으로 빈을 찾고 @Resource는 필드 이름을 기준으로 한다.
- @Enable~ 로 시작하는 어노테이션은 XML에서 자주 사용되는 전용 태그들을 쉽게 사용하기 위한 방식이다.

## 7.6.2 빈 스캐닝과 자동와이어링
- @Autowired는 자동와이어링 기법을 이용해서 조건에 맞는 빈을 찾아 자동으로 수정자 메소드나 필드에 넣어준다.
- @Component는 클래스에 부여된다. 이는 빈 스캐너를 통해 자동으로 빈에 등록되는 기능이다.
- DAO 기능을 제공하는 클래스에는 @Repository 어노테이션을 이용하도록 권장한다.
- @Service 어노테이션도 스프링이 제공한 빈 자동등록용 어노테이션이다. - Transaction과 함께 사용되는 경우가 많다.


## 7.6.3 컨텍스트 분리와 @Import
- 테스트용 DI 설정용 클래스를 분리하여 테스트용 빈주입을 분리하자.
- Autowired Repository 등으로 로 자동 주입된 빈들이 있기에 set을 통한 DI를 따로 안해줘도 된다. 
- 자바 클래스로 선언된 설정정보를 가져올때는 @ImportResource 대신 @Import를 이용한다.
- 테스트용 Configuration, 운영용 Configuration 아래에 Sql Configuration을 둬서 SQL관련된건 무조건 사용되게 Import 하는것

## 7.6.4 프로파일
- 운영환경에서는 반드시 필요하지만 테스트 실행 중에는 배제돼야 하는 빈 설정을 별도의 설정 클래스로 만들어 따로 관리할 필요가 있다.
- @Profile을 이용해 특정 환경에서만 빈 설정 조합을 만들어낼 수 있다.

- DefaultListableBeanFactory라는 클래스로 빈을 등록하고 관리한다.

## 7.6.5 프로퍼티 소스
- db 연결정보같은 프로퍼티 정보
- @PropertySource 로 .properties 파일을 세팅해준다.
- @Value는 이름 그대로 값을 주입받을 때 사용한다.

## 7.6.6 빈 설정의 재사용과 @Enable*
- SQL 쿼리문 자체는 수정할 수 있게 하고 나머진 은닉하자

**Comment by kyueun** [comment]
## 스프링 3.1의 DI
자바 언어의 변화와 스프링
- 애노테이션의 메타정보 활용
    - 로직을 담은 자바 코드 / 이를 지원하는 DI 프레임워크 / 프레임워크가 참조하는 메타정보 -> 분리해서 구성하는 방식에 잘 어울림
- 정책과 관례를 이용한 프로그래밍
    - 코드 없이도 미리 약속한 규칙을 따라 동작하도록

테스트 컨텍스트 변경
1. XML 위치 지정 -> DI 정보 담고 있는 클래스 생성
2. `<context:annotation-config />` 제거
    - 클래스를 DI 정보로 사용하면 XML 의 위 부분 필요 없음
3. XML 에 정의된 `<bean>` 클래스의 메소드로 이동
4. XML 빈 참조해야 하는 경우, `@Autowired` 사용
5. `<bean>`이 아닌 전용 태그는 builder 등 지원해주는 기능으로 사용
6. 트랜잭션 지원해야 하는 경우, `@EnableTransactionManagement`

### 빈 스캐닝과 자동 와이어링
- `@Autowired` : 자동 와이어링 기법, 조건에 맞는 빈을 찾아 자동으로 넣어줌
- `@Component` : 빈 스캐너를 통해 자동으로 빈으로 등록
- `@ComponentScan` : 빈 스캔 대상 패키지 지정

### 프로파일
실행 환경 별 다른 빈 정의가 필요한 경우
- `@Profile` : 프로파일 지정
- `@ActiveProfiles` : 활성 프로파일 목록
    - 해당 목록에 자신의 프로파일이 포함되지 않으면 무시됨

<details>
<summary>sample</summary>

```java
@Configuration
public class TestConfiguration {

    @Bean
    @Profile("A")
    public Sth ASth() {
        
        return new Sth("A");
    }
    
    @Bean
    @Profile("!A")
    public Sth notASth() {
        
        return new Sth("B");
    }
}

@SpringBootTest
@ActiveProfiles("C")
class SomeTest {
    
    @Autowired
    Sth sth;
    
    @Test
    public void testSth() {

        assert sth.getValue().equals("B");
    }
}
```
</details>

### 빈 설정의 재사용과 @Enable*
- `@Enable*` : 특정 설정 클래스를 `@Import`
    - ex. `@EnableSqlService`

**Comment by tmfrl1552** [comment]
# 7.6 스프링 3.1의 DI
### 자바 언어의 변화와 스프링

#### 애노테이션의 메타정보 활용
* 자바 코드의 메타 정보를 이용한 프로그래밍 방식
* 자바는 소스 코드가 컴파일된 후, 클래스 파일에 저장됐다가 JVM에 의해 메모리로 로딩되어 실행
* 자바 코드가 실행되는 것이 목적이 아니라 다른 자바 코드에 의 해 데이터 처럼 취급되기도 함
* java5와 javaEE5가 등장한 시점부터 급격하게 확산
* 원래 리플렉션 API는 자바 코드나 컴포넌트를 작성하는데 사용되는 툴을 개발할 때 이용
	* 언제부턴가 본래 목적 보다는 자바 코드의 메타정보를 데이터로 활용하는 스타일의 프로그래밍 방식에 더 많이 활용
* 절정은 자바5의 애노테이션 등장
	* 애노테이션 활용이 늘어난 이유?
		* 애플리케이션 핵심 로직을 담은 자바 코드와, 이를 지우너하는 IoC 방식의 프레임워크
		  그리고 프레임워크가 참조하는 메타정보라는 세가지로 구성하는 방식에 잘 어울림
* 애노테이션 사용의 장/단점
	* 장점
		* XML에 비해 작성할 정보의 양이 줄어들고, 오타 발생률이 적음
		* XML에 비해 코드로 내장되어 있어 리팩토링을 할때 안전함
	* 단점
		* 어느 환경에서나 손쉽게 편집이 가능하고 내용을 변경하더라도 다시 빌드를 거칠 일이 없는 XML에 비해
		  자바 코드에 존재하므로 변경할 떄 마다 매번 클래스 새로 컴파일 필요

* 자바 개발의 흐름은 점차 XML 같은 텍스트 형태의 메타정보 활용을 자바 코드에 내장된
  애노테이션으로 대체하는 쪽으로 가고 있음

<br>


#### 정책과 관례를 이용한 프로그래밍
* 애노테이션 같은 메타정보를 활용하는 프로그래밍 방식은 코드를 이용해 명시적으로 동작 내용을 기술하는 대신
  코드 없이도 미리 약속한 규칙 또는 관례를 따라 프로그램이 동작하도록 만드는 프로그래밍 스타일 적극 포용하게 만들어 옴

* 애노테이션은 작성하는 코드의 양에 비해 부가적으로 얻을 수 있는 정보가 많으므로
  일정한 패턴을 따르는 경우 관례를 부여해 명시적인 설정을 최대한 배제하면 애플리케이션의 코드가 매우 간략해짐
  * 코드로 직접 모든 내용을 작성하는 것보다 간결하고 빠른 개발이 가능하므로,
    이런 스타일의 프로그래밍 방식은 지속적으로 인기를 끔

<br>


## 7.6.1 자바 코드를 이용한 빈 설정
### <context:annotation-config /> 제거
* @Configuration이 붙은 설정 클래스를 사용하는 컨테이너 사용 시, 
  더 이상 <context:annotation-config /> 을 넣을 필요가 없음


### <bean>의 전환
* <bean>으로 정의된 DI 정보는 자바 코드, 특별히 @Bean이 붙은 메소드와 거의 1:1로 맵핑
* @Bean 은 @Configuration이 붙은 DI 설정용 클래스에서 주로 사용,
  메소드를 이용해서 빈 오브젝트의 생성과 의존관계 주입을 직접 자바 코드에서 작성
* <bean>은 @Bean이 붙은 public 메소드로 작성
* 스프링의 <bean>에 넣는 클래스는 굳이 public이 아니어도 됨
	* 내부적으로는 리플렉션 API를 이용하므로 private으로 접근을 제한해도 빈의 클래스로 사용
	* 직접 자바 코드에서 참조할 때는 패키지가 다르면 public으로 접근 제한자 수정 필요
* @Autowired
	* @Autowired가 붙은 필드 타입과 같은 빈이 있으면, 해당 빈을 필드에서 자동으로 넣어줌
	* 빈 클래스 내부에서 수정자 주입 대신해서 필드 주입으로도 사용
	* @Configuration 클래스에서 XML 등으로 정의된 빈을 가져올 때 사용
	* @Configuration 클래스를 하나 이상 사용하는 경우 다른 클래스의 @Bean 메소드로 정의된 빈 참조시 사용 가능 
* @Resource
	* @Autowired와 유사하게 필드에 빈 주입 시 사용
	* 차이점
		* @Autowired : 필드의 타입 기준으로 빈 찾기
		* @Resource : 필드의 이름을 기준으로 빈 찾기

### 전용 태그 전환
* <tx:annotation-driven />은 다음 애노테이션을 
  TestApplicationContext에 붙여주는 것으로 간단히 변환 가능
* 스프링 3.1은 XML에서 자주 사용되는 전용 태그를 
  @Enable로 시작하는 애노테이션으로 대체할 수 있게 다양한 어노테이션 제공


<br>

## 7.6.2 빈 스캐닝과 자동와이어링
* 원래 자바 언어에서 private 필드에는 클래스 외부에서 값을 넣을 수 없으나,
 스프링은 리플렉션 API를 이용해 제약조건을 우회해서 값을 넣어준다.



### @Component를 이용한 자동 빈 등록
* @Component는 클래스에 부여
* @Component가 붙은 클래스는 빈 스캐너를 통해 자동으로 빈 등록
* @Component 또는 @Component를 메타 애노테이션으로 갖고 있는 애노테이션이 붙은 클래스가 자동 빈 등록 대상
* @Component는 '빈으로 등록될 후보 클래스'에 붙여주는 '일종의 마커'
* @ComponentScan의 basePackages 엘리먼트는 @Component가 붙은 클래스를 
  스캔할 기준 패키지를 지정할 때 사용
  	* 기준 패키지는 여러개 넣어도 가능
* @Component가 붙은 클래스의 이름대신 다른 이름을 빈의 아이디로 사용하고 싶다면 다음과 같이 사용
```java
@Component("userDao")
```
* AOP에서 포인트컷 작성 시에 애노테이션 활용 가능
	* 패키지나 클래스 이름 패턴 대신 애노테이션을 기준으로 어드바이스 적용 대상 선별
		* ex. @Transactional

* 여러 개의 애노테이션에 공통 속성 부여 시, "메타 애노테이션" 이용
	* 메타 애노테이션 이란 ? 
		* 애노테이션의 정의에 부여된 애노테이션
	* 애노테이션 정의에 @Component를 메타 애노테이션으로 붙여주면 됨
* @Repository
	* 스프링이 DAO 빈을 자동 등록 대상으로 만들때 사용할 수 있게 제공
	* DAO 기능 제공 클래스에서 사용 권장
* @Service
	* 비즈니스 로직을 담고 있는 서비스 계층의 빈 구분 위해 사용

<br>

## 7.6.3 컨텍스트 분리와 @Import
### @Import
* 자바 클래스로 된 설정 정보를 가져올 때 @ImportResource 대신 @Import 이용


<br>

## 7.6.4 프로파일
### @Profile과 @ActiveProfiles
* 실행환경에 따라 빈 구성이 달라지는 내용을 프로파일로 정의해서 만들고,
  실행 시점에 어떤 프로파일의 빈 설정 사용할지 지정
* 프로파일 적용 시, 하나의 설정 클래스만 가지고 환경에 따라 다른 빈 설정 조합 만들 수 있음
* 프로파일은 '설정 클래스' 단위로 지정
* @Profile 애노테이션을 클래스 레벨에 부여하고 프로파일 이름 넣어주면 됨
* 스프링 3.1은 프로파일이 지정되어 있지 않은 빈 설정은 default 프로파일로 취급
	* dafault 빈 설정 정보로 취급되어 항상 적용
* @Profile이 붙은 설정 클래스는 @Import로 가져오든 @ContextConfiguration에 직접 명시하든 상관 없이
  현재 컨테이너의 활성 프로파일 목록에 자신의 프로파일 이름이 들어 있지 않으면 무시됨
  * @ActiveProfiles 애노테이션 사용
  * 일종의 필터처럼 적용


### 컨테이너의 빈 등록 정보 확인
* 스프링 컨테이너는 모두 BeanFactory라는 인터페이스 구현
* 구현 클래스 중에 DefaultListableBeanFactory가 있는데 
  거의 대부분의 스프링 컨테이너는 이 클래스를 이용해 빈을 등록하고 관리
* DefaultListableBeanFactory 오브젝트를 @Autowired로 주입받아서 이용하게 해줌
	* getBeanDefinitionNames() 메소드가 있어서 컨테이너에 등록된 모든 빈 이름을 가져올 수 있고,
	  빈 이름을 ㅣ용해서 실제 빈과 빈 클래스 정보 등도 조회 

<br>

## 7.6.5 프로퍼티 소스
* 프로퍼티 소스
	* 컨테이너가 프로퍼티 값을 가져오는 대상
* @PropertySource 애노테이션 이용
* @PropertySource로 등록한 리소스로부터 가져오는 프로퍼티 값은 
  컨테이너가 관리하는 Environment 타입의 환경 오브젝트에 저장
* 주입받은 Environment 오브젝트의 getProperty() 메소드를 이용해 프로퍼티 값 가져올 수 있음

### PropertySourcesPlaceholderConfigurer
* @Value 애노테이션
	* 이름 그대로 값을 주입 받을 때 상ㅅㅇ
	* 프로퍼티 소스로부터 값을 주입받을 수 있게 '치환자'를 이용
* 치환자라고 부르는 이유
	* XML에서 <property>의 value 사용하는 값 치환 방식과 유사
* @Value와 치환자를 이용해 프로퍼티 값을 필드에 주입하려면 특별한 빈 하나 선언 필요
	* 프로퍼티 소스로부터 가져온 값을 @Value 피륻에 주입하는 기능 제공해주는
	  PropertySourcesPlaceholderConfigurer 
	* 빈 팩토리 후처리기로 사용되는 빈을 정의해주는 것인데 
	  이 빈 설정 메소드는 반드시 스태틱 메소드로 선언
``` java
@Bean
public static PropertySourcesPlaceholderConfigurer placeholderConfigurer() {
	return new PropertySourcesPlaceholderConfigurer();
}
```

<br>

## 7.6.6 빈 설정 재사용과 @Enable* 
### @Enble* 애노테이션
* @Import를 다른 이름의 애노테이션으로 대체 가능
* @Import 애노테이션과 빈 설정 클래스 값을 메타 애노테이션으로 넣어서 다음과 같이 만들어주면 됨
``` java
@Import(value=SqlServiceContext.class)
public @interface EnableSqlService{
	
}
```

**Comment by aimhigh53** [comment]
## ✏️ 15주차 

## 7.6 스프링 3.1의 DI

### 자바 언어의 변화와 스프링
- 어노테이션의 메타정보 활용
   * 자바 코드의 메타정보를 데이터를 활용하는 스타일의 프로그래밍 방식에서 리플렉션 API를 활용하도록 변화, 이 방식의 절정이 어노테이션임
   * 리플렉션 API를 이용해 어노테이션 메터정보를 조회하고 가져오는 방법이 전부임
   * IOC 프레임워크가 참조하는 메타정보로 사용되기 때문에 어노테이션 활용도가 증가, XML을 DI용 메터정보로 활용하기 때문에, 간결한 코딩 가능
   
### 빈 스캐닝과 자동와이어링
 - 자동 와이어링
   * @autowired
   * 파라미터 타입을 보고 주입 가능한 타입의 빈을 모두 찾음
   * 주입 가능한 빈이 2개 이상일 때는 그중에서 프로퍼티와 동일한 이름의 빈을 찾아 넣고 없음 에러
   * 장점은 DI줄이고, 단점은 의존관계 파악이 어려움
  
  - @Component
   * class에 붙으면 빈스캐너를 통해 자동으로 빈으로 등록될 대상이 된다.

  -  구현클래스만 빈 등록, 코드 수정없이 구현 기술을 적용할 수 있음
  -  castor 구현..


### 컨텍스트 분리와 @Import
 - 컨텍스트 분리
   * 테스트를 위해 만든 빈은 테스트에만 사용돼야하고 실제 애플리케이션에는 포함하지 않도록
   * @Import
   * ->SQL서비스처럼 다른 애플리케이션에서도 사용할 수 있고, 독립적으로 개발/변경될 가능성이 높은 서비스는 독립적인 모듈처럼 취급하는게 좋다.
   * -> DI 설정정보 클래스를 분리해서 사용, 이를 @Import를 써서 함께 적용될 수 있도록 하자

### 프로파일
- 테스트와 운영환경에서 각기 다른 빈 정의가 필요한 경우 - 양쪽 모두 필요하면서 내용만 다른 것들은 설정정보를 변경하고 조합하는 것으로는 한계가 있음 (ex. mailSender)
 * ->실행환경에 따라 빈 구성이 달라지는 내용을 프로파일로 정의해서 만들어두고, 실행시점에 지정해서 사용
 *  스프링 컨테이너에 등록된 빈 정보 조회방법
 * ->스프링 컨테이너는 모두 BeanFactory 인터페이스를 구현함. 이중DefaultListableBeanFactory 클래스로 빈을 등록하고 관리한다. 이걸 @Autowired로 주입받아서 이용하면 된다.

### 프로퍼티 소스
- DB 연결정보를 환경별로 다르게 설정, 이를 쉽게 변경할 수 있도록 해야함
- 프로퍼티 파일에 저장에서 사용하는 방식
 * 컨테이너가 프로퍼티 값을 가져오는 대상을 property source라고 한다.
 *@Value.. 다들 알듯
 

### 빈 설정의 재사용과 @Enable*
- SqlServiceContext를 sql서비스 라이브러리 모듈에 포함시켜서 재사용 가능하게 하기
  * 여전히 UserDao에 종속된 정보가 남아있어서 다른 애플리케이션에서 SqlServiceContext를 재사용할수가 없다. DI설정용 클래스인 SqlServiceContext까지 독립적인 모듈로 분리하려면 
  *-> SqlMapConfig 인터페이스를 정의
  * ->SqlMapConfig의 구현체에서 리소스를 어디서 가져오는지를 구현

### @Enable*
- 모듈화된 빈 설정을 가져올 때, @Enable로 시작하는 메타 어노테이션을 사용

**Comment by yougahee** [comment]
## ✏️ 15주차 (7장 마무리)

## 자바 언어의 변화와 스프링

### 변화1) 애노테이션의 메타정보 활용 
- 절정 
       - AVA5 에서 등장한 애노테이션
- 활용이 늘어난 이유 
	- 핵심 로직을 담은 자바 코드, IoC 방식의 프레임워크, 프레임 워크가 참조하는 메타정보 이 3가지로 구성하는 방식에 잘 어울리기 때문.
- 장점
        - XML로 작성하던 것을 애노테이션 하나로 정의가 되어 훨씬 가독성도 좋고, 리팩토링 하기도 좋다.
- 단점
	- 매번 자바 컴파일 필요
- 흐름
        - XML 을 사용하다가, 자바 코드를 활용하는 애노테이션 방식으로 변화하고 있다.

### 변화2) 정책과 관례를 이용한 프로그래밍
- 애노테이션은 작성하는 코드의 양에 비해 부가적으로 얻을 수 있는 정보가 많다. 
때문에 일정한 패턴을 따르는 경우 관례를 부여해 명시적인 설정을 최대한 배제하면 코드가 매우 간결해진다. 


## 스프링 3.1 의 DI 스타일 만들기
### 1. XML 없애기
- XML 에 저장하고 있던 정보를 자바 코드로 대체하기 (클래스를 만들어, 연결해주자.)
	``` java
		@ContextConfiguration(classes=TestApplicationContext.class)

		// class
		@Configuration
		public class TestApplicationContext {}

	```

### 2. <context:annotation-config /> 제거
- @Configuration 이 붙은 자바 클래스를 DI 정보로 사용하면, XML에 있던 <context:annotation-config />은 더 이상 필요하지 않다.
-  <context:annotation-config /> 사용 예시 
      - @PostConstruct를 붙인 메소드가 빈이 초기화된 후에 자동으로 실행되도록 사용했다.


### 3. "<bean>"의 전환
- @Bean 이 붙은 public 메소드로 만들어 주면 된다.
	- spring의 <bean>에 넣는 클래스는 굳이 public이 아니어도 되지만, 자바코드로 작성할 때는 public으로 변경해줘야 한다.
- 메소드 이름은 <bean>의 id 값으로 한다.
- 리턴 타입은 해당 빈을 주입받아서 사용하는 다른 빈이 어떤 타입으로 빈의 존재를 알고 있는지 확인해서 작성할 필요가 있다.
	``` java
		@Bean
		public DataSource dataSource() {
			SimpleDriverDataSource dataSource = new SimpleDriverDataSource();

			dataSource.setDriverClass(Driver.class);
			dataSource.setUrl("jdbc:mysql:~~");
			dataSource.setUserName("spring");
			dataSource.setPassword("book");

			return dataSource;
		}
	```

### 4. @Autowired 와 @Resource
	- @Autowired : 필드 타입을 기준으로 빈을 찾음.
	- @Resource : 필드 이름을 기준으로 빈을 찾음.

### 5. 전용 태그 전환
	- <jdbc:embedded-database> -> @Bean
	- <tx:annotation-driven> -> @EnableTransactionManagement


## 빈 스캐닝과 자동와이어링
### 자동 와이어링
- 조건에 맞는 빈을 찾아 자동으로 수정자 메소드나 필드에 넣어준다.
- 컨테이너가 자동으로 주입할 빈을 결정하기 어려운 경우, 직접 프로프티에 주입할 대상을 지정하면 된다.
- 주입 우선 순위
	1) 타입
	2) 빈의 이름
	- 위 2개 모두 동일할 시 에러


### @Component를 이용한 자동 빈 등록
- 클래스에 부여되고, 해당 애노테이션이 있는 클래스는 빈으로 등록된다.
- 빈의 아이디는 클래스의 이름의 첫글자를 소문자로 바꿔서 사용한다.
	- 이름을 지정할 수도 있음
- @ComponentScan
	- 특정 패키지 아래서만 찾도록 기준이 되는 패키지를 지정


### @Repository
- 스프링에서 DAO 기능을 제공하는 클래스에 @Repository 애노테이션을 이용하도록 권장함.

### @ContextConfiguration
- 테스트용 컨텍스트를 분리하자. 
	- 테스트용으로 사용할 빈 정보만 분리하여 사용하는 편이 좋다.
- 예시
	- @ContextConfiguration(classes={TestAppContext.class, AppContext.class})

### @Import
- 테스트용 설정 정보는 애플리케이션 핵심 설정 정보와 깔끔하게 분리되는 편이 좋다.
- 보조 설정 정보는 @Import 를 사용하여 긴밀하게 연결하게 하자.

### @Profile
- 테스트와 운영 환경에서의 빈 분리 시, 사용하는 애노테이션
- 테스트 환경에서 사용할 빈들을 정의해둔 클래스에 작성하면 됨
	- ``` java
		@Configuration
		@Profile("test")
		public class TestAppContext {

		}
	```
- 테스트와 운영 환경에서 각기 다른 빈 정의가 필요한 경우가 있다.
	- ex) 메일 전송 

### @PropertySource
- application.properties 처럼 테스트용으로 property를 만들어 정의해주기
- 테스트용 DB 연결 정보 분리를 위해

### @Value 값을 주입해주는 방법
- 빈 팩토리 후처리기로 사용되는 빈을 정의
- 반드시 스태틱 메소드로 선언을 해야함
``` java
@Bean
public static PropertySourcePlaceholderConfigurer placeholder() {
	return new PropertySourcePlaceholderConfigurer();
}
```

## 빈 설정의 재사용과 @Enable*
- 특정 설정 클래스를 @Import 하여 사용
- 직접 정의한 애노테이션
