### ISSUE TITLE
Chapter8. 스프링이란 무엇인가?

### ISSUE THREAD

**Issue by tmfrl1552** [FireInStove/toby-spring#16]
## 👑 스터디장
- 슬기 (@tmfrl1552)
## 📖 스터디 범위
- 8장
## 🕧 스터디 일정
- 23/9/21 (목) 09시

**Comment by aimhigh53** [comment]
스프링 스터디

## 8.1스프링?

"자바 엔터프라이즈 개발을 편하게 해주는 오픈소스 경량급 애플리케이션 프레임워크"

* 프레임워크는 애플리케이션의 특정 계층에서 주로 동작하는 한 가지 기술 분야에 집중된다.
* JDBC/ORM은 일부기술,  Ioc/DI프레임워크 or AOP 툴이라고 보는이유는 핵심기술만 주목
	—> 스프링의 일차적인 존재 목적은 핵심기술에 담긴 프로그래밍 모델을 일관되게 적용해서 엔터프라이즈 애플리케이션 전 계층과 전 영역에 전략과 기능을 제공해줌으로써 애플리케이션을 편리하게 개발하게 해주는 app 프레임워크임

경량급
* 과도한 욕심으로 인하여 개발환경 운영서버, 테스트과정 개발, 빌드, 작성된 코드를 매우 무겁게 만든 EJB에 비하여 가볍다는 의미.

오픈소스
* 단점으로는 지속적이고 안정적인 개발이 가능할지가 불투명하다. 개발자의 여가시간을 이용해 일종의 취미로 만들어질 가능성이 높기에 문제가 생긴다면 그 즉시 중단될 수 있음

## 8.2 스프링의 목적

복잡함의 원인
* 기존 엔터프라이즈 프레임워크들이 실패했던 이유는, 비즈니스 로직과 엔터프라이즈 기술이라는 두 가지 복잡함이 얽혀있기 때문이다. 비즈니스 로직을 구현할 때 기술적인 문제까지 고려해야 하는 일이 많아짐

스프링 전략
* 기술에 대한 일관적인 접근방법
* 기술과 관련된 코드와 비즈니스 로직의 핵심 코드와 분리하기
* 비즈니스/애플리케이션 로직의 복잡함 상대하기
* 스프링의 핵심 도구 : 객체지향과 DI

## 8.3 POJO 프로그래밍

pojo?

* 특정 규약(contract)에 종속되지 않음
    * 특정 환경에 종속되지 않는다
    * 단일 책임 원칙을 지키는 클래스
* 위 원칙을 지키며 POJO에 핵심 로직을 담고 설계하는 방법을 POJO 프로그래밍이라 부를 수 있다
* 자바문법대로 다 지켰다고해서 꼭 POJO는 아니다

## 8.4 스프링의 기술

IoC/DI
* '유연한 확장이 가능하게 하기 위해서'
* SOLID 원칙 중 OCP는 확장에는 열려있지만(주입하는 빈은 구현이 바뀌거나 다른 클래스가 될 수 있음) 변경에는 닫혀있다(주입받는 클래스는 빈이 어떻게 바뀌든 변경의 이유가 생기지 않음)
* 핵심 기능의 변경,핵심 기능의 동적인 변경,부가기능의 추가,템플릿과 콜백

AOP
* 스프링과 같이 다이나믹 프록시를 사용하는 방법
* 스프링에서 구현할 수 있지만 부가기능을 부여할 수 있는 곳이 오로지 메서드 호출지점이라는 단점이 존재한다
* 자바 언어의 한계를 넘어서는 언어의 확장을 이용하는 방법
* 다양한 조인포인트를 이용하기 위해선 AspectJ라는 유명한 AOP 오픈소스 라이브러리를 사용할 수도 있다
* 메서드 호출, 인스턴스 생성, 필드 엑세스 등에도 부가 기능을 적용할 수 있다
*  직접 바이트코드를 수정하기 때문에 AOP 변경사항이 존재할 때 마다 새로 컴파일을 해주어야 한다는 단점이 있다.
* 잘 선택해서 써야한다~

PSA
* '일관성 있는 서비스 추상화 기술'
* POJO 코드가 기술에 직접적으로 노출되어 만들어져서는 안된다는 의미이다.
* 프링이 정의한 트랜잭션 추상화 인터페이스인 PlatformTransactionManager를 통해 트랜잭션 기술을 이용한다면, 추후DB가 바뀌거나 하는 문제들에도 코드는 변하지 않고 제 역할을 해낼 것이다.

**Comment by yougahee** [comment]
# ✏️ 16주차 (8장)

## 스프링이란?
자바 엔터프라이즈 개발을 편하게 해주는 오픈소스 경량급 애플리케이션 프레임워크

#### 1) 애플리케이션 프레임워크
- 특정 계층이나 기술, 업무 분야에 국한되지 않고 애플리케이션의 전 영역을 포괄하는 범용적인 프레임워크

#### 2) 경량
- 가장 단순한 서버환경인 톰캣이나 제티에서도 동작한다.

#### 3) 자바 엔터프라이즈 개발을 편하게
- 비즈니스 로직 구현에만 집중하고 빠르고 효율적.
- 개발자가 복잡하고 실수하기 쉬운 로우레벨 기술에 많은 신경쓰지 않도록 함

#### 4) 오픈소스
특별한 라이선스를 취득할 필요없이 얼마든지 가져다 자유롭게 이용
- 장점
  - 개발 과정에 많은 사람이 자유롭게 참여한다.
  - 다양한 참여를 통해 매우 빠르고 유연한 개발이 가능하다.
  - 라이선스 비용에 대한 부담이 없다.
- 단점
   - 지속적이고 안정적인 개발이 계속될지 불확실

-> 그래서, 스프링은 오픈소스의 단점을 보완하고자 회사를 설립하여 개발을 꾸준히 이어가고 있다.

</br>

## 스프링의 목적
스프링을 활용해서 엔터프라이즈 애플리케이션 개발을 편하게 하는 것

### 엔터프라이즈 시스템의 복잡함의 "이유"
1. 기술적인 제약조건과 요구사항이 늘어남
	- 보안, 안정성, 확장성, 동시성, 분산 트랜잭션 등
2. 구현해야 할 핵심기능인 비즈니스 로직의 복잡함이 증가
	- 정책, 사회의 변화, 흐름에 따라 변경하고 추가되는 프로세스 등이 많아짐.

### 스프링이 선택한 해결책 : "비침투적인 방식"
복잡함의 원인은 제거할 대상이 아니다. (로직을 쉽게 작성하기 위해 보안을 신경쓰지 않는다는 것은 말이 안된다.)
- *복잡함을 줄일 전략과 기법*이 필요하다.
- 비즈니스 로직에 지저분하고 복잡한 코드를 만들지 말자.
- 비침투적이란? 
	- 기술의 적용 사실이 코드에 직접 반영되지 않는다.
	- 로직 중간에 불쑥 등장하거나, 코드의 설계와 구현 방식을 제한하지 않는다.

</br>


## 스프링의 전략
- 문제점1 : 특정 환경에 종속적이여서, 서버나 환경이 변경되면 코드가 변경됨
	- 해결책 : 서비스 추상화
- 문제점2 : 기술적인 처리를 담당하는 코드가 성격이 다른 코드에 섞여서 등장
	- 예시 : 비즈니스 로직 전후로 경계가 설정돼야 하는 트랜잭션, 보안적용 등
	- 해결책 : AOP


</br>


## POJO 프로그래밍
DI : 유연하게 확장 가능한 오브젝트를 만들어두고 그 관계는 외부에서 다이내믹하게 설정해준다는 것

### POJO란?
- Plain Old Java Object 의 약자
- 자바의 단순한 오브젝트를 이용해 비즈니스 로직을 구현
- 객체지향적인 원리에 충실하면서, 환경과 기술에 종속되지 않고 필요에 따라 재활용 할 수 있는 방식으로 설계된 오브젝트

### POJO의 조건
1. 특정 규약에 종속되지 않는다.
	- 자바 언어와 꼭 필요한 API 외에는 종속되지 않아야 한다.
2. 특정 환경에 종속적이지 않는다.
	- 비즈니스 로직을 담은 코드에 HttpServletRequests나 HttpSession, 캐시와 관련된 API가 등장하거나 웹 프레임워크의 클래스를 직접 이용하는 부분이 있다면 진정한 POJO라고 볼 수 없다.

### 장점
- 특정한 기술과 환경에 종속적이지 않다. (깔끔한 코드)
- 자동화된 테스트에 매우 유리
- 객체지향적인 설계를 자유롭게 적용 가능


</br>

## 스프링의 기술

### POJO 프로그래밍을 손쉽게 할 수 있는 3가지 기능
1. IoC/DI
2. AOP
3. PSA

### IoC/DI 활용
- 유연한 확장이 가능
1. 의존 대상의 구현을 바꾸는 것(ex. 전략 패턴)
2. 핵심 기능 자체를 바꾸는 것
3. 핵심 기능은 그대로 둔 채 부가기능을 추가

- 예시
	- 템플릿과 콜백
	- 싱글톤과 오브젝트 스코프
	- 테스트 (Mock 오브젝트)

### AOP
- 순수한 객체지향 기법만으로 요구 조건과 난해함을 해결하기에 한계가 있는데, 이를 도와주는 보조적인 프로그래밍 기술이다.

#### AOP 적용 기법
1. 다이내믹 프록시를 사용하는 방법
	- 기존 코드에 영향을 주지 않고 부가기능을 적용함(=데코레이터 패턴)

2. 자바 언어의 한계를 넘어서는 언어의 확장을 이용하는 방법
	- AspectJ를 사용

#### AOP 의 적용 단계 (걍 팁이었네? ㅎ)
1. 미리 준비된 AOP 이용
	- 스프링이 직접 제공하는 AOP 사용(ex. 트랜잭션)
2. 정책 AOP 사용
	- AOP 담당 팀이 개발하여 만든 정책 사용
3. AOP의 자유로운 이용
	- 개발자가 적극 활용

### PSA(Portable Service Abstraction)
- 환경과 세부 기술의 변화에 관계없이 일관된 방식으로 기술에 접근할 수 있게 해줌

**Comment by flyingtw** [comment]
# 8.1 스프링의 정의
- 스프링이란 : 자바 엔터프라이즈 개발을 편하게 해주는 오픈소스 경량급 애플리케이션 프레임워크
## 애플리케이션 프레임워크
- 프레임워크랑 애플리케이션의 특정 계층에서 주로 동작하는 한 가지 
- 스프링의 기원은 자바 엔터프라이즈 개발 전략의 핵심을 정리하는것에서 시작되었다.
- 애플리케이션 전 영역에서 전략과 기능을 제공해주는게 스프링이다.
## 경량급
- 스프링은 불필요하게 무겁지 않다.
- 복잡했던 EJB보다 훨씬 가볍다
## 오픈소스
- 아파치 라이센스 버전 2.0
- spring source가 스프링 개발을 관리하고 있다.
- 현재는 VMware에 합병되었다.

# 8.2 스프링의 목적
## 8.2.1 엔터프라이즈 개발의 복잡함
- Java EE는 왜 실패하였는가?
- 기술적인 제약조건과 요구사항이 늘어났다.
- 엔터프라이즈 애플리케이션이 구현해야 할 핵심기느인 비즈니스 로직의 복잡함이 증가하였다.
- 복잡한 앤터프라이즈 기술과 변화가 필요한 비즈니스 로직들의 합에의해 Java EE는 실패하였다.
## 8.2.2 복잡함을 해결하려는 도전
- 실패한 EJB
- 원래 EJB의 목표는 개발자가 로우레벨의 기술적인 복잡함에 신경 쓰지 않고 비즈니스 로직을 효과적으로 개발하는데 더 집중할 수 있게 하자는 목표이다.
- 어떤 기술을 적용했을 때 그 기술과 관련된 코드나 규약등이 코드에 등장하는 경우를 침투적인 기술이라고 한다.
- 스프링은 비 침투적인 기술
## 8.2.3 복잡함을 상대하느 스프링의 전략
- 스프링은 AOP, DI등을 이용한 객체지향 언어의 목표를 충실히 이행하였다.

# 8.3 POJO 프로그래밍
## 8.3.1 스프링의 핵심 : POJO
- IoC/DI, AOP, PSA의 삼각형
- POJO : Plain Old Java Object = 간단한 자바 오브젝트 입니다~
## 8.3.3 POJO의 조건
- 특정 규약에 종속되지 않는다
- 자바언어와 꼭 필요한 API 외에는 종속되지 않아야 한다.
- 특정 환경에 종속되지 않는다.
## 8.3.4 POJO의 장점
- 특정한 기술과 환경에 종속되지 않는 오브젝트는 그만큼 깔끔한 코드가 될 수 있다.
## 8.3.5 POJO 프레임워크
- DB 이용 기술에 POJO 를 적용하는것을 목적으로 하는게 하이버네이트 이다.

# 8.4 스프링의 기술
- 스프링의 기술들은 스프링 프레임워크가 만들어진 진정한 목표인 POJO 기반의 엔터프라이즈 개발을 편리하게 해주는 도구일 뿐이다.
## 8.4.1 제어의 역전(IoC) / 의존관계 주입 (DI)
- 유연한 확장이 가능하게 하기 위해서이다.
### DI의 활용 방법
- 핵심기능의 변경 : 의존 대상의 구현을 바꾸는것이다. 전략패턴의 한 예
- 핵심기능의 동적인 변경 : 애플리케이션이 동작하는 중간에 그 의존 대상을 다이내믹하게 바꿀 수 있다.
- 부가기능의 추가 : 핵심기능은 그대로 둔채 부가기능을 추가하는 것 (데코레이터 패턴)
- 인터페이스의 변경 : 실제 사용하는 오브젝트와 인터페이스 상의 다름이 있어도 DI가 유용하다.
- 프록시
- 템플릿과 콜백 : 탬플릿을 만들어놓아 간결하게 만들 수 있다.
- 싱글톤과 오브젝트 스코프 : 오브젝트의 생명주기를 제어할 수 있다.
- 테스트 : 테스트 코드를 고립시킬 수 있게됨으로써 테스트가 용이하게 되었다.
## 8.4.2 애스팩트 지향 프로그래밍 (AOP)
- OOP(객체지향 프로그래밍)의 한계를 해결하기 위해 나왔다.
- 1. 스프링과 같이 다이내믹 프록시를 사용하는 방법
- 2. 자바 언어의 한계를 넘어선느 언어의 확장을 이용하는 방법
## 8.4.3 포터블 서비스 추상화
- 환경과 세부 기술의 변화에 관계없이 일관된 방식으로 기술에 접근할 수 있게 해주는 PSA
- 일관성 있는 서비스 추상화 기술이니까! (잘 갈아 끼울수 있게 )

**Comment by kyueun** [comment]
# 8. 스프링이란 무엇인가?
## 스프링
자바 엔터프라이즈 개발을 편하게 해주는 오픈소스 경량급 애플리케이션 프레임워크
- 애플리케이션 프레임워크
    - 특정 계층, 기술, 업무 분야에 국한 X, 애플리케이션 전 영역을 포괄하는 범용적인 프레임워크
    - 애플리케이션 개발 전 과정을 빠르고 편리하며 효율적으로 진행하는 데 목표를 두는 프레임워크
    - IoC/DI 프레임워크로만 보는 건 스프링이 제공하는 핵심 기술만 보는 것
- 경량급
    - EJB 같은 기술 대비 가벼움
    - WAS가 필요한 EJB와 달리, 단순한 서버 환경인 톰팻이나 제티에서도 동작
        - <details>
            <summary>톰캣도 WAS 아닌가?</summary>

            - WAS = Java EE를 완전히 구현한 것
                - Java EE : 기업용 애플리케이션에 필요한 기능들의 사양을 정의한 명세서 ( JSP. Servlet, EJB, JDBC 등 )
                    - ![JavaEE](https://github.com/kyueun/TIL/blob/main/%EB%8F%84%EC%84%9C/img/JavaEE.jpeg?raw=true)
            - 톰캣 = Java EE 중 Web Container만 구현한 것 ( 온전한 WAS가 아님, HTTP 요청을 Servlet을 통해 관리 )
            </details>
- 자바 엔터프라이즈 개발을 편하게
    - 로우레벨 기술에 신경쓰지 않고 비즈니스 로직을 빠르고 효과적으로 구현 가능
- 오픈소스
    - 개발 과정에 많은 사람들이 자유롭게 참여
    - 빠르고 유연한 개발
    - 지속적이고 안정적인 개발이 계속될지 불확실

## 스프링의 목적

Java EE ( 자바 엔터프라이즈 ) 프로젝트 실패 이유
- 엔터프라이즈 시스템의 복잡함
    - 기술적인 제약조건, 요구사항 증가
    - 비즈니스 로직 복잡함 증가

엔터프라이즈 시스템의 복잡함 문제 해결책
- 실패한 해결책 : EJB
    - 침투적인 기술 : 기술과 관련된 코드나 규약이 코드에 등장
    - 로직을 담은 코드에서는 기술적인 코드가 제거됐지만, 전체적으로 EJB 환경과 스펙에 종속되는 코드로 만들어져야 함
    - EJB 틀 안에서 강제적으로 제한한 사항 -> 객체지향적 특성을 잃음
- 비침투적 방식을 통한 해결책 : 스프링
    - 비침투적인 기술 : 기술의 적용 사실이 코드에 반영되지 않음
    - 기술적인 코드와 로직 코드 분리 가능
    - 성격이 다른 복잡함을 분리 -> 각각에 대해 상대

## 스프링의 전략
1. 기술적인 복잡함에 대한 전략
    - 기술에 대한 접근 방식이 일관성이 없고, 특정 환경에 종속적 -> 서비스 추상화
        - 추상화를 통해 기술 구현 / 기술 사용 인터페이스 분리
    - 기술적인 처리를 담당하는 코드가 성격이 다른 코드에 섞여서 등장 -> AOP
        - 로직에 남아있는 기술 코드를 분리, 별도 모듈로 관리
2. 비즈니스, 애플리케이션 로직의 복잡함에 대한 전략
    - 비즈니스 로직 오류 -> 객체지향 기술에 집중할 수 있게 방해 요소 제거

## POJO 프로그래밍
### POJO
- Plain Old Java Object
- 자바의 단순한 오브젝트를 이용해 비즈니스 로직을 구현

POJO의 조건
- 특정 규약에 종속되지 않는다
    - 자바 언어와 꼭 필요한 API 외에는 종속되지 않는다
- 특정 환경에 종속되지 않는다
    - 웹이라는 환경 정보, 웹 기술을 담고 있는 클래스, 인터페이스를 사용하면 안 됨
        - ex. `HttpServletRequest`, `HttpSession`, ...

POJO의 장점
- 깔끔한 코드 ( 특정 기술, 환경에 종속되지 않음 )
- 자동화된 테스트에 유리
- 객체지향적인 설계 자유롭게 적용 가능

POJO 프레임워크
- POJO 프로그래밍이 가능하도록 기술적인 기반을 제공하는 프레임워크
- ex. 스프링 프레임워크, 하이버네이트

## 스프링의 기술
POJO 프로그래밍을 쉽게 할 수 있도록 지원하는 가능기술

### IoC/DI
- 유연한 확장 가능
- DI의 활용 방식
    - 핵심기능 변경
    - 핵심기능의 동적인 변경 : 동적으로 매번 변경
    - 부가기능의 추가
    - 인터페이스의 변경 : 어댑터 패턴
    - 프록시
    - 템플릿과 콜백
    - 싱글톤과 오브젝트 스코프
    - 테스트

### AOP
- 객체지향 기술의 한계, 단점 극복하도록 도와주는 보조적인 프로그래밍 기술
- 적용 기법
    - 다이나믹 프록시 사용 ex. 스프링
    - 언어 확장 이용 ex. AspectJ

### PSA
포터블 서비스 추상화
- 특정 환경이나 구현 방식에 종속적이지 않는 POJO 프로그래밍을 위해 스프링이 제공하는 기술

**Comment by tmfrl1552** [comment]
# 8. 스프링이란 무엇인가?
> 스프링의 사상과 가치, 그리고 적용된 원칙 생각

## 8.1 스프링의 정의

```java
자바 엔터프라이즈 개발을 편하게 해주는 오픈소스 경량급 애플리케이션 프래임워크
```
> 스프링에 대해  가장 잘 알려진 정의

#### 애플리케이션 프레임워크
* '애플리케이션 프레임워크' 란?
	* 특정 계층이나, 기술, 업무 분야에 국한되지 않고 애플리케이션의 전 영역을 포괄하는 범용적인 프레임워크
	* 애플리케이션 개발의 전 과정을 빠르고 편리하며 효율적으로 진행하는데 일차적인 목표를 두는 프레임워크
* 스프링이 애플리케이션 프레임워크라고 불리는 이유? 
	* 애플리케이션의 전 영역을 관통하는 일관된 프로그래밍 모델과 핵심 기술을 바탕으로 해서 각 분야의 특성에 맞는
  	  필요를 채워주고 있기에, 애플리켕션을 빠르고 효과적으로 개발

#### 경량급
* 스프링이 가볍하도 하는 이유?
	* 불필요하게 무겁지 않단 의믜
* 단순한 툴과 기본적인 개발환경으로도 엔터프라이즈 개발에서 필요로 하는 주요한 기능을 갖춘
  애플리케이션을 개발하기에 충분
* 스프링
* 침투적인 기술
	* EJB처럼 어떤 기술을 적용했을 때  기반의 코드가 가벼운 이유
	* 코드에 불필요하게 등장했던 프레임워크와 서버환경에 의존적인 부분을 제거
* 만들어진 코드가 지원하는 기술 수준은 비슷하더라도 그것을 훨씬 빠르고 간편하게 작성하게 해줌 으로써
  생산성과 품질 면에서 유리 ➡️ '경량급' 으로 표현되는 스프링의 특징


#### 자바 엔터프라이즈 개발을 편하게
* 편리한 애플리케이션 개발이란?
	* 개발자가 복잡하고 실수하기 쉬운 로우레벨 기술에 많은 신경을 쓰지 않으면서도
	  애플리케이션의 핵심인 사용자의 요구사항, 즉 비즈니스 로직을 빠르고 효과적으로 구현하는 것 
* 스프링은 프레임워크가 제공하는 기술이 아니라 자신이 작성하는 애플리케이션 로직에 더 많은 관심과 시간을 쏟게 해줌
* 스프링의 뛰어난 점
	* 엔터프라이즈 개발에서 필연적으로 요구되는 기술적인 요구를 충족하면서도 개발을 복잡하게 만들지 않음


#### 오픈 소스
* 스프링은 '오픈소스' 프로젝트로 개발
* 스프링에 적용된 오픈소스 라이선스는 오픈소스 라이선스 주에서도 비교적 제약이 적고
  사용이 매우 자유로운 편인 '아파치 라이선스 버전 2.0'
	* 상업적인 목적의 제품에 포함시키거나 비공개 프로젝트에 자유롭게 이용
* 오픈소스의 장점
	* 공개된 커무니티의 공간 안에서 투명한 방식으로 다양한 참여를 통해 개발
	  ➡️ 매우 빠르고 유연한 개발 가능
* 오픈소스의 단점
	* 오픈소스 개발 방식의 가장 큰 취약점은 지속적이고 안정적인 개발이 계속될지가 불확실
	* 개발자 개개인에게 극히 의존적
* 스프링은 프레임워크 사용자에게 지속적인 신뢰를 주도록 개발을 책임지고 진행할 수 잇는 전문 기업 생성


<br>


## 8.2 스프링의 목적
> 스프링의 개발 철학과 궁극적인 목표

스프링의 목적은?
```java
'경량급 프레임워크인 스프링을 활용해서 엔터프라이즈 애플리케이션 개발을 편하게' 하는 것
```

<br>

* 굳이 스프링을 사용해서 엔터프라이즈 개발을 편하게 하려는 이유는?
	* 원래 엔터프라이즈 개발이란 편하지 않기 때문
* 엔터프라이즈 개발이 실패하는 이유 중 대표 원인
	* 엔터프라이즈 시스템 개발이 너무 복잡해져서

### 복잡함의 근본적인 이유
> 크게 두가지 원인 

#### 1. 기술적인 제약조건과 요구사항이 늘어가기 떄문
* 엔터프라이즈 시스템이란?
	* 서버에서 동작하며 기업과 조직의 업무를 처리해주는 시스템
* 엔터프라이즈 시스템이 기업 업무를 처리하는데 핵심적인 역할로 등장하고 중요해지면서
  점점 더 기술적인 요구는 심화되고 그에 따른 복잡도는 증가

#### 2. 엔터프라이즈 애플리케이션이 구현해야 할 핵심기능인 비즈니스 로직의 복잡함이 증가하기 때문
* 원래 기업 업무란 그 자체로 복잡
* 다양한 예외 상황도 많고, 처리해야 하는 정보의 규모도 상당함
* 엔터프라이즈 시스템이 관여한느 업무의 비율이 급격하게 커지고 있으니 애플리케이션 개발도 힘들고 복잡해져 감



### 복잡함을 해결하려는 도전

* 근본적으로 엔터프라이즈 개발에 나타나는 복잡함의 원인은 제거 대상이 아님
* 그 복잡함을 효과적으로 상대할 수 있는 '전략과 기법' 필요
* 문제는 비즈니스 로직의 복잡함을 효과적으로 다루기 위한 방법과
  기술적인 복잡함을 효과적으로 처리하는데 적용되는 방법이 다름
  	* ➡️ 성격이 다른 두 가지 복잡함 분리 필요

#### 실패한 해결책: EJB
* EJB(Enterprise Java Bean) 이란?
	* 기업환경의 시스템을 구현하기 위한 서버측 컴포넌트 모델
	*  즉, EJB는 애플리케이션의 업무 로직을 가지고 있는 서버 애플리케이션
* EJB 의 목표
	* 개발자가 로우레벨의 기술적인 복잡함에 신경 쓰지 않고 비즈니스 로직을 효과적으로 개발하는데 더 집중
* but, 목표 달성에 실패 
	* 상속 구조 적용하지 못하게 함
	* 다형성 적용을 근복적으로 제한.. 등등
	* EJB의 발전 주기는 너무 느려서 엔터프라이즈 개발 기술 발전을 따라잡지 못함


#### 비침투적인 방식을 통한 효과적인 해결책: 스프링
* 침투적인 기술
	* EJB처럼 어떤 기술을 적용했을 때 그 기술과 관련된 코드나 규약 등이 코드에 등장하는 겨우
* 비침투적인 기술
	* 기술의 적용 사실이 코드에 직접 반영되지 않는다는 특징
	* 애플리케이션 코드 여기저기에 불쑥 등장하거나, 코드의 설계와 구현 방식을 제한하지 않음
* 스프링의 성공 비결 => 비침투적인 기술
	* 스프링 이용 시, 기술적인 복잡함과 비즈니스 로직을 다루는 코드를 깔끔하게 분리


## 복잡함을 상대하는 스프링의 전략
* 스프링의 기본 전략
	* 비즈니스 로직을 담은 애플리케이션 코드와 엔터프라이즈 기술을 처리하는 코드를 '분리'
* 스프링은 엔터프라이즈 기술을 적용했을 때 발생하는 복잡함의 문제를 두 가지로 분류 및 대응 방법 제공


### 기술적인 복잡함을 상대하는 전략 
#### 첫 번쨰 문제: 기술에 대한 접근 방식이 일관성이 없고, 특정 환경에 종속적
* 위 문제의 공략 방법 : 서비스 추상화
* 기술적인 복잡함은 일단 추상화를 통해 로우레벨의 기술 구현 부분과 기술을 사용하는 인터페이스 분리
  환경과 세부 기술에 독립적인 접근 인터페이스를 제공하는 것이 가장 좋은 해결책


#### 두 번째 문제: 기술적인 처리를 담당하는 코드가 성격이 다른 코드에 섞여서 등장
* 위 문제의 공략 방법 : AOP
* AOP는 취호까지 애플리케이션 로직을 담당하는 코드에 남아 있는 기술 관련 코드를 깔끔하게 분리해서
  별도의 모듈로 관리하게 해주는 강력한 기술 


### 비즈니스와 애플리케이션 로직의 복잡함을상대하는 전략 
* 전략 > 자바라는 객체지향 기술 그 자체
	* 객체지향 프로그래밍 기법과 언어가 주는 장점인 유연한 설계가 가능하고 재사용성이 높다는점을 잘 활용
	  자주 바뀌고 조건이 까다로운 비즈니스 로직을 효과적으로 구현
* 스프링은 단지 객체 지향 언어의 장점을 제대로 살리지 못하게 방해했던 요소를 제거하도록 도와줌


### 핵심 도구: 객체지향과 DI
* 자바의 기본인 객체지향에 충실한 설계가 가능하도록 단순한 오브젝트로 개발
* 객체지향의 설계 기법을 잘 적용할 수 있는 구조를 만들기 위해 DI 같은 유용한 기술을 편하게 적용하도록 도와줌
	* 스프링의 기본 전략 

```java
결국 모든 스프링의 기술과 전략은 '객체지향'이라는 자바 언어가 가진 강력한 도구를
극대화해서 사용할 수 있도록 돕는 것.
스프링은 단지 거들 뿐
```


## 8.3 POJO 프로그래밍 
* 엔터프라이즈 서비스란?
	* 엔터프라이즈 시스템에서 요구되는 기술
* 스프링의 가장 강력한 특징과 목표
	* '분리됐지만 반드시 필요한 엔터프라이즈 서비스 기술을 
	   POJO 방식으로 개발된 애플리케이션 핵심 로직을 담은 코드에 제공'

### POJO란 무엇인가?
* POJO(Plain Old Java Object)
	* 간단한 자바 오브젝트를 있어보이게 부른 것
	* EJB와 같은 그럴싸한 이름을 붙여서 좀 더 많이 사용하게 하기 위함..

### POJO의 조건
#### 특정 규약에 종속되지 않는다.
* POJO는 자바 언어와 꼭 필요한 API 외에는 종속되지 않아야 한다.
	* 특정 규약을 따라 만들게 하는 경우는 대부분 규약에서 제시하는 특정 클래스를 상속하도록 요구
	* 자바의 단일 상속 제한 때문에 더 이상 해당 클래스에 객체지향적인 설계 기법 적용 어려움
* 규약따위에 종속되지 않아야 하고, 객체지향 설계의 자유로운 적용이 가능한 오브젝트여야 POJO

#### 특정 환경에 종속되지 않는다.
* POJO는 환경에 독립적이어야 함 
* 비즈니스 로직을 담고 있는 POJO 클래슨느 웹이라는 환경정보나 웹 기술을 담고 있는 클래스나 인터페이스 사용 안됨

```java
* 진정한 POJO란?
객체지향적인 원리에 충실 하면서, 환경과 기술에 종속되지 않고 필요에 따라 
재활용될 수 있는 방식으로 설계된 오브젝트  

* POJO 프로그래밍이란?
그런 POJO에 애플리케이션 핵심 로직과 기능을 담아 설계하고 개발하는 방법
```

### POJO의 장점
> POJO의 장점은 POJO가 될 수 있는 조건이 그대로 장점
* 자동화된 테스트에 매우 유리
	* 어떤 환경에도 종속되지 않으므로 매우 유연한 방식으로 원하는 레벨에서 코드를 빠르고 명확하게 테스트
* 객체지향적인 설계를 자유롭게 적용할 수 있음


### POJO 프레임워크
* POJO 프레임워크란?
	* POJO 프로그래밍이 가능하도록 기술적인 기반을 제공하는 프레임워크
	* 스프링은 POJO 프레임워크
* 스프링 이용 시, POJO 프로그래밍의 장점을 그대로 살려 엔터프라이즈 애플리케이션의 핵심로직을 
  객체지향적인 POJO를 기반으로 깔끔하게 구현 

* 스프링은 비즈니스 로직의 복잡함과 엔터프라이즈 기술의 복잡함을 분리해서 구성할 수 있게 도와줌
	* 스프링은 기술 영역에만 관려하고 비즈니스 로직을 담당하는 POJO에서는 모습을 감춤
* 스프링은 POJO 프레임워크로써 자신을 직접 노출하지 않으면서 애플리케이션을 POJO로 쉽게 개발할 수 있게 지원 

![images_superkkj_post_4fd38aed-21bb-4e9e-b754-2479e27dec06_image](https://github.com/FireInStove/toby-spring/assets/52412936/3a98b4a6-28e9-4898-ba82-ed0a62048c7a)



<br>

## 8.4 스프링의 기술
스프링은 POJO 프로그래밍을 손쉽게 할 수 있도록 세 가지 가능 기술 제공
> IoC/DI, AOP, PSA

### 제어의 역전(IoC) / 의존관계 주입(DI)
* 스프링의 가장 기본이되는 기술, 스프링의 핵심 개발 원칙
* 구체적인 DI 활용 방법
	* 핵심 기능의 변경
		* 전략 패턴
	* 핵심기능의 동적인 변경
		* 다이내믹 라우팅 프록시, 프록시 오브젝트 기법 활용
	* 부가기능의 추가
		* 데코레이터 패던
	* 인터페이스의 변경
		* 어댑퍼 패턴의 응용
	* 프록시
		* 프록시 패턴의 응
	* 테플릿과 콜백
	* 싱글톤과 오브젝트 스코프
	* 테스트 

### 애스펙트 지향 프로그래밍 (AOP)
* 객체 지향 기술의 한계와 단점을 극복하도록 도와주는 보조적인 프로그래밍 기술
* AOP를 자바 언어에 적용하는 기법
	* 1. 스프링과 같이 다이내믹 프록시 사용
	* 2. 자바 언어의 한계를 넘어서는 언어의 확장을 이용하는 방법
		* ex) AspectJ

### 포터블 서비스 추상화(PSA, Portable Service Abstraction)
* 일관성 있는 서비스 추상화 기술 > 스프링이 제공하는 대표적 기술
* 스프링은 엔터프라이즈 개발에 사용되는 다양한 기술에 대한 서비스 추상화 기능 제공
