### ISSUE TITLE
Chapter1. 오브젝트와 의존관계 (2)

### ISSUE THREAD

**Issue by yougahee** [FireInStove/toby-spring#2]
## 👑 스터디장
- 가희 (@yougahee)

### 1장 마무리
- 1.3 DAO의 확장 ~ 1.9 정리

## 🕧 스터디 일정
- 23/6/15 18시

**Comment by aimhigh53** [comment]
스터디

1.3 클래스의 분리
상속관계가 아닌 독립적인 클래스로 만드는 과정
-> DB커넥션과 관련된 부분을 서브 클래스가 아닌 별도의 클래스로 담은 뒤, 해당 class를 UserDao가 쓰도록
하지만 문제발생, UserDao의 코드가 SimpleConnectionMaker라는 특정 클래스에 종속되어 있기 떄문에 상속을 사용했을 때 처럼 UserDao 코드의 수정없이 DB 커넥션 생성 기능을 변경할 방법이 없어짐


인터페이스 도입
인터페이스는 어떤 일을 하겠다는 기능만을 정의해놓인거임,
그래서 Connection을 맺는 인터페이스 타입의 object라면 어떤 클래스로 만들어졌는지 상관없이 
makeConnection을 호출만하면 Connection타입의 object를 만들어서 리턴할 수 있겠다라는 기대 가능


관계설정&책임의 분리
UserDao가 어떤 connectionMaker 구현 클래스의 object를 이용하게 할지를 결정하는 것
즉 client에게 어떤 것을 사용할지에 대해 책임을 전가함

ConnectionMaker connectioMaker = new DconnectionMaker();
UserDao dao = new UserDao(connectionMaker);

원칙과 패턴

1. OCP: 클래스나 모듈은 확장에는 열려있어야 하고 변경에는 닫혀있어야한다.
2. SOLID
3. 높은 응집도, 낮은 결합도 
제어의 역전
IoC라는 약자로 많이 사용되는 제어의 역전(Inversion Of Control)이라는 용어가 있다. 스프링을 통해 많이 알려진 용어지만, 사실 제어의 역전이라는 개념은 상당히 오래 존재했다. 

오브젝트 팩토리 

테스트 책임의 분리

원래 UserDaoTest는 단순히 테스트를 위한 클래스였다. 그런데 어느샌가부터 어떤 구현 클래스를 사용하는지에 대한 책임이 있는 클라이언트가 되어버렸다. UserDaoTest는 온전히 테스트만 담당할 수 있도록 문제를 해결해보자.

팩토리의 등장
이 클래스의 역할은 객체의 생성 방법을 결정하고 그렇게 만들어진 오브젝트를 돌려줄 것이다. 이런 역할을 하는 클래스를 흔히 팩토리(factory) 라고 부른다.

1.4 제어의 역전이란(IOC)?
제어의 역전을 간단히 표현하면 프로그램 제어 흐름 구조가 뒤바뀌는 것이라고 할 수 있다.
일반적인 프로그램은 main 메소드에서 로직이 시작되며, 필요한 오브젝트를 만들고 오브젝트가 주체적으로 어떤 구현체를 사용하여 어떤 행위를 할 것인지에 대해 결정한다.

제어의 역전이 없는 상태(처음 만들었던 UserDao)에서는 모든 오브젝트가 능동적으로 자신이 사용할 클래스를 결정하고, 언제 어떻게 그 오브젝트를 만들지 스스로 관장한다. 모든 종류의 작업을 사용하는 쪽에서 제어하는 구조, 제어의 역전이란 이런 제어 흐름을 거꾸로 뒤집는 것이다.

제어의 역전의 특성
제어의 역전에서는 모든 오브젝트가 자신이 사용할 오브젝트를 스스로 선택하지 않는다. 당연히 생성하지도 않는다. 자신도 어떻게 만들어지고 어디서 사용되는지를 알 수 없다. 모든 제어권한을 자신이 아닌 다른 대상에게 위임하기 때문


1.5 제어의 역전(IoC)과 스프링 프레임워크
IoC는 스프링 프레임워크만의 기술이 아니다. 프레임워크가 꼭 필요한 개념도 아니다. 단순히 디자인 패턴에서도 발견할 수 있는 것처럼 상당히 폭 넓게 사용되는 프로그래밍 모델이다. IoC를 적용하여 설계가 깔끔해지고 유연성이 증가하며 확장성이 좋아진다면 IoC 스타일의 설계와 코드를 만들어서 사용하면 된다.


애플리케이션 컨텍스트의 동작 방식

![스크린샷 2023-06-14 오후 11 17 08](https://github.com/FireInStove/toby-spring/assets/37101427/ea5c4fb6-61b8-4a48-b3ff-e56c5d5d12a7)



IOC 용어정리

1. bean 
    1. 스프링이 직접 그 생성과 제어를 담당하는 오브젝트만을 빈이라고부름
2. bean factory
    1. 빈을 등록하고 생성하고 조회하고 돌려주고,,,
3. app context
    1. 빈 팩토리 기능 + 스프링이 제공하는 애플리케이션 지원 기능을 모두 포함해서 이야기하는 것
4. 컨테이너, ioc container
    1. IOC 방식으로 빈을 관리한다는 의미에서 애플리케이션 컨텍스트나 빈 팩토리를 컨테이너 또는 IOC 컨테이너라고도함.

싱글톤 레지스트리와 오브젝트 스코프

1.6.1. 싱글톤 레지스트리로서의 애플리케이션 컨텍스트
서버 애플리케이션과 싱글톤
싱글톤

- 어떤 클래스를 애플리케이션 내에서 제한된 인스턴스 개수, 주로 하나만 존재하도록 강제하는 패턴
- 하나만 만들어지는 클래스의 오브젝트는 애플리케이션 내에서 전역적으로 접근 가능
- 단일 오브젝트만 존재, 이를 애플리케이션 여러 곳에서 공유하는 경우 주로 사용

싱글톤의 한계
* private 생성자를 갖고 있기 때문에 상속할 수 없다.
* 테스트하기 힘들다.
* 서버환경에서는 싱글톤이 하나만 만들어지는 것을 보장하지 못한다.
* 싱글톤의 사용은 전역 상태를 만들 수 있기 때문에 바람직하지 못하다.


1.6.2. 싱글톤과 오브젝트의 상태

- 멀티스레드 환경에서 서비스 형태의 오브젝트로 사용되는 경우, 상태정보를 내부에 갖고 있지 않은 무상태(stateless)방식으로 만들어져야 함.
- 읽기전용의 값이라면 초기화 시점에서 인스턴스 변수에 저장해두고 공유하는 것은 아무 문제 없음.
- 상태가 없는 방식으로 클래스를 만드는 경우
	- 각 요청에 대한 정보, DB, 서버의 리소스로부터 생성한 정보는 파라미터와 로컬변수, 리턴 값 등을 이용하여 다룬다.
	- 메소드 파라미터나, 메소드 안에서 생성되는 로컬 변수는 매번 새로운 값을 저장할 독립적인 공간이 만들어지기 때문에 여러 스레드가 변수의 값을 덮어쓸 일이 없다.

1.6.3. 스프링 빈의 스코프

- 스프링 빈이 생성되고, 존재하고, 적용되는 범위
- 스프링에서 만들어지는 대부분의 빈은 싱글톤의 스코프를 갖는다.
- 싱글톤 외의 스코프
	-  프로토타입 스코프
		- 싱글톤과 달리 컨테이너에 빈을 요청할 때마다 매번 새로운 오브젝트를 만들어준다.
	- 요청 스코프
		- 웹을 통해 새로운 HTTP 요청이 생길 때마다 생성된다.
	- 세션 스코프
		- 웹의 세션과 유사하다.

**Comment by yougahee** [comment]
## 1.3 원칙과 패턴
- 개방 폐쇄 원칙
  - 확장에는 열려있어야 하고, 변경에는 닫혀있어야 한다.
  - 이 외에도 SOLID를 잘 기억해두자!
- SOLID
	- SRP : 단일책임 원칙
	- OCP : 개방폐쇄 원칙
	- LSP : 리스코프 치환 원칙
	- ISP : 인터페이스 분리 원칙
	- DIP : 의존관계 역전 원칙



## 1.4 제어의 역전(IoC)
- 팩토리
	- 객체의 생성 방법을 결정하고 그렇게 만들어진 오브젝트를 돌려준다.
	- 목적 : 오브젝트를 사용하는 쪽의 역할과 책임을 깔끔하게 분리하려는 목적

- 제어의 역전이란?
	- 프로그램의 제어 흐름 구조가 뒤바뀌는 것
	- 1) 원래의 흐름 : main() -> 사용할 오브젝트 결정 -> 오브젝트 생성 -> 사용 의 반복
		- 사용하는 쪽(구현 클래스)에서 자신이 어떤 오브젝트를 사용할 지 결정하고, 그 오브젝트를 필요한 시점에서 생성해두고, 각 메소드에서 이를 사용하는 구조
		- 즉, 사용하는 쪽에서 제어하는 구조
	- 2) 제어의 역전
		- 오브젝트가 자신이 사용할 오브젝트를 스스로 선택 및 생성하지 않음.
		- 오브젝트는 자신이 언제 사용될지 모름
		- **(코드 첨부 필요) 



## 1.5 스프링 IoC
- 스프링 빈 
	- 스프링 컨테이너가 생성과 관계설정, 사용 등을 제어해주는 제어의 역전이 적용된 오브젝트
- 빈 팩토리
	- 빈의 생성과 관계설정 같은 제어를 담당하는 IoC 오브젝트
	- 스프링 IoC를 담당하는 핵심 컨테이너
	- 빈을 등록, 생성, 조회 등 부가적인 빈 관리 기능 담당
- Application Context
	- 빈 팩토리를 확장(implements)한 IoC 컨테이너 
	- 빈 팩토리 기능 + 스프링이 제공하는 각종 부가 서비스를 추가로 제공
	- (용어) IoC 컨테이너 = 스프링 컨테이너 = 애플리케이션 컨텍스트
	- 애플리케이션 컨텍스트 implements ApplicationContext implements BeanFactory
	- 오브젝트가 만들어지는 방식, 시점과 전략 등을 다르게 가져갈 수 있고, 이에 부가적으로 자동생성, 오브젝트에 대한 후처리, 정보의 조합, 설정 방식의 다변화, 인터셉팅 등 다양한 기능 제공
- IoC 컨테이너
	- IoC 방식으로 빈을 관리한다는 의미

- 빈 등록 ~ 소멸까지
	- @Configuration 붙은 곳에서 @Bean 붙어있는 것들을 Application Context에 빈으로 등록한다.
	- getBean()으로 클라이언트가 해당 빈을 조회하면, 그때 빈이 생성되고, 생성된 애를 넘겨준다.


## 1.6 싱글톤 레지스트리와 오브젝트 스코프
- 스프링은 빈을 싱글톤으로 만든다.
- 그렇다면 왜? 싱글톤으로 만들까?
	- 스프링이 주로 적용되는 대상이 자바 엔터프라이즈 기술을 사용하는 서버환경이기 때문
	- 한꺼번에 많은 요청들을 받고, 요청마다 객체를 생성하고 삭제하는 과정이 이루어진다면 서버의 부하가 심해짐.(성능이 나오지 않음.)

- 싱글톤 패턴
	- 한계 및 단점
		- private 생성자를 가지고 있기 때문에 상속할 수 없다.
		- 테스트가 어렵거나 불가능하다.
		- 서버 환경에서 싱글톤이 하나만 만들어지는 것을 보장하지 못한다.
		- 
- 이러한 싱글톤 패턴의 한계로 인해, 스프링에서는 *싱글톤 레지스트리* 를 제공한다. 
	- 직접 싱글톤 형태의 오브젝트를 만들고 관리하는 기능
	- 평범한 자바 클래스를 싱글톤으로 활용하게 해준다는 점
	- public 생성자도 만들 수 있음.

- 스프링 빈의 스코프
	- 스프링이 관리하는 빈의 생성/존재/적용범위
	- 스프링 빈의 기본 스코프는 싱글톤
	- 프로토타입 스코프
		- 컨테이너에 빈을 요청할 때마다 매번 새로운 오브젝트를 만들어 줌
	- 요청 스코프
		- 새로운 HTTP 요청이 생길때마다 생성
	- 세션 스코프
		- 웹의 세션과 유사한 스코프 (?)
	- 10장에서 자세히

## 1.7 의존관계 주입(DI)
- DI 란 ?
	- 의존성 주입으로, 자신이 사용할 오브젝트에 대한 선택과 생성의 제어권은 외부로 넘기고, 자신은 수동으로 주입받은 오브젝트를 사용한다.
	- DI를 원하는 오브젝트는 먼저 자기 자신이 컨테이너가 관리하는 빈이 돼야 한다.
	- * DI 의 장점 *  
		- 결합도가 낮음
		- 다른 책임을 가진 사용 의존관계에 있는 대상이 바뀌거나 변경되더라도 자신은 영향을 받지 않음. 
		- 변경을 통한 다양한 확장 방법에는 자유롭다.
- 주입이란?
	- 외부에서 내부로 무엇인가를 넘겨줘야 하는 것
	- 자바에서 오브젝트에 무엇인가를 넣어준다 개념
	- 메소드를 실행하면서, 파라미터로 오브젝트의 레퍼런스를 전달해주는 방법
- 의존관계 검색
	- 의존관계를 맺는 방법이 외부로부터의 주입이 아닌, 스스로 검색을 이용하기 떄문에
	- 즉, 생성자 주입 시, 파라미터로 값을 주입하는 것이 아닌, DaoFactory를 통해 해당 메소드를 찾게 하는 것임으로 일종의 의존관계 검색이라고 볼 수 있다.
		- ex. getBean()
	- 특징
		- 검색하는 오브젝트는 자신이 스프링의 빈일 필요가 없다.


## 1.8 XML을 이용한 설정
- bean 생성 >> XML로 할 수 있는 방법
- 개발할 때 실제로 사용해본 적은 없어 많이 와닿지는 않음.
	- 이런 방법도 있구나~ 를 알 수 있었음.

**Comment by flyingtw** [comment]
1.3 DAO의 확장
- UserDao의 ConnectionMaker를 Class 끼리의 상속으로의 관리를 하다보니 다중 상속이 안되는 이유등이 발생한다. 
-> ConnectionMaker 라는 클래스를 만들어서 이 클래스를 각각의 N사등이 상속받도록 관심사를 분리했다.
-> 더 편리하게 구현하기 위해 interface를 사용

- interface를 사용해서 N사에서 구현한다 하더라도 UserDao의 생성자를 통해 오브젝트를 생성해야하는데 이때 DConnectionMaker라는 구체적인 클래스명을 통해 오브젝트를 생성해야한다
-> 클라이언트라는 클래스간의 관계를 이어주는 제 3자의 오브젝트가  UserDao가 오브젝트가 사용할 ConnectionMaker 오브젝트를 전달해주도록 만든다. 
-> test 클래스에서 생성자 파라미터로 NConnection 클래스의 Connection 오브젝트를 UserDao 클래스로 넘겨주고 UserDao는 클래스 타입, 구현 방식은 신경쓰지 않고 받은 connection 오브젝트를 통해 add 등의 메소드를 구현한다.

- 개방 폐쇄 원칙 
= 클래스나 모듈은 확장에는 열려 있어야 하고(interface와 생성자 파라미터를 통해 connection 에는 열려있는것 처럼), 변경에는 닫혀 있어야 한다.(add나 get 메서드 처럼 핵심적인 기능은 변경이 불가능하다)

- SOLID라는 객체지향 설계 원칙중 한개가 개방 폐쇄 원칙이다.

- 전략패턴
  - 컨텍스트(UserDao)를 사용하는 클라이언트(UserDaoTest)는 컨텍스트가 사용할 전략(ConnectionMaker를 구현한 DConnectionMaker)을 컨텐스트의 생성자를 통해 제공해주는것이 일반적인 전략패턴이다.

**Comment by tmfrl1552** [comment]
## 인터페이스의 도입
* 추상화 : 어떤 것들의 공통적인 성격을 뽑아내어 이를 따로 분리해내는 작업
* 인터페이스 
	* 자바가 추상화를 위해 제공하는 가장 유용한 도구
	* 어떤 일을 하겠다는 기능만 정의, 어떻게 하겠다는 구현 방법은 나타나 있지 않음
## 개방 폐쇄 원칙
* 개방 폐쇄 원칙 (open-close principle) : 클래스나 모듈은 확장에는 열려있어야 하고, 변경에는 닫혀있어야 함 
	* 높은 응집도 : 하나의 모듈, 클래스가 하나의 책임 또는 관심사에만 집중되어 있음
	* 낮은 결합도 : 하나의 변경이 발생할 때 마치 파문이 이는 것처럼 여타 모듈과 객체로 변경에 대한 요구가 전파되지 않는 상태
		* 높은 결합도 : 변경에 따른 작업량이 많아지고, 변경으로 인해 버그 발생 가능성이 높아짐
> 객체 지향 설계 원칙 (SOLID)
	* SRP(The Single Responsibility Principle) : 단일 책임 원칙
	* OCP(The Open Closed Principle) : 개방 폐쇄 원칙
	* LSP(The Liskov Substitution Principle) : 리스코프 치환 원칙
	* ISP(The Interface Segregation Principle) : 인터페이스 분리 원칙
	* DIP(The Dependency Inversion Principle) : 의존관계 역전 원칙
## 전략 패턴
* 전략 패턴 : 자신의 기능 맥락(context)에서, 필요에 따라 변경이 필요한 알고리즘을 인터페이스를 통해 통째로 외부로 분리시키고,
		   이를 구현한 구체적인 알고리즘 클래스를 필요에 따라 바꿔서 사용할 수 있게 하는 디자인 패턴
	* 알고리즘 : 독립적인 책임으로 분리가 가능한 기능
	* 컨텍스트를 사용하는 클라이언트는 컨텍스트가 사용할 전략을 컨텍스트의 생성자 등을 통해 제공해주는 게 일반적임

## 제어의 역전
* 제어의 역전(IoC, Inversion of Controll) : 프로그램의 제어의 흐름 구조가 뒤바뀌는 것
	* 모든 제어 권한을 자신이 아닌 다른 대상에게 위임
	* 템플릿 메소드 패턴은 '제어의 역전'이라는 개념을 활용해 문제를 해결하는 디자인 패턴
		* 제어권을 상위 템플릿 메소드에 넘기고, 자신은 필요할 때 호출되어 사용되도록 함
* 스프링의 IoC
	* 빈(bean) : 스프링이 제어권을 가지고 직접 만들고 관계를 부여하는 오브젝트
		* 스프링 빈 : 스프링 컨테이너가 생성과 관계설정, 사용 등을 제어해주는 제어의 역전이 적용된 오브젝트
	* 빈 팩토리(bean factory) : 빈의 생성과 관계설정 같은 제어를 담당하는 IoC 오브젝트
		* 빈 팩토리보다는 더 확장한 개념인 '애플리케이션 컨텍스트'를 주로 사용
		* 빈 팩토리 : 빈을 생성하고 관계를 설정하는 IoC의 기본 기능에 초점을 맞춘 것
		* 애플리케이션 컨텍스트 : 애플리케이션 전반에 걸쳐 모든 구성요소의 제어 작업을 담당하는 IoC 엔진이라는 의미가 좀 더 부각
	> * @configuration : 애플리케이션 컨텍스트 또는 빈 팩토리가 사용할 설정정보라는 표시
	> * @bean : 오브젝트 생성을 담당하는 IoC용 메소드라는 표시
* 스프링에서 애플리케이션 컨텍스트
	* IoC 컨테이너 라고 하기도 하고, 간단히 '스프링 컨테이너'라고 부르기도 한다. (또는 빈팩토리)
* 오브젝트 팩토리 사용과 비교했을 때, 애플리케이션 컨텍스트 사용시의 장점
	* 클라이언트는 구체적인 팩토리 클래스를 알 필요가 없다.
	* 애플리케이션 컨텍스트는 종합 IoC 서비스를 제공해준다.
	* 애플리케이션 컨텍스트는 빈을 검색하는 다양한 방법을 제공한다.
* 스프링 IoC의 용어 정리
	* 빈 (bean)
		* 빈 또는 빈 오브젝트는 스프링이 IoC 방식으로 관리하는 오브젝트
		* 스프링이 직접 그 생성과 제어를 담당하는 오브젝트만을 빈이라고 부른다.
	* 빈 팩토리 (bean factory)
		* 스프링의 IoC를 담당하는 핵심 컨테이너를 가리킨다.
		* 빈을 등록하고, 생성하고, 조회하고 돌려주고, 그 외에 부가적인 빈을 관리하는 기능을 담당
		* 보통은 빈 팩토리를 바로 사용하지 않고, 확장된 개념인 애플리케이션 컨텍스트 이용
	* 애플리케이션 컨텍스트 (application context)
		* 빈 팩토리를 확장한 IoC 컨테이너
		* 스프링이 제공하는 각종 부가 서비스를 추가로 제공
		* 애플리케이션 컨텍스트는 beanFactory를 상속
	* 설정 정보/설정 메타정보(configuration metadata)
		* 애플리케이션 컨텍스트 또는 빈 팩토리가 IoC를 적용하기 위해 사용하는 메타정보
		* IoC 컨테이너에 의해 관리되는 애플리케이션 오브젝트를 생성/구성 시 사용
	* 컨테이너 또는 IoC 컨테이너
		* IoC 방식으로 빈을 관리한다는 의미에서 애플리케이션 컨텍스트나 빈 팩토리를 컨테이너 또는 IoC 컨테이너라고 함
		* 애플리케이션 컨텍스트 오브젝트는 하나의 애플리케이션에서 보통 여러 개가 만들어져서 사용되는데, 이를 통틀어서 스프링 컨테이너라고 부름
	* 스프링 프레임워크
		* IoC 컨테이너, 애플리케이션 컨텍스트를 포함해서 스프링이 제공하는 모든 기능을 통틀어 말할 떄 주로 사용
> 오브젝트의 동일성과 동등성
	* 동일성 : 두 개의 오브젝트가 완전히 같은 동일한 오브젝트 >> == 연산자로 비교
	* 동등성 : 동등한 정보를 담고 있는 오브젝트 >> equals() 메소드로 비교

## 싱글톤 레지스트리로서의 애플리케이션 컨텍스트
* 애플리케이션 컨텍스트는 싱글톤을 저장하고 관리하는 싱글톤 레지스트리.
* 스프링은 별다른 설정을 하지 않으면 내부에서 생성하는 빈 오브젝트를 모두 싱글톤으로 생성.
	* 왜 스프링은 싱글톤으로 빈을 만들까 ? 
		* 스프링이 주로 적용되는 대상이 자바 엔터프라이즈 기술을 사용하는 서버환경이므로...
		* 요청이 올때마다 각 로직을 담당하는 오브젝트를 새로 생성할 경우, 부하가 걸리면 서버가 감당하기 힘듬
* 싱글톤 패턴의 한계
	* private 생성자를 갖고 있기 때문에 상속할 수 없다.
	* 싱글톤은 테스트하기가 힘들다.
	* 서버 환경에서는 싱글톤이 하나만 만들어지는 것을 보장하지 못한다.
	* 싱글톤의 사용은 전역 상태를 만들 수 있기 때문에 바람직하지 못하다.
* 싱글톤 레지스트리
	* 자바의 기본적인 싱글톤 패턴의 구현 방식은 여러 가지 단점 존재
	* 따라서, 스프링은 직접 싱글톤 형태의 오브젝트를 만들고 관리하는 기능 제공 -> 싱글톤 레지스트리
	* 스프링 컨테이너는 싱글톤을 생성하고, 관리하고, 공급하는 '싱글톤 관리 컨테이너'
	* 장점
		* 스태틱 메소드와 private 생성자를 사용해야 하는 비정상적인 클래스가 아니라 평범한 자바 클래스를 싱글톤으로 활용
		* 싱글톤 방식으로 사용될 애플리케이션 클래스라도 public 생성자 가질 수 있음.
	* 싱글톤이 멀티스레드 환경에서 서비스 형태의 오브젝트로 사용되는 경우, 상태정보를 내부에 갖고 있지 않은 '무상태 방식'으로 만들어져야 함.
		* 저장할 공간이 하나뿐이므로 서로 값을 덮어쓰고 자신이 저장하지 않은 값을 읽어올 수 있음.
* 빈 스코프 : 스프링이 관리하는 오브젝트, 즉 빈이 생성되고, 존재하고, 적용되는 범위
	* 스프링에서 만들어지는 대부분의 빈은 싱글톤 스코프
	* 스프링 컨테이너가 존재하는 동안 계속 유지
## 의존관계 주입(DI)
* 의존 오브젝트 : 런타임 시에 의존 관계를 맺는 대상
* 의존 관계 주입 : 구체적인 의존 오브젝트와 그것을 사용할 주체, 보통 클라이언트라고 부르는 오브젝트를 런타임 시에 연결해주는 작업
	* 생성자를 통한 의존관계 주입
	* 메소드를 이용한 의존관계 주입
		* 수정자 메소드를 이용한 주입
			* 용도 : 외부에서 오브젝트 내부의 에트리뷰트 값을 변경하기 위함	 
			* 항상 set으로 시작
			* 파라미터로 전달된 값을 보통 내부의 인스턴스 변수에 저장
		* 일반 메소드를 이용한 주입
			* 임의의 초기화 메소드를 이용하여 적절한 개수의 파라미터를 가진 여러개의 초기화 메소드 생성
<br>

### 💭 궁금증
* XML을 이용해서 빈 설정 하는 방식은 왜 사용하는 것이고, 장점이 무엇인지?
	* 고전적인 방법이며 요즘에는 잘 사용하지 않음
	* Spring boot에서는 main > @SpringBootApplication을 통해 설정클래스를 생성해줄 필요 없이 자동으로 설정 클래스 셋팅
	* 참고 링크
		* [XML vs Java Configuration](https://haeng-on.tistory.com/78)
		* [Spring에서 Spring Boot까지 Bean 설정 방식](https://kyun-s-world.gitbook.io/nowstart/spring/springframeworkcore/1-setting-bean)

**Comment by kyueun** [comment]
## DAO의 확장
클래스 사이의 불필요한 의존관계를 제거해야 함
    - 예시의 UserDao 내에 DB 커넥션을 만드는 코드가 있거나, ConnectionMaker 구현체를 지정하는 것은 불필요한 의존관계가 생기는 것
    - UserDao 안이 아닌, 외부에서 UserDao가 사용할 Connection Maker 구현체를 지정하여 주입해줘야 함

### 원칙과 패턴
객체지향 설계 원칙 (SOLID)
- 단일 책임 원칙 (SRP : SIngle Responsibility Principle)
- 개방 폐쇄 원칙 (OCP : Open-Closed Principle)
    - 클래스나 모듈은 확장에는 열려 있어야 하고 변경에는 닫혀 있어야 한다
    - 높은 응집도 : 하나의 모듈, 클래스가 하나의 책임, 관심사에만 집중
    - 낮은 결합도 : 책임, 관심사가 다른 오브젝트 또는 모듈 간에는 느슨하게 연결
- 리스코프 치환 원칙 (LSP : Liskov Substitution Principle)
- 인터페이스 분리 원칙 (ISP : Interface Segregation Principle)
- 의존관계 역전 원칙 (DIP : Dependency Inversion Principle)

전략 패턴 : 변경이 필요한 알고리즘은 인터페이스를 통해 외부로 분리, 그 구현체를 필요에 따라 바꿔 사용할 수 있도록 함

## 제어의 역전 (IoC)
### 팩토리
- 객체 생성 방법을 결정하고, 생성된 오브젝트를 돌려주는 것
- 오브젝트 생성자, 사용자 분리 목적

### 제어관계 역전
- 자신이 사용할 오브젝트를 직전 선택하지도, 생성하지도 않음
- 제어의 권한을 다른 대상에게 위임

## 스프링의 IoC
### 빈
스프링이 제어권을 가지고 있는 오브젝트

### 빈 팩토리
빈의 생성과 관계 설정 등의 제어를 담당하는 IoC 오브젝트
스프링 IoC 담당하는 핵심 컨테이너

### 애플리케이션 컨텍스트
일종의 빈 팩토리 (빈 팩토리를 확장한 IoC 컨테이너)
별도의 설정정보 가져와서 빈 생성, 관계 설정 등의 제어 작업 총괄하는 범용적인 IoC 엔진
빈 이름 기반으로 오브젝트 생성 -> 같은 타입의 오브젝트도 빈 이름을 다르게 해서 생성하는 방식, 구성을 다르게 할 수 있음

#### 장점
- 클라이언트는 구체적인 팩토리 클래스를 알 필요 없음
- 종합 IoC 서비스 제공
    - 오브젝트 생성 방식, 시점, 전략 등 설정 가능
    - 자동 생성, 오브젝트 후처리, 정보 조합, 설정 방식 다변화, 인터셉팅 등 기능 제공
    - 외부 시스템 연동을 컨테이너 차원에서 제공
- 빈을 찾는 다양한 방법 제공
    - 빈 이름 외 방법으로도 검색 가능

### 설정정보 / 설정 메타정보
애플리케이션 먼텍스트 또는 빈 팩토리가 IoC 적용하기 위해 사용하는 메타 정보

### 컨테이너 / IoC 컨테이너
애플리케이션 컨텍스트나 빈 팩토리를 컨테이너 / IoC 컨테이너라고도 함 : IoC 방식으로 빈을 관리한다

## 싱글톤 레지스트리와 오브젝트 스코프
스프링은 빈을 싱글톤으로 생성
-> 애플리케이션 컨텍스트는 싱글톤을 저장하고 관리하는 싱글톤 레지스트리이기도 함

요청이 올 때마다 매번 다른 객체를 생성하면 성능 이슈

#### 싱글톤 패턴
애플리케이션 내에서 어떤 클래스를 제한된 개수만큼 존재하게 강제
- 한계
    - 생성자를 private 으로 해서 클래스 밖에서 생성하지 못하도록 함 -> 상속이 불가능
    - 생성 방식이 제한적 -> 테스트 시 목 오브젝트 등으로 대체가 힘듦
    - 서버 환경에서 단일 클래스만 만들어진다고 보장할 수 없음
    - 스태틱 메소드를 통해 언제든 접근 가능 -> 전역 상태로 사용됨 -> 어디서든 자유롭게 접근
- 이런 한계들 때문에 안티 패턴으로 불리기도 함

### 싱글톤 레지스트리
싱글톤 패턴을 따르지 않는 평번한 자바 클래스도 싱글톤 방식으로 생성, 관리할 수 있도록 함

#### 주의점
- 무상태 방식으로 생성되어야 함
    - 여러 스레드에서 접근 가능 -> 여러 곳에서 Read/Write
    - 상태 정보를 내부에 갖고 있지 않은 무상태 방식으로 만들어져야 함

### 빈 스코프
빈이 생성, 존재, 적용되는 범위
스프링 빈은 대부분 싱글톤 스코프이지만, 경우에 따라 다를 수 있음
- 프로토타입 스코프 : 빈 요청할 때마다 새로운 오브젝트 반환
- 요청 스코프 : HTTP 요청마다 새로운 오브젝트 반환
- 세션 스코프 : 웹의 세션과 유사

### 의존관계
방향성이 존재 -> 누가 누구에게 의존하고 있음
의존대상이 변하면 의존하고 있는 쪽이 영향을 받음
인터페이스를 통한 의존관계를 제한 -> 변경에서 자유로움

의존 오브젝트 : 런타임 시에 의존관계를 맺음
- 각 오브젝트 간의 의존관계가 설계, 코드 상에는 드러나지 않음
- 런타임 시의 의존관계는 컨테이너나 팩토리 같은 제3자가 결정

## 의존관계 주입 (DI)
오브젝트 레퍼런스를 외부로부터 제공받고, 이를 통해 타 오브젝트들과 관계를 만듦
DI 컨테이너에 의해 런타임 시 오브젝트 레퍼런스를 전달받는 과정

### 메소드를 이용한 의존관계 주입
- 수정자 메소드(setter) 이용
- 일반 메소드 이용

### 의존관계 검색(DL)
스스로 검색해서 의존관계를 맺는 방법
- ex) getBean()
코드 안에 팩토리 클래스, 스프링 API가 나타남 (이것도 결국 성격이 다른 오브젝트에 의존하는 것)

### XML을 이용한 설정
자바 클래스를 사용하지 않는 의존관계 설정 정보 관리 방법 중 하나
- `<beans>` == @Configuration : 여러 빈을 담을 수 있음
- `<bean>` == @Bean
- `<property>` : 주입하는 오브젝트

**Comment by yougahee** [comment]
## 6/15(목) 스터디 내용

#### 왜 @Autowired(필드 주입) 를 사용하지 않고, 생성자 주입 방식(ex. @@RequiredArgsConstructor) 을 권장할까??

#### IoC 가 왜 필요한가?
