### ISSUE TITLE
Chapter 2 TEST

### ISSUE THREAD

**Issue by aimhigh53** [FireInStove/toby-spring#3]
## 👑 스터디장
- 인석 (@aimhigh53 )

### 2장 3절까지
- 2 ~ 2.3

## 🕧 스터디 일정
- 23/6/22 18시

**Comment by yougahee** [comment]
# ✏️ 정리

## 스프링에서의 테스트!
- 스프링에서 테스트를 짜지 않는 것은 스프링이 지닌 가치의 절반을 포기하는 셈
- 테스트는 가능하면 작은 단위로 쪼개서 해야한다. (=단위테스트)
- 다른 코드들은 신경 쓰지 않고, 참여하지 않고 테스트가 동작할 수 있으면 좋다.

## 좋은 테스트
1. 코드에 변경사항이 없다면, 테스트는 항상 동일한 결과를 내야한다. 
    - 테스트를 마치고 난 후, 테스트가 등록한 정보를 삭제하여 테스트를 수행하기 이전 상태로 만들어주기 
2. 테스트코드를 만들지 않는 것도 위험한 일이지만, 성의없는 테스트로 인해 성공하게 만드는 것은 더 위험하다.
3. 한가지 테스트 메소드에 한가지 검증 목적만 충실하는 것이 좋다.


## UserDaoTest 개선
- 테스트를 작성할 때 성공 케이스, 실패 케이스를 작성해줘야 한다.
- 이전까지 사용했던 Main 테스트를 벗어나 JUnit 테스트를 해보자
	- JUnit은 프레임워크다
	- public으로 선언하고 @Test를 붙여줘야 한다.

## JUnit : 테스팅 프레임워크
- @Before , @After 메소드 실행 전/후 에 실행됨.
- 각 테스트 메소드를 실행할 때마다 테스트 클래스의 오브젝트를 새로 만듦
   - WHY??
   		- 각 테스트가 서로 영향을 주지 않고 독립적으로 실행하는 것을 확실히 보장한다.


## Fixture
- 테스트를 수행하는데 필요한 정보 또는 오브젝트
- 대부분 여러 test에 반복적으로 사용하기에, @Before 메소드를 이용해 생성하면 좋음.

## 개발자가 테스트를 만들 때 자주하는 실수
1. 성공하는 Test만 만들기
2. 테스트도 리팩토링 대상이다. 

## TEST는 이렇게 작성하면 좋다!
- negative test를 먼저 만들자. (실패하는 테스트)
- 애플리케이션코드보다 테스트 코드를 먼저 작성하자.(TDD)
- 조건 / 행위 / 결과 순으로 작성

## TDD(Test Driven Development)
- 테스트 주도 개발
- 실패한 테스트를 성공시키기 위한 목적이 아닌 코드는 만들지 않는다(=> 기본원칙)
- Test를 작성하는 시간과 애플리케이션 코드를 작성하는 시간의 간격이 짧아진다 
- 테스트 작성, 성공하는 코드를 만드는 작업 주기를 짧게 가져가도록 권장


</br>

## ❓ [궁금!] @ BeforeEach vs @BeforeAll 의 차이점
1) @ BeforeEach
- 각 테스트가 시작하기전 해당 애노테이션이 붙어있는 메소드가 실행된다.
- 꼭 static, private이 아닌 public으로.
- 테스트 결과
```
before
1 // 메소드 1
before
2 // 메소드 2
before
3 // 메소드 3
```

2) @BeforeAll
- 클래스에서 전체 테스트 중 처음에 한번 실행된다.
- 꼭 static 메소드로 작성을 해줘야 한다.
- static 메소드로 정의되기 때문에 한번만 실행되도, 모든 테스트에서 동일한 값으로 사용될 수 있다. 
``` 
    public static int ha;

    @BeforeAll
    public static void init() {
        testObjects = new HashSet<>();
        ha = 0;
        System.out.println("before, ha : " + ha);
    }

    ... (중략) ....


       // 실행 결과
         before
         1
         2
         3

 ``` 


- 단, 이전 테스트에서 before에서 셋팅한 값을 수정한다면, 값이 변함을 주의하자.

```
// before에서 정의한 ha = 0 (전역에 선언) 가 테스트를 지나면서 변경되는 것을 확인할 수 있음.
before, ha : 0
1ha : 1
2ha : 2
3ha : 3
```

**Comment by aimhigh53** [comment]
2.1

테스트란 결국 내가 예상하고 의도했던 대로 코드가 정확히 동작하는지를 확인해서, 만든 코드를 확신할 수 있게 해주는 작업

웹을 통한 DAO 테스트의 문제점
-> 요약하자면,, 모든 서비스 레이어를 만들어야하고,  이후에 테스트가 가능하기때문에 비효율적임. 어디서 문제가 발생하는지에 대해 확인을 해보려고하면 좀 빡셈

작은단위의 테스트
테스트하고자 하는 대상이 명확하다면 그 대상에 대해서만.. 
근데 과정이나 대상이 크다면 확인하기 복잡함. 그래서 관심사 분리 원리를 사용한다

단위테스트
"단위"자체가 정해진건 아님, 크게는 사용자 관리 기능과 같은,, 메소드 하나만 가지고 하나의 단위로 볼 수도 있음. 
—> 실무에선 보통 어떤걸 단위로 보나? 타팀은 어떻게,,?

단위테스트를 하는 이유?
개발자가 설계하고 만든 코드가 원래 의도한 대로 동작하는지를 개발자 스스로 빨리 확인받기 위해서

UserDaoTest 문제점

수동 확인 작업의 번거로움

실행 작업의 번거로움

JUnit
JUnit 프레임워크를 이용해 앞에서 만든 테스트.. 그 안에 JUnitCore 클래스의 main 메소드를 호출해주는 간단한 코드를 넣어주면 된다. 메소드 파라미터에는 @Test 테스트 메소드를 가진 클래스의 이름을 넣어줌

2.3
* 테스트 결과의 일관성
* 동일한 결과를 보장하는 테스트
* 포괄적 테스트
    * 한가지 결과만 검증하고 마는 것은 상당히 위험
        * 고장난 시계 두번..
    * 테스트 코드를 수정한 뒤에도 잊지말고 테스트를 다시실행, 코드의 수정 후에는 그 수정에 영향을 받을 만한 테스트를 실행하는 것을 잊지말기로.. 
* 네거티브 테스트를 먼저 만들라
* 예외적인 상황을 빠뜨리지 않는 꼼꼼한 개발

TDD인트로
* 기존 코드가 없는데 어떻게 테스트를..?
    * 만들어진 코드를 보고 이것을 어떻게 테스트할까라고 생각하면서 만드는 것이 아닌, 추가하고 싶은 기능을 코드로 표현하려고 했기 때문 
* 조건/행위/결과 순으로 작성

TDD
*

**Comment by kyueun** [comment]
## UserDaoTest 다시 보기
테스트의 관심이 다르다면, 테스트할 대상을 분리하고 집중해서 접근

### 단위 테스트
작은 단위의 코드에 대해 테스트를 수행한 것
- 단위는 작을수록 좋다
- 테스트는 자동화, 빠르게 실행 가능해야 함

## UserDaoTest 개선
코드에 큰 변화가 일어나더라도, 테스트 수행으로 정상 동작 확인 가능

## 개발자를 위한 테스팅 프레임워크 JUnit
### Junit
테스팅 프레임워크

단위 테스트는 항상 일관성 있는 결과가 보장되어야 함
테스트는 포괄적으로 작성해야 함
- 문제가 있는 코드인데도 테스트가 성공하게 만드는 것은 위험
- 충분한 검증이 필요

### 테스트 주도 개발
테스트 코드를 먼저 만들고, 테스트를 성공하게 해주는 코드를 작성
테스트 작성 ~ 성공 코드 작성 작업의 주기를 가능한 짧게 가져가도록 권장

### 테스트 코드 개선
중복되는 코드는 `@Before`, `@After` 등 어노테이션을 setUp() 등의 메소드에 추가해서 분리 가능

### 픽스쳐
테스트를 수행하는 데 필요한 정보, 오브젝트

## 스프링 테스트 적용
빈이 많아질수록 어플리케이션 컨텍스트 생성 시간이 오래 소요 -> 생성 방식을 정해주어야 함

JUnit은 기본적으로 테스트 메소드 실행할 때마다 새로운 테스트 오브젝트를 생성
단, 어플리케이션 컨텍스트처럼 생성에 시간과 자원이 많이 소모되는 경우, 테스트 전체가 공유하는 오브젝트 생성하기도 함
- `@RunWith`, `@ContextConfiguration` 어노테이션으로 어플리케이션 컨텍스트 관리 가능

### Autowired
변수 타입과 일치하는 빈을 찾아 주입 ( 생성자, 수정자 등 메소드 없이도 주입 가능 )

### DI와 테스트
구현체가 아닌 인터페이스를 두고 DI 적용해야 함
- 소프트웨어 개발에서 절대 바뀌지 않는 것은 없음
- 구현 방식이 바뀌지 않더라도, 인터페이스를 두면 다른 차원의 서비스 기능을 도입할 수 있음
- 빠르게 동작하는 테스트 코드를 위해, 범위를 가능한 한 작은 단위로 지정해야 함

## 개인적으로 궁금한 점
각 팀마다 테스트 코드는 어느정도로 작성하는지?
작성하는 시점은 언제인지? ( 개발 전, 중간, 완료 이후 )
단위 테스트 외에 통합 테스트 코드도 작성하는지?
커버리지를 따로 측정하는지? 측정한다면 어떤 기준?
픽스쳐 관리는 어떻게 하는지?
테스트 코드 작성을 위해 사용하는 라이브러리 등이 있는지?

**Comment by tmfrl1552** [comment]
# 2. 테스트
### 작은 단위의 테스트
* 단위 테스트(unit test) : 작은 단위의 코드에 대해 테스트를 수행
* 테스트는 작은 단위로 쪼개서 그 대상에만 집중해야함
	* 관심사의 분리 원리 적용
	* 한꺼번에 너무 많은 것을 몰아서 테스트하면, 테스트 수행 과정도 복잡해지고 오류의 정확한 원인을 찾기 힘들어짐.
* 단위 테스트를 하는 이유
	* 개발자가 설계하고 만든 코드가 원래 의도한 대로 동작하는지를 개발자 스스로 빨리 확인받기 위함
	* 개발자 테스트 또는 프로그래머스 테스트라고 부르기도 함.

### 자동 수행 테스트 코드
* 장점 : 자주 반복 할 수 있음
	* 번거로운 작업이 없고, 테스트들 빠르게 실행할 수 있으므로 언제든 코드를 수정하고 나서 테스트를 진행 가능

### 지속적인 개선과 점진적인 개발을 위한 테스트
* 테스트를 이용하면, 새로운 기능도 기대한 대로 동작하는지 확인할 수 있을 뿐만 아니라,
  기존에 만들어뒀던 기능들이 새로운 기능을 추가하느라 수정한 코드에 영향을 받지 않고 여전히 잘 동작하는지 확인 가능

### JUnit 테스트로 전환
* JUnit : 자바 테스팅 프레임워크 
* 테스트 메소드
	* 1. 메소드는 public으로 선언
	* 2. 메소드에 @Test 어노테이션 붙여주기
* assertThat()을 이용해 검증을 했을 때 기대한 결과가 아니면 AssertionError를 던짐.
	* 테스트는 더 이상 진행되지 않고, 실패를 알림
* 동일한 결과를 보장하는 테스트
	* 단위 테스트는 항상 일관성 있는 결과가 보장돼야 함.
	* DB에 남아있는 데이터와 같은 외부 환경에 영향을 받지 말아야 하는 것은 물론이고, 테스트를 실행하는 순서를 바꿔도 동일한 결과 보장 필요
	> 멱등성 있는 테스트
	* JUnit은 특정한 테스트 메소드의 실행 순서를 보장해주지 않음
		* 모든 테스트는 실행 순서에 상관 없이 독립적으로 항상 동일한 결과 도출 필요 
* 포괄적인 테스트
	* 테스트를 작성할 때, 부정적인 케이스를 먼저 만드는 습관을 들이자.
		* 발생할 수 있는 다양한 상황과 입력 값을 고려하는 포괄적인 테스트
### 테스트 주도 개발(TDD)
* 만들고자 하는 기능의 내용을 담고 있으면서 만들어진 코드를 검증도 해줄 수 있도록 테스트 코드를 먼저 만들고,
  테스트를 성공하게 해주는 코드를 작성하는 방식으로 개발하는 방법
* 테스트 우선 개발이라고도 부름
	* 테스트를 먼저 작성하므로.
* TDD 기본 원칙
	* "실패한 테스트를 성공시키기 위한 목적이 아닌 코드는 만들지 않는다."
* 코드를 만들어 테스트를 실행하는 그 사이의 간격이 매우 짧음.
	* 개발한 코드의 오류를 빨리 발견할 수 있음
#### 테스트 코드 개선
* @Before
	* 테스트 메소드(@Test)를 실행하기 전 먼저 실행시켜주는 기능
* Junit의 테스트 수행 방식
	* 1. 테스트 클래스에서 @Test가 붙은 public이고 void 형이며 파라미터가 없는 테스트를 모두 찾는다.
	* 2. 테스트 클래스의 오브젝트를 하나 만든다.
	* 3. @Before가 붙은 메소드가 있으면 실행한다.
	* 4. @Test가 붙은 메소드를 하나 호출하고 테스트 결과를 저장해둔다.
	* 5. @After가 붙은 메소드가 있으면 실행한다.
	* 6. 나머지 테스트 메소드에 대해 2 ~ 5번을 반복한다.
	* 7. 모든 테스트의 결과를 종합해서 돌려준다.
* 테스트 메소드를 실행할 때 마다 테스트 클래스의 오브젝트는 새로 만들어짐
	* ex) 테스트 메소드가 2개라면, 테스트가 실행되는 중에 JUnit은 이 클래스의 오브젝트를 두 번 생성
	* 새로 만드는 이유 : 각 테스트가 서로에게 영향을 주지 않고 독립적으로 실행됨을 보장
* 픽스처 (Fixture)
	* 픽스처 : 테스트를 수행하는 데 필요한 정보나 오브젝트
	* 일반적으로 여러 테스트에서 반복적으로 사용되므로 @Before 메소드 이용하면 편리
		* ex) 이 책의 예시에서는 userDao, add() 메소드에 전달하는 User 오브젝트

## 추가 참고사항
### 1️⃣ Junit 버전에 따른 @Before/@BeforeClass 사용 차이
* 1. Junit4
	* @Before : 각 테스트 전에 먼저 실행
	* @BeforeClass : 모든 테스트를 실행하기 전에 한 번만 실행
* 2. Junit5
	* @BeforeEach
		* Junit4의 @Before와 동일한 기능
		* 각 테스트 전 먼저 실행
			> * return type : 반드시 void
			   * 접근 제한자로 private 사용 금지
			   * static 선언 금지
	* @BeforeAll
		* Junit4d의 @BeforeClass와 동일한 기능
		* 모든 테스트 실행 전 한 번 실행
			> * return type : 반드시 void
			   * 접근 제한자로 private 사용 금지
			   * static 선언
==> jnit4 > jnit5 로 버전업 되면서 네이밍만 변경됨 느낌..


### 2️⃣ assertThat의 두가지
```
1. Junit의 assertThat
	* Junit : 자바에 구축된 자동화 테스트가 가능한 프레임워크 
2. assertj의 assertThat
	* AssertJ : 자바 테스트에서 유창하고 풀부한 assertions를 작성하는데 사용되는 오픈소스 라이브러리
```

* ==> **AssertJ 를 더 선호**함
	* 배우기가 쉽다
	* 사용하기가 쉽다
	* IDE에서 자동완성 지원
	* 코드가 더 직관적이다

* 참고 링크 : [Junit VS AssertJ](https://kkoon9.tistory.com/135?category=1035506)

**Comment by flyingtw** [comment]
### 2.1 UserDaoTest 다시보기

- main을 통한 테스트는 서비스 클래스, 컨트롤러, JSP 뷰 등 모든 레이어의 기능을 다 만들어야 테스트가 가능하다  -> 단위별로 테스트하기가 쉽지않음
- 오류의 원인을 파악하기 위해 테스트는 가능한 작은 단위로 쪼개서 집중해서 할 수 있어야 한다.(관심사의 분리도 적용)
- 단위 테스트 : 작은 단위의 코드에 대해 테스트를 수행
- 테스트의 장점은 자주 반복할 수 있다는점!

### 2.2 UserDaoTest 개선
- 테스트의 결과는 틀린결과와 다른결과로 나눌 수 있다.(에러, 실패의 개념)
- 만들거진 코드의 기능을 모두 점검할 수 있는 포괄적인 테스트 
- Java의 대표적인 테스트 지원 도구는 JUnit 프레임워크이다. (제어의 역전 IC 를 활용한다는 뜻)
    - (프레임워크에서 동작하는 코드는 main() 메소드도 필요없고 오브젝트를 만들어서 실행시키는 코드를 만들 필요도 없다.)
- JUnit 프레임워크가 요구하는 조건 2가지
    - 메소드가 public으로 선언되어야 한다. 
    - 메소드에 @Test 라는 어노테이션을 추가한다.
- assertThat
    - if문의 맞냐? 라는 검증 (is..?)
    - 테스트를 실패한 원인, 위치를 띄워줌

### 2.3 개발자를 위한 테스팅 프레임워크 JUnit
- 테스트 없이는 스프링의 의미도 없다. (심지어 스프링 자체도 JUnit으로 테스트 하면서 개발됨 오오..)
- IDE 에서 제공하는 테스트 방식을 사용할 수도 있ㄷ지만 메이븐과 같은 빌드 툴을 통해서도 테스트를 진행 할 수 있다.
- DB를 통한 테스트를 하기 전에 전체 데이터를 삭제해주는 기능을 추가
- 단위테스트는 코드가 바뀌지 않는다면 매번 실행할 때마다 동일한 테스트 결과를 얻어야 한다.
- 테스트를 하기 전에 모든 데이터를 초기화 하는 방식이 좋다.
- 테스트 메소드는 한번에 한가지 기능만 검증하는게 좋다.
- 생성자를 통해 User 객체를 한번에 만듬.. (진작에 이러지)
- Junit은 테스트 메소드의 실행 순서를 보장해 주지 않는다.
    - 모든 테스트는 실행 순서과 상관없이 독립적으로 항상 동일한 결과를 낼 수 있도록 해야한다.
- null이다와 id값이 없다고 예외를 던지는것은 다른것임.
- 예외 클래스 이미 있는것 사용
- 특정 예외가 터졌을때 성공임을 확인
- @Test 어노테이션의 expected 엘리먼트는 그 테스트에서 해당 class(exception 클래스)가 터지면 ok임)
- 성공하는 테스트만 골라서 하면 안된다!
    - 스프링 창시자인 로드존슨은 항상 네거티브 테스트를 먼저 만들라 라고 했다.
- 추가하고 싶은 기능을 테스트로 표현
- 테스트가 성공하면 그 순간 코드 구현과 테스트라는 두가지 작업이 해결된다.
- 테스트 주도 개발 (TDD)
    - 테스트코드를 먼저 만들고 이후에 테스트를 성공하게 해주는 코드를 작성하는 방법
- 테스트는 머릿속에서 예외상황을 좀 더 구체적으로 표현하는 수단이다.
- 테스트 코드는 생각보다 작성하는데 오래 걸리지 않는다.
- @Before
    - 테스트 시작 전 반복적인 메소드
    - dao 같은걸 인스턴스 변수(전역변수)에 등록해주는 역할도 한다.
- Junit 테스트는 7단계를 거친다. 
- 각 테스트 마다 주고받을 객체나 변수가 있다면 인스턴스 변수에 저장을 해놔야 한다.
- 테스트는 실행할때마다 각 테스트의 독립적인 실행을 보장하기 위해 각각의 오브젝트를 생성한다.
- 픽스쳐
    - 테스트를 수행하는데 필요한 정보나 오브젝트
    - @Before로 만들어두는게 편하다.
