### ISSUE TITLE
Chapter2. 테스트 ~ Chapter3. 템플릿

### ISSUE THREAD

**Issue by kyueun** [FireInStove/toby-spring#4]
## 👑 스터디장
- 규은 (@kyueun )

### 3장 2절까지
- 2.4 ~ 3.2

## 🕧 스터디 일정
- 23/6/29 14시 (미진행)
- 23/07/06 09시

**Comment by kyueun** [comment]
## 스프링 테스트 적용
빈이 많아질수록 어플리케이션 컨텍스트 생성 시간이 오래 소요 -> 생성 방식을 정해주어야 함
JUnit은 기본적으로 테스트 메소드 실행할 때마다 새로운 테스트 오브젝트를 생성
- 단, 어플리케이션 컨텍스트처럼 생성에 시간과 자원이 많이 소모되는 경우, 테스트 전체가 공유하는 오브젝트 생성하기도 함
`@RunWith`, `@ContextConfiguration` 어노테이션으로 어플리케이션 컨텍스트 관리 가능

### Autowired
변수 타입과 일치하는 빈을 찾아 주입 ( 생성자, 수정자 등 메소드 없이도 주입 가능 )

### DI와 테스트
구현체가 아닌 인터페이스를 두고 DI 적용해야 함
- 소프트웨어 개발에서 절대 바뀌지 않는 것은 없음
- 구현 방식이 바뀌지 않더라도, 인터페이스를 두면 다른 차원의 서비스 기능을 도입할 수 있음
- 빠르게 동작하는 테스트 코드를 위해, 범위를 가능한 한 작은 단위로 지정해야 함

## 학습 테스트로 배우는 스프링
프레임워크나 라이브러리 등에 대해 테스트를 작성해 방법을 익힘

### 버그 테스트
코드에 오류가 있을 때 오류를 드러낼 수 있는 테스트
실패하는 테스트 작성 -> 코드 수정 -> 테스트 성공 확인

# 템플릿
개방 폐쇄 원칙(OCP) : 변화의 특성이 다른 부분을 구분해서 독립적으로 변경될 수 있도록 함

## 다시 보는 초난감 DAO
기능 수행 중 예외가 발생해도 리소스를 반환해야 함
-> try/catch/finally 구문 권장
- finally에서 리소스 반환
- 리소스 반환 시, null 체크 후 반환

## 변하는 것과 변하지 않는 것
변하지 않지만 중복되는 코드 / 로직에 따라 자주 변하는 코드 -> 분리 필요
먼저 변하는 성격이 다른 부분 찾고, 분리
- 메소드로 추출
- 템플릿 메소드 패턴 적용
    - 템플릿 메소드 패턴 : 상속을 통해 기능을 확장해서 사용
    - 변하지 않는 부분은 슈퍼클래스에 구현, 변하는 부분은 추상 메소드로 정의 후 서브 클래스에서 오버라이딩
- 전략 패턴 적용
    - 전략 패턴 : 오브젝트를 분리, 클래스 레벨에서 인터페이스를 통해서만 의존
    -  일정한 구조를 갖고 동작하다가, 특정 확장 기능은 독립된 전략 클래스에 위임
    - ```java
        public interface Movable {
            public void move();
        }

        public class Train implements Movable{
            public void move(){
                System.out.println("선로를 통해 이동");
            }
        }        

        public class Bus implements Movable{
            public void move(){
                System.out.println("도로를 통해 이동");
            }
        }


        public class Client {
            public static void main(String args[]){
                Movable train = new Train();
                Movable bus = new Bus();

                train.move();
                bus.move();
            }
        }
- DI 적용을 위한 클라이언트/컨텍스트 분리
    - 클라이언트가 전략 선택, 오브젝트 생성, 컨텍스트에 전달
    - 컨텍스트는 전달받은 오브젝트 사용

### 마이크로 DI
DI의 장점을 단순화, IoC 컨테이너 도움 없이 코드 내에서 적용한 경우
- (스프링 bean 같은 DI 말고, 코드 상에 DI 방식을 사용한 것)

**Comment by aimhigh53** [comment]
2.4 스프링 테스트 적용
* 테스트는 가능한 한 독립적으로 매번 새로운 오브젝트를 사용하는 것이 원칙
    * 하지만 애플리케이션 컨텍스트 처럼 생성에 많은 시간과 자원이 소모되는 경우에는 테스트 전체가 공유하는 오브젝트를 만듬
    * 따라서 애플리케이션 컨텍스트는 한 번만 만들고 여러 테스트가 공유해서 사용해도 됨
* JUnit 사용, 
    * @Runwith: Junit 프레임워크의 테스트 실행 방법을 확장할 때 사용하는 @
        * SpringJUnit4classRunner라는 Junit용 테스트 컨텍스트 프레임워크 확장 클래스를 지정해주면 Junit이 테스트를 진행하는 중에 테스트가 사용할 애플리케이션 컨텍스트를 만들고 관리
    * @ContextConfiguration은 자동으로 만들어줄 애플리케이션 컨텍스트의 설정 파일 위치를 지정한 것
* 테스트 메소드는 context를 공유함, 반면 특정 오브젝트는 매번 주소값이 다름, Junit의 기능인데, 테스트 메소드를 실행할 때마다 새로운 테스트 오브젝트를 만들기 때문,
* context 변수에 어떻게 애플리케이션 context가 들어가나?
    * Junit확장기능, 테스트가 실행되기 전에 딱 한번만 애플리케이션 컨텍스트를 만들어두고, 테스트 오브젝트가 만들어질 때마다 특별한 방법을 이용해 애플리케이션 컨텍스트 자신을 테스트 오브젝트의 특정 필드를 주입해줌(DI랑 비슷) 
* @autowired
    * 변수타입과 일치하는 컨텍스트 내 빈을 찾는다
* DI와 테스트
    * 왜 Interface를 써서 굳이굳이 DI를 해줘야하는가
        * 1. 시간과 비용 부담 줄여줌, 개발자 편의(내 표현)
        * 2. 다른차원의 서비스 기능 도입
        * 3. 테스트
    * @DirtiesContext라는 애노테이션추가
        * 애플리케이션 컨텍스트 공유는 허용하지 않음
        * 매번 새로운 애플리케이션 컨텍스트를 만들어 다음 테스트가 사영히게 해줌


3.1 ~ 3.2

3.1은딱히..
try/catch/finally
   * finally에서 close()로 리소스반환
   * t/c 에서 해야 중간 과정에서 에러처리하면서 쓸 수 있음

3.2

**Comment by yougahee** [comment]
## ✏️ 4주차 (테스트 ~ 템플릿) 정리


## 애플리케이션 컨텍스트 관리
- 모든 테스트마다 Application Context를 생성하는 것은 비효율적
	- AC는 싱글톤 패턴으로 한번 만들어지면 잘 변경되지 않음.
- @RunWith 
	- JUnit 프레임워크의 테스트 실행 방법을 확장할 때 사용하는 애노테이션
- @ContextConfiguration
	- 테스트 컨텍스트가 자동으로 만들어줄 애플리케이션 컨텍스트의 위치 지정
	- 여러 개의 테스트 클래스가 있을 때, 모두 같은 설정파일을 바라본다면 동일한 AC임.
- @Autowired
	- 스프링 DI에 사용되는 특별한 애노테이션
	- 변수 타입과 일치하는 빈을 찾아 주입을 해줌.
- @DirtiesContext
	- AC의 구성이나 상태를 변경한다는 것을 테스트 컨텍스트 프레임워크에 알려준다.
	- 이 애노테이션이 붙은 테스트 클래스에는 AC를 공유하지 않는다는 뜻
	- 메소드에도 사용할 수 있다.
- 참고)
	- AC는 초기화할 때 자기 자신도 빈으로 등록함.

## 인터페이스를 두고 DI를 해야하는 이유
1. SW에서 바뀌지 않는 것은 없다.
2. 다른 차원의 서비스 기능을 도입할 수 있다. (이런 기법을 사용하여 AOP라는 기술로 만들어주기도 한다.)
3. 테스트 

## 학습 테스트
- 자신이 만들지 않은 framework나 다른 개발팀에서 만들어서 제공한 라이브러리에 대해 테스트
- 목적 : 사용법 익히기
- 장점 
	- 다양한 조건에 따른 기능을 손쉽게 확인해볼 수 있다. 
	- 학습 테스트 코드를 개발 중에 참고할 수 있다. 
	- 프레임워크나 제품을 업그레이드할 때 호환성 검증을 도와준다. 
	- 테스트 작성에 대한 좋은 훈련이 된다.
	- 새로운 기술을 공부하는 과정이 즐거워진다.


## 버그 테스트 
- 코드에 오류가 있을 때, 그 오류를 가장 잘 드러내줄 수 있는 테스트
- 일단 실패하도록 만들기(버그가 원인이기 때문)
- 장점
	- 테스트 완성도 높여줌
	- 버그 내용을 명확하게 분석
	- 기술적인 문제를 해결하는데 도움


## 분리와 재사용을 위한 디자인 패턴
- 변하는 로직과 변하지 않고 공통으로 사용하는 로직의 분리가 필요하다.
	- ex) connection 을 열고 꼭 닫아주는 행위(connection pool 관리)
	- 만약, DB 쿼리를 사용하는 모든 메소드에 connection을 열고 닫아줘야 하는 코드를 직접 넣어줘야 한다면..?
		- 코드 복잡도 및 개발자의 수동 작업/실수 등이 빈번하게 나타날 것
- 그렇기에, 3장에서는 메소드를 추출하여 공통되는 로직을 함수 호출을 통해 해결

## Template 메소드 패턴
- 상속을 통해 기능을 확장
- 변하지 않은 부분 -> 슈퍼 클래스 의 default method 나 구현해놓기 
- 변경이 필요한 부분 -> 추상 메소드 
- 단점 
	- 확장구조가 클래스 설계 시점에 고정되어 버림
	- 관계에 대한 유연성이 떨어짐


## 전략 패턴
- 개방 폐쇄 원칙을 잘 지키면서도 템플릿 메소드 패턴보다 유연하고 확장성이 뛰어남
- interface를 통해 의존하도록 하는 패턴
- DI가 전략패턴의 장점을 활용할 수 있도록 만든 구조
- 쿼리가 전략패턴에서의 핵심임

**Comment by tmfrl1552** [comment]
### 테스트를 위한 애플리케이션 컨텍스트 관리
* @Authwired : 스프링 컨텍스트에 의해 자동으로 값 주입
	* 테스트 컨텍스트 프레임워크는 변수 타입과 일치하는 컨텍스트 내의 빈을 찾는다.
	* 타입이 일치하는 빈이 있으면 인스턴스 변수에 주입
	* 메소드가 없어도 주입 가능
	* 별도의 DI 설정 없이 필드의 타입정보를 이용헤 빈을 자동으로 가져올 수 있는데, 이런 방법을 타입에 의한 '자동 와이어링'이라고 함
	* 변수에 할당 가능한 타입을 가진 빈을 자동으로 찾음
	* 같은 타입의 빈이 두 개 이상 있는 경우, 타입만으로는 어떤 빈을 가져올지 결정할 수 없음
		* 타입으로 빈 하나를 가져올 수 없는 경우에는 변수명과 같은 이름을 가진 빈이 있는지 확인 
		* 변수 이름으로도 빈을 찾을 수 없는 경우, 예외 발생 
* @RunWith : JUnit 프레임워크의 테스트 실행 방법을 확장할 때 사용하는 애노테이션
	* SpringJUnit4ClassRunner라는 JUnit 용 테스트 컨텍스트 프레임워크 확장 클래스를 지정해주면
	  JUnit이 테스트를 진행하는 중에 테스트가 사용할 애플리케이션 컨테스트를 만들고 관리
* @ContextConfiguration : 자동으로 만들어줄 애플리케이션 컨텍스트릥 설정파일 위치 지정 
* 스프링은 설정 파일의 종류만큼 애플리케이션 컨텍스트를 만들고, 같은 설정파일을 지정한 테스트에서는 이를 공유
* 스프링 애플리케이션 컨텍스트는 초기화할 때 자기 자신도 빈으로 등록
	* 애플리케이션 컨텍스트에는 ApplicationContext 타입의 빈이 존재하는 셈이고, DI도 가능
* **테스트에서도 가능한 한 인터페이스를 사용해서 애플리케이션 코드와 느슨하게 연결해두는 편이 좋음**

### DI와 테스트
* 인터페이스를 두고 DI 적용 필요
	* 1. 소프트웨어 개발에서 절대로 바뀌지 않는 것은 없기 때문
	* 2. 클래스의 구현 방식은 바뀌지 않는다고 하더라도 인터페이스를 두고 DI를 적용하게 해두면
	     다른 차원의 서비스 기능을 도입할 수 있기 때문
	* 3. 테스트 때문 > 효율적인 테스트를 손쉽게 만들기 위해

* @DirtiesContext
	* 스프링의 테스트 컨텍스트 프레임워크에게 해당 클래스의 테스트에서 애플리케이션 컨텍스트의 상태를 변경한다는 것을 알려줌
	* 일단 테스트에서 빈의 의존 관계를 강제로 DI하는 방법을 사용했을 때 문제는 피할 수 있음
		* 하지만 애플리케이션 컨텍스트를 매번 만드는 건 조금 찜찜.
* DI는 객체지향 프로그래밍 스타일
	* DI를 위해 컨테이너가 반드시 필요한 것은 아님, DI 컨테이너나 프레임워크는 DI를 편하게 적용하도록 도움을 주는 것이지,
	  컨테이너가 DI를 가능하게 해주는 것은 아님 
* 항상 스프링 컨테이너 없이 테스트 할 수 있는 방법을 가장 우선적으로 고려 필요
	* 테스트 수행 속도가 가장 빠르고, 테스트 자체가 간결

### 학습 테스트로 배우는 스프링
* 학습 테스트(learning test)
	* 자신이 만들지 않은 프레임워크나 다른 개발팀에서 만들어서 제공한 라이브러리 등에 대해서 테스트 작성
	* 목적 : 자신이 사용할 API나 프레임워크의 기능을 테스트로 보면서 사용방법을 익히기 위함
* 장점
	* 1. 다양한 조건에 딸느 기능을 손쉽게 확인 가능
	* 2. 학습 테스트 코드를 개발 중에 참고할 수 있음
	* 3. 프레임워크나 제품을 업그레이드할 때 호환성 검증을 도와줌
	* 4. 테스트 작성에 대한 좋은 훈련이 됨
	* 5. 새로운 기술을 공부하는 과정이 즐거워 짐
### 버그 테스트
* 버그테스트(bug test)
	* 코드에 오류가 있을 때 그 오류를 가장 잘 드러내줄 수 있는 테스트
	* 버그가 원인이 되서 테스트가 실패하는 코드를 만드는 것
	* 버그 테스트가 성공할 수 있도록 애플리케이션 코드를 수정
* 버그 테스트의 필요성과 장점
	* 테스트의 완성도를 높여준다
		* 기존 테스트에서 검증하지 못한 부분에 대해 테스트를 만들어 불충분했던 테스트를 보완
	* 버그의 내용을 명확하게 분석하게 해준다
		* 버그를 테스트로 만들어서 실패하게 하려면 원인을 명확하게 알아야 하므로, 그 과정에서 분석해볼 기회가 주어짐
	* 기술적인 문제를 해결하는 데 도움이 된다 
		* 기술적으로 다루기 힘든 버그를 발견할 때가 있는데, 그 때 버그테스트를 만들어보면 도움이 된다.

## 템플릿
* '템플릿' 이란?
	* 바뀌는 성질이 다른 코드 중에서 변경이 거의 일어나지 않으며 일정한 패턴으로 유지되는 특성을 가진 부분을 
	  자유롭게 변경되는 성질을 가진 부분으로부터 독립시켜서 효과적으로 활용할 수 있도록 하는 방법

### JBDC 수정 기능의 예외처리 코드
> 리소스 반환과 closed()
	* closed() 메소드 : 보통 리소스를 반환한다는 의미
	* Connection과 PreparedStatement는 보통 풀(pool) 방식으로 운영
		* 미리 정해진 pool 안에서 제한된 수의 리소스(Connection과 PreparedStatement)를 만들어 두고 필요할 때 이를 할당, 반환 
		* 사용한 리소스는 빠르게 반환 필요
			* 그렇지 않으면 풀의 리소스가 고갈되고 결국 문제 발생 
	* closed()는 보통 '만들어진 순서의 반대'로 하는 것이 원칙
* JDBC 코드에서는 **try/catch/finally** 구문 사용을 권장
* finally : try 블록을 수행한 후에 예외가 발생하든 정상적으로 처리되든 상관 없이 반드시 실행되는 코드를 넣을 때 사용
* closed() 도 SQLException이 발생할 수 있는 메소드
	* try/catch 문으로 처리 필요

### 변하는 것과 변하지 않는 것
* 변하지 않는, 그러나 많은 곳에서 중복되는 코드 / 로직에 따라 자꾸 확장되고 자주 변하는 코드 분리 필요 

### 분리와 재사용을 위한 디자인 패턴 적용
* 메소드 추출
	* 변하는 부분을 메소드로 뺴는 것
* 템플릿 메소드 패턴
	* 상속을 통해 기능 확장
	* 변하지 않는 부분 -> 슈퍼클래스에 두고,
	  변하는 부분 -> 추상 메소드로 정의해둬서 서브 클래스에서 오버라이드하여 새롭게 정의하여 사용
	* 템플릿 메소드 패턴의 제한점 
		* DAO 로직마다 상속을 통해 새로운 클래스를 만들어야 함
		* 확장 구조가 이미 클래스를 설계하는 시점에 고정됨 
* 전략 패턴
	* 오브젝트를 아예 둘로 분리하고 클래스 레벨에서 인터페이스를 통해서만 의존하도록 만드는 패턴
		* 개방 폐쇄 원칙을 잘 지키는 구조
		* 템플릿 메소드 패턴 보다 유연하고 확장성이 뛰어남
> 마이크로 DI
	* DI의 장점을 단순화해서 IoC 컨테이너의 도움 없이 코드 내에서 적용한 경우 
	* 코드에 의한 DI라는 의미로 수동 DI라고도 부름

**Comment by flyingtw** [comment]
3.1 다시 보는 초난감 DAO
- 초난감 dao는 예외 상황 처리에 대한 문제가 존재
  - close() 메소드는 리소스는 반환한다는 의미이다. 즉, 풀로 다시 돌려서 다른 커넥션을 사용할 수 있도록 여유를 남기는것.
  - 이를 해결하기 위해 try, cathc, finally  구문을 사용한다.
- query를 수행하는 resultset도 예외 처리를 통하여 try문으로 잡을 수 있다.
- close문은 만들어진 순서의 반대로 즉, 가장 마지막에 수행할 부분을 가장 처음 try로 잡아주는것이 좋다.

3.2 변하는 것과 변하지 않는 것
- 하지만 모든 커넥션, excute 등에 try-catch를 붙이면 코드가 너무 길어진다.
- 실제로 connection pool을 닫아주지 않아서 일주일마다 서버를 껏다켜야하는 경우도 있다.
- 가장 기본적인 방법은 중복되는 로직을 뽑아서 메서드화 하는 것이다.
- 이를 해결하기 위해 템플릿 메소드 패턴을 적용하여 변하지 않는 부분은 슈퍼 클래스에, 변하는 부분은 추상 메소드로 정의하여 서브 클래스에서 상속 받아서 오버라이드 한다음 새롭게 정의해 쓰도록 하는것이다.
- 하지만 이역시도 문제이다. 서브 클래스를 상속받아 원하는 로직마다 새로 서브 클래스를 추가해야 한다는 점이다. 
- 변하지 않는 부분을 contextmethod가 된다.
- 외부 기능을 호출하는 부분을 전략 패턴이라고 한다!
- 하지만 컨텍스트(delete와 관련된) 안에서 delete를 콱 선언해 버리면 개방원칙에 위배된다.
- 앞서 objectFactory를 만들어서 구현했던것처럼 구현하면 된다.
-

**Comment by kyueun** [comment]
`@Autowired` 대신 `@RequiredArgsConstructor`
- 스프링 4.3 이후로 단일 생성자에 대해 `@Autowired` 생략 가능 -> `@RequiredArgsConstructor` 권장
- 의존성 주입받아야 하는 객체가 null인 경우 `@Autowired` 사용하면 런타임 시에 문제 발생 / `@RequiredArgsConstructor` 사용하면 컴파일부터 문제 발생
