### ISSUE TITLE
Chapter3. 템플릿

### ISSUE THREAD

**Issue by flyingtw** [FireInStove/toby-spring#5]
# 👑 스터디장
- 김태완(flyingtw)
# 📖 스터디 범위
- 3.3 ~ 3.5
# 🕧 스터디 일정
- 23/07/06 09시

**Comment by yougahee** [comment]
## ✏️ 5주차 (3장. 템플릿)

## 중첩 클래스
- 장점 : 내부 클래스에서 외부 클래스의 멤버들을 쉽게 접근할 수 있다.
### 종류
- 스태틱 클래스
	- 독립적으로 오브젝트로 만들어질 수 있는 클래스
	``` java
	public class OuterClass {

		public static void main(String[] args) {
			System.out.println(StaticInnerClass.b);
		}

		static class StaticInnerClass{
			int a = 3;
			static int b = 10;
		}
	}
	```
	
- 내부 클래스
	- 자신이 정의된 클래스의 오브젝트 안에서만 만들어질 수 있는 클래스
	1) 내부 클래스
		- 클래스 내부에 정의되는 클래스
		``` java
		public class OuterClass {

			class InnerClass { }
		}
		```
	2) 로컬 클래스
		- 메소드 내부에 정의되는 클래스
		- 선언된 메소드 내에서만 사용 가능
		``` java
		public class OuterClass {

			public void test() {
				class localClass {
					int v = 3;
				}
			}
		}
		```
	3) 익명 내부 클래스
		- 이름이 없는 클래스
		- 클래스의 선언과 동시에 객체 생성도 하여 오직 하나의 객체만 생성이 가능하고, 일회성 클래스
		``` java
		public void deleteAll() throws SQLException {
			jdbcContextWithStatementStrategy(
			new StatementStrategy() {
				public PreparedStatement makePreparedStatement(Connection c) throws SQLException {
					return c.prepareStatement("delete from users");
				}
			}
			);
		}
		```

## JdbcContext 와 DI
- 해당 책에서, UserDao -> JdbcContext -> DataSource 로 의존관계를 맺고 있다.
	- UserDao, JdbcContext 는 클래스 / DataSource는 인터페이스
- 스프링의 DI
	- 기본적으로 인터페이스를 사이에 두고 의존 클래스를 바꿔서 사용하는 것이 목적.
- 그러나, 예제에서는 인터페이스가 없고, JdbcContext 클래스를 의존하여 사용한다.(클래스 레벨의 의존 관계)
	- 문제는 없을까?
	- 인터페이스를 사용하지 않았다면 온전한 DI라고 볼수는 없지만, 넓은 의미에서 객체의 생성과 관계 설정에 대한 제어 권한이 JdbcContext에 있다는 걸 보면 IoC 개념을 포괄

## 수동 DI 
- UserDao가 JdbcContext를 DI하지 않고, DataSource를 DI하면서, JdbcContext를 셋팅하는 방식
- 해당 메소드가 실행되는 시점은 DI 컨테이너가 DataSource 오브젝트를 주입해줄 때 호출 
``` java
    public void setDataSource(DataSource dataSource) {
        this.jdbcContext = new JdbcContext();
        this.jdbcContext.setDataSource(dataSource);
        
        this.dataSource = dataSource;
    }
```
- 해당 방법의 장점
	- 굳이 인터페이스를 두지 않아도 될 DAO 클래스와 JdbcContext를 어색하게 따로 빈으로 분리하지 않고 내부에서 직접 만들어 사용


## 템플릿/콜백 패턴
- 템플릿 
	- 고정된 작업 흐름을 가진 코드를 재사용
- 콜백
	- 템플릿 안에서 호출되는 것을 목적으로 만들어진 오브젝트
	- 실제 작업이 이뤄지는 부분

- 반복적으로 사용하는 코드가 있다면, 이를 템플릿으로 만들어두고 콜백을 사용하여 재활용하는 것이 좋다.
- 코드의 줄도 짧아지고, 가독성도 좋고, 자원 해제 등 변경 사항이 있다면 템플릿만 수정하면 되어 영향 범위도 줄어든다.
``` java
public void deleteAll() throws SQLException {
	executeSql("delete from users");
}

private void executeSql(final String query) throws SQLException {
	this.jdbcContext.workWithStatementStrategy(c -> c.prepareStatement(query));
}
```

**Comment by kyueun** [comment]
## JDBC 전략 패턴의 최적화

### 중첩 클래스
다른 클래스 내부에 정의되는 클래스
- 스태틱 클래스 : 독립적으로 오브젝트로 만들어질 수 있음
- 내부 클래스 : 자신이 정의된 클래스와 오브젝트 안에서만 만들어질 수 있음
    - 멤버 내부 클래스 : 오브젝트 레벨에 정의
    - 로컬 클래스 : 메소드 레벨에 정의
    - 익명 내부 클래스 : 이름을 갖지 않음
<details>
<summary>샘플 코드</summary>

```java
public class OuterClass {

    private StaticClass sc;
    private MemberInnerClass mic;
    // private LocalClass lc; // LocalClass 는 선언된 메소드 안에서만 접근 가능

    public OuterClass() {

        this.sc = new StaticClass();
        this.mic = new MemberInnerClass();
    }

    public StaticClass getSc() {

        return sc;
    }

    public MemberInnerClass getMic() {

        return mic;
    }

    public static class StaticClass {}

    public class MemberInnerClass {}

    public String getLocalClassStr() {

        class LocalClass {}

        LocalClass lc = new LocalClass();

        return lc.toString();
    }

    public AnonymousInnerClass getAic() {

        return new AnonymousInnerClass() {

            @Override
            public String getStr() {

                return this.toString();
            }
        };
    }
}

interface AnonymousInnerClass {

    public abstract String getStr();
}

public class OtherClass {

    public void methodOfOtherClass() {

        OuterClass oc = new OuterClass();

        // static class -> 외부에서도 생성 가능
        OuterClass.StaticClass sc = new OuterClass.StaticClass();
        OuterClass.StaticClass sc1 = oc.getSc();
        System.out.println("[sc]\t"+sc);
        System.out.println("[sc1]\t"+sc1);

        // member inner class -> 선언된 클래스틀 통해서만 생성 가능 / 생성 이후에는 외부에서 접근 가능
        // OuterClass.MemberInnerClass memberInnerClass = new XXX;
        OuterClass.MemberInnerClass mic = oc.getMic();
        System.out.println("[mic]\t"+mic);

        // local class -> 외부에서 생성 불가 / 접근 불가
        // LocalClass lc = new XXX;
        System.out.println("[lc]\t"+oc.getLocalClassStr());

        // anonymous inner class
        AnonymousInnerClass aic = new AnonymousInnerClass() {
            @Override
            public String getStr() {

                return this+" NEW";
            }
        };
        AnonymousInnerClass aic1 = oc.getAic();
        System.out.println("[aic]\t"+aic.getStr());
        System.out.println("[aic1]\t"+aic1.getStr());
    }

    public static void main(String[] args) {

        OtherClass otherClass = new OtherClass();
        otherClass.methodOfOtherClass();
    }
}
```
</details>


## 컨텍스트와 DI
스프링의 DI
- 기본적으로 인터페이스를 사이에 두고, 의존 클래스를 바꿔 사용하도록 하는 것이 목적
- 책 예제의 `JdbcContext`의 경우 구현 방법이 바뀔 가능성이 없어 인터페이스 구현하지 않음
    - `UserDao` - `JdbcContext` 사이에 인터페이스 없이 DI 적용 = 런타임이 아닌 클래스 레벨에서 의존 관계가 결정
        - 의존관계가 고정되었다 == 온전한 DI라고 볼 수 없다
        - 하지만, 스프링을 이용해 `JdbcContext`를 `UserDao`에 주입 -> 객체 생성, 관계 설정에 대한 제어 권한이 오브젝트가 아닌 외부(스프링) == IoC 개념을 포괄하므로 DI라고 볼 수 있음

### 수동 DI
`JdbcContext`의 생성, 초기화를 외부에서 관리해줘야 함 -> `UserDao`에게 맡김
- `UserDao`는 `JdbcContext`의 생성, 초기화 관리
- `JdbcContext`는 `DataSource`를 동적으로 주입받음
- => `UserDao`가 `DataSource`를 DI 받고, `JdbcContext` DI 작업에 사용

## 템플릿과 콜백
### 템플릿
어떤 목적을 위해 미리 만들어둔 모양이 있는 틀
- 전략 패턴의 컨텍스트

### 콜백
실행되는 것을 목적으로 다른 오브젝트의 메소드에 전달되는 오브젝트
- 익명 내부 클래스로 만들어지는 오브젝트

값을 참조하기 위한 것이 아닌, 메소드를 수행시키기 위한 것
- 메소드 자체를 파라미터로 전달할 수 없으므로, 메소드가 담긴 오브젝트를 전달 -> 메소드 레벨의 DI

**Comment by tmfrl1552** [comment]
### 로컬 클래스
> 중첩 클래스의 종류
	* 중첩 클래스 (nested class) : 다중 클래스 내부에 정의되는 클레스
	* 독립적으로 오브젝트로 만들어질 수 있는 스태틱 클래스(static class) 와 
  	자신이 정의된 클래스의 오브젝트 안에서만 만들어질 수 있는 내부 클래스(inner class)로 구분된다.
  	* 내부 클래스는 범위(scope)에 따라 3가지로 구분
 		* 1. 멤버 내부 클래스 - 멤버 필드처럼 오브젝트 레벨에 정의되는 클래스
 		* 2. 로컬 클래스 - 메소드 레벨에서 정의되는 클래스
 		* 3. 익명 내부 클래스 - 이름을 갖지 않는 클래스
* 로컬 클래스
	* 로컬 변수 선언하듯이 선언
	* 선언된 메소드 내부에서만 사용 가능
	* 클래스가 내부 클래스이므로 자신이 선언된 곳의 정보에 접근할 수 있다는 장점 
	* 내부 클래스에서 외부 변수 사용 시, **final 선언** 필수

### 익명 내부 클래스
> 익명 내부 클래스 (anonymous inner class)
	* 이름을 갖지 않는 클래스
	* 클래스 선언과 오브젝트 생성이 결합된 형태로 생성
	* 클래스를 재사용할 필요가 없고, 구현한 인터페이스 타입으로만 사용할 경우에 유용
* 익명 내부 클래스
	* 선언과 동시에 오브젝트 생성
	* 이름이 없으므로 클래스 자신의 타입을 가질 수 없고, 구현한 인터페이스 타입의 변수에만 저장 가능

### 스프링빈으로 DI
* 스프링의 DI
	* 넓게 보자면 객체의 생성과 관계설정에대한 제어권한을 오브젝트에서 제거하고 외부로 위임했다는 Ioc 라는 개념을 포괄
* JdbcContext를 UserDao와 DI 구조로 만들어야 하는 이유
	* 1. JdbcContext가 스프링 컨테이너의 싱글톤 레지스트리에서 관리되는 싱글톤 빈이 되기 때문
		* JdbcContext는 JDBC 컨텍스트 메소드를 제공해주는 일종의 서비스 오브젝트로써 의미가 있음
		* 그래서 싱글톤으로 등록돼서 여러 오브젝트에서 공유해 사용되는 것이 이상적
	* 2. ⭐️ JdbcContext가 DI를 통해 다른 빈에 의존하고 있기 때문 ⭐️
		* 스프링이 생성하고 관리하는 IoC 대상이어야 DI에 참여할 수 있기 때문
* 인터페이스를 사용하지 않은 이유?
	* UserDao(client)와 JdbcContext(context)가 매우 긴밀한 관계를 가지고 강하게 결합되어 있음
	* 이런 경우 굳이 인터페이스를 두지 말고 강력한 결합을 가진 관계를 허용하면서,
	  위에서 말한 두가지 이유인 싱글톤으로 만드는 것과 JdbcContext에 대한 DI 필요성을 위해 스프링의 빈으로 등록해서 DI 되도록 만들어도 좋음
### 코드를 이용한 수동 DI
* UserDao(client) 내부에서 직접 DI를 적용하는 방법
* JdbcContext에는 내부에 두는 상태 정보가 없음
	* 오브젝트 수십, 수만개가 만들어져도 메모리에 주는 부담 거의 없음
	* 자주 만들어졌다가 제거되는게 아니므로 GC에 대한 부담도 없음
==> JdbcContext에 대한 제어권은 UserDao가 갖는 것이 적당
* UserDao는 직접 DataSource 빈을 필요로 하지 않지만 JdbcContext에 대한 DI 작업에 사용할 용도로 제공받는 것
	* UserDao가 직접 DataSource를 의존하고 있는 것 같지만, 
	  내부적으로는 JdbcContext를 통해 간접적으로 DataSource를 사용하고 있을 뿐
* 위 두가지 방법의 장/단점
	* 1. 인터페이스를 사용하지 않는 클래스와의 의존관계이지만, 스프링의 DI를 이용하기 위해 빈으로 등록해서 사용하는 방법
		* 장점 : 오브젝트 사이의 실제 의존관계가 설정 파일에 드러난다.
		* 단점 : DI의 근본적인 원칙에 부합하지 않는 구체적인 클래스와의 관계가 설정에 직접 노출
	* 2. DAO의 코드를 이용해 수동으로 DI를 하는 방법
		* 장점 : JdbcContext가 UserDao의 내부에서 만들어지고 사용되면서 그 관계를 외부에는 드러내지 않는다.
		* 단점 : JdbcContext를 여러 오브젝트가 사용하더라도 싱글톤으로 만들 수 없고, DI 작업을 위한 부가적인 코드가 필요 
	==>  두 방법이 장/단점이 서로 반대가 되는 것 같다!!

## 템플릿과 콜백
* 템플릿/콜백 패턴 : 전략 패턴의 기본구조에 익명 내부 클래스를 활용한 방식
	* 템플릿
		* 전략 패턴의 컨텍스트 
		* 고정된 작업의 흐름을 가진 코드를 재사용한다는 의미
	* 콜백
		* 익명 내부클래스로 만들어지는 오브젝트
		* 템플릿 안에서 호출되는 목적으로 만들어진 오브젝트
		* 자바에선 메소드 자체를 파라미터로 전달할 방법은 없으므로 메소드가 담긴 오브젝트 전달 필요 ➡️ 펑셔널 오브젝트(funtional object)
### 템플릿/콜백의 특징
* 템플릿/콜백 패턴은 보통 단일 메소드 인터페이스 사용
	* 템플릿의 작업 흐름 중 특정 기능을 위해 '한 번' 호출되는 경우가 일반적 
	* 콜백은 일반적으로 하나의 메소드를 가진 인터페이스를 구현한 익명 내부 클래스로 만들어진다고 보면 됨
* 콜백 인터페이스의 메소드에는 보통 파라미터가 존재
	* 템플릿의 작업 흐름 중에 만들어지는 컨텍스트 정보 전달받을 때 사용 

#### 템플릿/콜백의 작업 흐름
![템플릿:콜백 흐름](https://github.com/FireInStove/toby-spring/assets/52412936/6426aeb4-4195-417a-93ea-369ff4be4c6a)

* 콜백 오브젝트가 내부 클래스로서 자신을 생성한 클라이언트 메소드 내의 정보를 직접 참조

### 템플릿/콜백의 응용
* 가장 전형적인 템플릿/콜백 패턴의 후보는 'try/catch/finally' 블록 사용
	* 일정한 리소스를 만들거나 가져와 작업하면서 예외가 발생할 가능성이 있는 코드는
	  보통 try/catch/finally 구조로 만들어질 가능성이 높음 
* 템플릿/콜백 적용 시에는 템플릿과 콜백의 경계를 정하고, 
  템플릿이 ➡️ 콜백에게 / 콜백이 ➡️ 템플릿에게 각각 전달하는 내용이 무엇인지 파악하는게 가장 중요
  * 그에 따라 콜백 인터페이스를 정의할 수 있으므로.

**Comment by aimhigh53** [comment]
3.3
add() 메소드의 PreparedStatement 생성 로직을 분리한 클래스

3.4

* UserDao.deleteAll(), UserDao.add(): 클라이언트
    * 어떤 전략을 사용할지 의존성을 결정
* 익명 내부 클래스: 전략
    * 구체적인 전략
* UserDao.jdbcContextWithStatementStrategy(): 컨텍스트
    * PreparedStatement를 실행하는 변하지 않는 부분
JDBC의 일반적인 작업 흐름을 담고있는 jdbcContextWithStatementStrategy()는 다른 DAO에서도 사용 가능하다. jdbcContextWithStatementStrategy()를 UserDao 클래스 밖으로 독립시켜서 모든 DAO가 사용할 수 있게 해보자.

익명 내부 클래스 씀?

클래스 분리
JdbcContext라는 클래스를 생성하여 UserDao에 있던 컨텍스트 메소드를 workWithStatementStrategy()라는 이름으로


빈 의존관계 변경
UserDao는 이제 JdbcContext에 의존하고 있다. 그런데, JdbcContext는 인터페이스인 DataSource와 달리 구체 클래스이다.
스프링의 DI는 기본적으로 인터페이스를 사이에 두고 의존 클래스를 바꿔서 사용하도록 하는 게 목적이다. 하지만 이 경우 JdbcContext는 그 자체로 독립적인 JDBC 컨텍스트를 제공해주는 서비스 오브젝트로서 의미가 있을 뿐
따라서 인터페이스를 구현하도록 만들지 않았고, UserDao와 JdbcContext는 인터페이스를 사이에 두지 않고 DI를 적용하는 구조


JdbcContext의 인터페이스 없는 DI
UserDao와 JdbcContext사이에는 인터페이스를 사용하지 않고 DI를 적용
UserDao와 JdbcContext는 클래스 레벨에서 의존관계가 발생
런타임 시에 DI 방식으로 외부에서 오브젝트를 주입해주는 방식을 사용하긴 했지만, 의존 오브젝트의 구현 클래스를 변경할 수는 없음


JdbcContext와 같이 인터페이스를 사용하지 않고 DAO와 밀접한 관계를 갖는 클래스를 DI에 적용하는 방법 두가지

빈으로 등록하는 방법
* 장점
    * 의존관계가 설정파일에 명확하게 드러난다.
    * 싱글톤 레지스트리에 등록 가능
* 단점
    * DI의 근본적 원칙에 부합하지 않는 구체적인 클래스와의 관계가 설정에 직접 노출된다.
수동으로 DI하는 방법
* 장점
    * 관계를 외부에 드러내진 않는다.
* 단점
    * 싱글톤 불가능
    * DI작업을 위한 부가적인 코드가 필요하다.


3.5

템플릿
* 어떤 목적을 위해 미리 만들어둔 모양이 있는 틀
* 고정된 틀 안에 바꿀수 있는 부분을 넣어서 사용하는 경우를 템플릿이라 함
* 변하는 것과 변하지 않는 것을 분리
* 고정된 틀의 로직을 갖는 템플릿 메소드를 슈퍼 클래스에 두고, 바뀌는 부분을 서브 클래스의 메소드에 두는 구조

콜백
* 실행되는 것을 목적으로 다른 오브젝트의 메소드에 전달되는 오브젝트
* 파라미터로 전달되지만, 값을 참조하는 것이 아닌 특정 로직을 담은 메소드 실행을 목적
* 자바에서는 메소드 자체를 전달하는 방법이 없기 때문에 메소드가 담긴 오브젝트를 전달
* 이를, 펑셔널 오브젝트(Functional Object)라 함

* 템플릿은 작업 흐름을 가진 코드를 재사용한다는 의미에서 붙인 이름이며, 콜백은 템플릿 안에서 호출되는 것을 목적으로 만들어진 오브젝트
* 보통, 전략 패턴(템플릿) 및 익명 내부 클래스(콜백)를 같이 사용함
* 여러 개의 메소드를 지닌 일반적 전략 패턴과 달리, 템플릿/콜백은 단일 메소드 인터페이스 사용
* 콜백 인터페이스 메소드의 파라미터는 컨텍스트 정보(DB Connection)를 받을 때 사용


작업흐름
    * 클라이언트의 역할은 템플릿 안에서 콜백 오브젝트를 만들고, 콜백이 참조할 정보 제공. 만들어진 콜백은 클라이언트가 템플릿의 메소드를 호출할 때 파라미터로 전달
    * 템플릿은 정해진 작업 흐름을 따라 작업을 진행하다가 내부에서 생성한 참조정보를 가지고 콜백 오브젝트의 메소드를 호출. 콜백 작업 수행 후 결과를 템플릿에 전달템플릿은 콜백 작업 수행 결과를 사용해 작업을 마저 수행. 최종 결과를 클라이언트에게 전달해 주기도 함
    * 템플릿은 콜백 작업 수행 결과를 사용해 작업을 마저 수행. 최종 결과를 클라이언트에게 전달해 주기도 함   즉, 전달받은 펑셔널 오브젝트는 템플릿에서 사용될 때 호출됨
* 클라이언트가 템플릿을 호출하면서 콜백 오브젝트를 전달하는 것은 메소드 레벨의 DI
* 템플릿/콜백 방식은 매번 메소드 단위로 사용할 오브젝트를 새롭게 전달
* 콜백 오브젝트는 (익명)내부 클래스로서, 클라이언트 내 메소드의 멤버를 직접 참조가능
* 클라이언트와 콜백이 강하게 결합된다는 특징이 있음
* 즉, 템플릿/콜백 방식은 전략 패턴과 DI의 장점을 익명 내부 클래스를 사용한 전략과 결합한 독특한 활용법임


* 템플릿과 클라이언트가 메소드 단위인것이 특징임
* 템플릿의 리턴 값이 없음

* 현재 템플릿/콜백 방식은 상대적으로 코드 작성하고 읽기 불편
* 복잡한 익명 내부 클래스의 사용 최소화
* deleteAll()에서 변하는 것은 SQL 실행 문장뿐임
* 변하지 않는 부분을 executeSql()로 추출하고, JdbcContext에 옮김
* 구체적 구현, 내부의 전략 패턴, 코드에 의한 DI, 익명 내부 클래스 등의 기술은 감추고, 외부에 꼭 필요한 기능만 제공하는 단순 메소드만 노출
* 가변인자(String... str)를 통해 부가 정보를 받음(책에 가변인자 부분 코드가 나와있지 않음)
