### ISSUE TITLE
Chapter 3. 템플릿(3) ~ Chapter 4. 예외(1)

### ISSUE THREAD

**Issue by tmfrl1552** [FireInStove/toby-spring#6]
## 👑 스터디장
- 이슬기(@tmfrl1552 )

## 📖 스터디 범위
- 3.6 ~ 4.1

## 🕧 스터디 일정
- 23/07/13 09시

**Comment by flyingtw** [comment]
## 3.6 스프링의 JdbcTemplate

### 3.6.1 update()
### 3.6.2 queryForInt()
### 3.6.3 queryForObject()
### 3.6.4 query()
### 3.6.5 재사용 가능한 콜백의 분리


## 4.1 사라진 SQLException
- jdbcTemplate 을 사용하면서 throw SQLException 이 사라졌다.

### 4.1.1 초난감 예외처리
- try-catch문으로 예외처리를 할 경우 catch 문을 비워두는 경우가 있는데 이는 절대 해서는 안되는 행동이다.
- 프로그램중 어디선가 문제가 생긴 상황이지만 모르고 넘어가버리기 때문
- system.out이나 printstackTrace() 같이 얼렁뚱땅 넘어가는것도 모두 금지
    - 운영서버에 올라가거나 실제 서비스 되는 상황에선 콘솔이 묻혀버릴 가능성이 큼
- 예외처리의 핵심 원칙은 적절하게 복구를 하던지, 작업을 중단시키고 분명하게 통보를 하던지 둘 중 하나이다.
    - exit(1)로 꺼버리는게 훨씬 낫다

### 4.1.2 예외의 종류와 특징
- 자바에서 throw를 통해 발생시킬 수 있는 예외는 크게 세 가지가 있다.
    - Error : java.lang.Error의 서브클래스
        - 자바 VM에서 발생시키는 에러임으로 이런 에러처리는 필요하지 않다.
    - Exception과 체크 예외
        - java.lang.Exception 클래스와 그 서브 클래스
            - 체크 예외 : RuntimeException 클래스를 상속하지 않은것
            - 언체크 예외 : RuntimeException 클래스를 상속받은것
        - 즉, RuntimeException을 상속받지 않은걸 체크 예외이다.
        - 체크예외는 반드시 예외를 처리하는 코드를 함께 작성해야 한다.
            - 보통 많이 사용하는 throw로 던지는 방식
        - 언체크 예외는 RuntimeException에서 다 처리가 되기 때문에 catch문이나 throws로 처리하지 않아도 된다.
        - 주로 프로그램 자체적인 오류가 있을때 발생하기 떄문
        - NPE나 Illegal ecxption등이 대표적인 예시
    - 하지만 무분별한 throw나 예외 블랙홀이 발생하기 떄문에 (예외인데 아무것도 처리하지 않는것) 최근에는 예상 가능한 예외 상황을 다루는 예외를 체크 예외로 만들지 않는 경향이 있다.
    - 
### 4.1.3 예외처리 방법
- 예외복구
    - 예외가 발생했을경우 예외로 비치긴 하지만 전체적인 흐름상으론 retry 하거나 alert을 보여주는등의 방식
- 예외처리 회피
    - 예외가 발생한 로직을 호출한 곳으로 예외를 뱉어서 예외 처리를 회피하는 방식이다. 
    - SQLException 같은 경우 sql 실패로 인한 예외발생시 연결에 대한 처리를 add 메소드가 하지 않아도 되기 때문에 상위 로직으로 예외를 던져버리는것이다.
- 예외 전환
    - DB Insert 로직에서 예외가 발생했을경우 SQLException보다는 DuplicateException등으로 바꿔서 발생시키면 보다 명확하게 예외 상황을 처리할 수 있다.
    - 이방식의 경우 원래 발생한 예외를 담아서 '중첩예외' 로 만드는것이 좋다.
    - 또다른 예외 전환 방식으로는 원인이 되는 예외를 언체크 예외인 런타임 예외로 바꿔버리는것이다. (아예 런타임 에러로 스탑되도록)


### 4.1.4 예외처리 전략
- 런타임 예외의 보편화
    - 체크 예외로 처리하면 무조건 catch 해서 throw를 해야하니 요즘엔 runtime 예외로 언체크 예외로 처리하는게 보편적인 방식이다
- add() 메소드의 예외처리
    - SQLException 이더라도 중복같은 예외는 DuplicationException 같이 명시적인 예외로 전환시키고, 그외 는 RuntimeException으로 처리되도록 한다.
- 애플리케이션 예외
    - 일반적인 예외로 흐름을 끊기지 않게 하기 위한 예외들은 애플리케이션 단에서 처리 가능하도록 만든다. errorCode등을 정의해서 내려줄 수 있지만 간혹 개발자들간의 약속이 다를경우 혼란을 야기할 수 있다.
    - 정상적인 흐름의 코드는 그대로 냅두고 잔고 부족과 같은 상황을 비즈니스 예외를 만들어서 처리하는 방식도 있다.
        - 이러한 예외는 명시적으로 체크예외로 만들어두어 개발자가 직접 예외상황을 처리하도록 한다.

### 4.1.5 SQLException은 어떻게 됐나?
- JDBC Template 에서는 모든 SQLException을 런타임 예외로 포장해서 바꿔주고 개발자는 이 예외를 필요한 경우에만 처리하면 된다. 그 외는 런타임이니 신경쓸 필요가 없다는뜻.
- 대부분의 스프링의 예외는 Runtime에러임으로 사용하는 메서드에서 이를 잡아서 굳이 처리할 의무는 없다.

**Comment by yougahee** [comment]
## ✏️ 6주차 (3장. 템플릿 ~ 4장. 예외처리)

## 3.6 스프링의 jdbcTemplate
1. queryForInt() 
	- getCount() 메소드
	- 템플릿/콜백으로 이루어져서 단 한 줄만 작성해도 모든 것을 해줌
2. queryForObject()
	- 결과값을 조회하는 곳에서 사용하는 쿼리


## 잘못된 예외처리
1. 예외를 잡아놓고, 아무런 작업을 하지 않음
	- 아무런 행동도 하지 않겠다는 의도가 없다면, 잘못된 예외처리
2. 무책임한 throw Exception 
	- 해당 메소드를 사용하는 함수 모든 곳에서 예외를 던짐
	- 어딘가에서 예외를 처리해주지 않고 계속 throw로 던지는 행위

## 좋은 예외처리
1. 작업을 중단시키고, 운영자 또는 개발자에게 보고
2. 적잘히 복구

## 예외 종류
1. Error
	- 주로 자바 VM에서 발생시킴
	- 애플리케이션이 아닌 OutOfMemoryError 또는 ThreadDeath 같은 에러

2. Exception 과 체크 예외
	- 애플리케이션 코드 중 예외 상황
	- Checked Exception
		- 컴파일 중 에러 발생
		- 반드시 예외 처리 필요
	- Unchecked Exception
		- 런타임 중 에러 발생
		- 로직 등에서 나는 이유로 프로그램 동작 상에는 문제가 없지만, 기능상에는 문제가 있을 수는 있음.


## 예외처리 방법
1. 예외복구
	- 정상 상태로 만들어두기
2. 예외처리 회피
	- 자신을 호출한 쪽으로 예외던지기 (throw exception)
	- 반드시 그것을 사용하는 메소드쪽에서 예외를 처리해줘야 함. (계속 throw 하는 것은 좋지 않음.)
3. 예외 전환
	- 예외를 메소드 밖으로 던짐
	- 발생한 예외 그대로 던지는 것이 아닌, 적절한 예외로 전환
	- ex) SQLException 이 발생했을 경우, 해당 에러가 발생할 수 있는 케이스가 많기 때문에 어떤 에러 때문에 발생했는 지, 구체화 시키는 것



## 요즘은 예외처리를 어떻게 할까?
- 체크 예외의 활용도 및 가치가 하락하고 있다. 
- 항상 복구할 수 없다면, unchecked로 처리하는 추세

**Comment by kyueun** [comment]
## 스프링의 JdbcTemplate
### queryForInt
결과값을 integer로 받음

### queryForObject
결과값이 row 하나일 때 object로 받음
결과가 없을 때 예외 발생

### query
결과값이 row 여러개일 때 지정한 타입으로 받음
결과가 없을 때 빈 List 반환

# 예외
## 초난감 예외처리
예외 발생 시, 아무것도 해주지 않거나 단순히 출력하는 건 예외를 처리한 것이 아님

## 예외의 종류와 특징
### Error
시스템 문제 ( 주로 자바 VM에서 발생시킴 )
애플리케이션의 관심사가 아님

### Exception, 체크 예외
체크 예외 : RuntimeException을 상속하지 않은 것
- 예외 처리 강제
- 처리하지 않으면 컴파일 시 에러 발생

### RuntimeException, 언체크/런타임 예외
언체크 예외 : RuntimeException을 상속한 것
- 예외 처리 강제하지 않음
- 처리하지 않으면 런타임에 에러 발생

## 예외처리 방법
- 예외 복구 : 정상 상태로 돌려놓기
    - ```java
        void test(int maxRetry) {
            while(maxRetry-- > 0) {
                try {
                    ...
                } catch (AException e) {
                    sleep();
                }
            }
            throw new BException();
        }
- 예외처리 회피 : 호출한 쪽으로 예외 그대로 던지기
    - ```java
        void test() throws Exception { ... }
- 예외 전환 : 적절한 예외로 전환해서 외부에 던지기
    - ```java
        void test() {
            try {
                ...
            } catch (AException e) {
                throw new BException(e); // 중첩 예외
            } catch (CException e) {
                throw new RuntimeException(e); // 예외 포장
            }
        }

런타임 에러의 보편화
- 사용자들이 여러 요청 시, 한 요청에서 예외 발생하면 해당 작업만 중지
- 대응 불가능한 체크 예외는 런타임 예외로 전환해서 던지는 게 낫다
    - 대응 불가능한 체크 예외 = throws Exception 메소드만 늘어남

어플리케이션 예외
- 로직에서 의도적으로 발생시키고, 반드시 catch 해야하는 예외
- 설계 방법
    1. 정상 동작 / 예외 케이스에 다른 종류의 값 리턴
        - ```java
            int test(SomeRequest request) {
                if (request.invalid()) {
                    return -1;
                }
                return 1;
            }
    2. 비즈니즈적 의미를 가진 예외 발생
        - ```java
            int test(SomeRequest request) {
                if (request.invalid()) {
                    throw new BusinessException();
                }
                return 1;
            }

**Comment by tmfrl1552** [comment]
## 3.6 스프링의 JdbcTemplate
#### queryForInt()
SQL 쿼리를 실행하고 정수의 결과 값(Integer 타입)을 가져올 때 사용하는 메소드
* 현재는 Deprecated 돼서, queryForObject로 대신 사용


#### queryForObject()
SQL의 DML 중 SELECT를 실행했을 때 하나의 객체(Object) 결과 값이 나올 때 사용하는 메소드


#### query()
많은 결과 값(로우 값)을 처리 할 수 있는 메소드

<br>

## 4. 예외
* 예외 처리 시, 반드시 지켜야할 핵심 원칙
	* 모든 예외는 적절하게 복구되든지 아니면 작업을 중단시키고 운영자 또는 개발자에게 분명하게 통보

### 초난감 예외처리
* 예외를 무시하거나 잡아버리는 코드는 위험하므로 만들지 말자
	* 예외를 잡아서 조치를 취할 방법이 없으면 잡지 말자

* 무책임한 throws 선언
	* 의미 있는 정보를 얻을 수 없다.
	* 적절한 처리를 통해 복구될 수 있는 예외상황도 다룰 수 있는 기회 박탈

### 예외의 종류와 특징
자바의 throw를 통해 발생시킬수 있는 총 3가지 예외

#### Error
* java.lang.Error 클래스의 서브 클래스
* 애플리케이션 코드가 아닌 주로 java VM에서 발생
	* 애플리케이션에서는 에러 처리 신경 안써도 무방
* ex) OutOfMemory, ThreadDeath

#### Exception과 체크 예외
* java.lang.Exception 클래스와 그 서브클래스로 정의되는 예외들은 애플리케이션 코드 작업 중 예외 상황 발생하는 경우에 사용
* Exception 클래스의 두 가지 예외
	* 체크 예외
		* Exception 클래스의 서브 클래스이면서, RuntimeException 클래스 상속하지 않는 것
	* 언체크 예외
		* Exception 클래스의 서브 클래스이면서, RuntimeException 클래스 상속하는 것

* 일반적으로 말하는 예외 ➡️ '체크 예외' 
* 예외가 발생할 수 있는 메소드 사용 시, 반드시 예외 처리 코드 작성
* ex) IOException, SQLException


#### RuntimeException과 언체크/런타임 예외
* 명시적인 예외 처리를 강제하지 않으므로 언체크 예외라고 불림
* 에러와 마찬가지로 런타임 예외는 catch문으로 잡거나 throws로 선언하지 않아도 됨
	* 명시적으로 잡거나 throws 선언도 가능
* 주로 프로그램의 오류가 있을 때 발생하도록 의도
* ex) NullpointException, IllegalArgumentException

<br>

### 예외처리 방법
#### 예외 복구
예외상황을 파악하고 문제를 해결해서 정상 상태로 돌려놓는 것
* 예외처리 코드를 강제하는 체크 예외들은 예외를 어떤 식으로 복구할 가능성이 있는 경우 사용
```java
int maxRetry = MAX_RETRY;
while(maxRetry --> 0){
	try{
		...
		return;

	} catch(SomeException){
		// 로그 출력 후, 일정 시간 대기

	} finally {
		// 리소스 반납, 정리 작업
	}
	throw new RetryFailedException(); // 최대 재시도 횟수 넘기면 직접 예외 발생
}
```

#### 예외 회피
예외처리를 자신이 담당하지 않고, 자신을 호출한 쪽으로 던져버리는 것
* 예외를 자신이 처리하지 않고 회피하는 방법
	* throws 선언해서 알아서 던지는 방법
	* catch문으로 일단 예외를 잡은 후에 로그 남기고, 다시 예외를 던지는 방법
* 예외를 복구하는 것 처럼 의도 분명해야 함
	* 자신을 사용하는 쪽에서 예외를 다루는게 최선의 방법이라는 확신 필요
```java
public void add() throws SQLException{
	...
}
```
```java
public void add() throws SQLException{
	 try {

	  	... 

	} catch(SQLException e) {
		// 로그 출력
		throw e;
	}
}
```

#### 예외 전환
예외 회피와 같이 예외를 메소드 밖으로 던지나, 예외 회피와는 달리 예외를 그대로 넘기는 게 아닌 적절한 예외로 전환해서 던지는 것
* 예외 전환 목적
	* 1. 내부에서 발생한 예외를 그대로 던지는 것이, 그 예외상황에 대한 적절한 의미 부여가 되지 않을 때
	* 2. 예외를 처리하기 쉽고 단순하게 만들기 위해 포장
		* 체크 예외를 언체크 예외인 런타임 예외로 바꾸는 경우 주로 사용
* 전환 예외는 원래 발생한 예외를 담아서 '중첩 예외'로 만드는 것이 좋음
```java
// 중첩 예외 
catch(SQLException e){
	...
	throw DuplicateUserIdException(e);
}


// 예외 포장
catch(SQLException e){
        throw new EJBException(e);
}
```

#### 바람직한 예외처리란?
어쩌피 복구하지 못한 예외라면 애플리케이션 코드에서는 런타임 예외로 포장해서 던지고,
예외처리 서비스 등을 이용해서 자세한 로그를 남기고, 관리자에게는 메일 등으로 통보해주고,
사용자에게는 친절한 안내 메시지를 보여주는 식으로 처리

#### 최근 예외 처리 경향
* 최근 등장하는 표준 스펙 또는 오픈 소스 프레임워크에서는 API가 발생시키는 예외를 체크 예외 대신 언체크 예외로 정의하는 것이 일반화
* 항상 복구할 수 있는 예외가 아니라면 일단 언체크 예외로 만드는 경향

#### 애플리케이션 예외
시스템 또는 외부의 예외상황이 아니라 애플리케이션 자체의 로직에 의해 의도적으로 발생시키고, 
반드시 catch해서 무엇인가 조치를 취하도록 요구하는 예외


#### SQLException은 어떻게 됐나?
* 99%의 SQLException은 코드 레벨에서는 복구할 방법이 없음
	* SQL 문법 오류 
	* 제약조건 위반
	* DB 서버 다운 or 네트워크 불안정
	* DB 커넥션 풀이 꽉 차서 커넥션을 가져올 수 없는 경우
* JdbcTemplate은 템플릿과 콜백 안에서 발생하는 모든 SQLException을 런타임 에외인 DataAccessException으로 포장해서 던져줌
* 스프링 API 메소드에 정의된 대부분의 예외는 런타임 예외
	* 발생 가능한 예외가 있다고 하더라도 이를 처리하도록 강제하지 않음

**Comment by aimhigh53** [comment]
3.6 JdbcTemplate
* 스프링이 제공하는 JDBC 코드용 기본 템플릿
* JdbcTemplate은 생성자의 파라미터로 DataSource를 주입하면 됨
* JdbcTemplate는 DAO 안에서 만들
어 수동 DI를 하는
 것이 관례임
* 하지만, 낮은 결합도를 위해 JdbcTemplate를 독립적인 빈으로 등록하고 JdbcTemplate가 구현하고 있는 JdbcOperations 인터페이스를 통해 DI받아 사용하도록 해도 됨

update()
* deleteAll()에 처음 적용한 콜백은 StatementStrategy 인터페이스의 makePreparedStatement()임
* 이에 대응되는 JdbcTemplate 콜백은 PrepareStatementCreator 인터페이스의 createPreparedStatement()임
* 템플릿으로 부터 Connection을 제공받아 PreparedStatement를 반환하는 점에서 같음
* update()를 통해 콜백을 구현
* 앞서 만들었던 executeSql() 처럼 SQL 문장만으로 미리 준비된 콜백을 만들어서 템플릿을 호출 할 수 있음
* ps에 값을 바인딩 은 SQL 문장 다음 파라미터에 넣으면 됨

queryForInt() -> deprecated

queryForObject()
* get() 메소드에 JdbcTemplate 적용
* get()의 경우 값을 바인딩 하고, User 오브젝트를 만들어 반환해 줘야함
* ResultSetExtractor는 ResultSet을 한번 전달받음
* RowMapper는 ResultSet의 로우 하나를 매핑하기 위해 사용되기 때문에 여러번 호출될 수 있음 -> 중복제거
* RowMapper 콜백을 사용하여 첫 번째 로우에 담긴 정보를 하나의 User 오브젝트에 매팽하면 됨
* RowMapper 두 번째 파라미터는 세 번째 파라미터가 존재하기 때문에 가변인자을 사용하지 못하고, 오브젝트 배열을 사용해서 SQL에 바인딩 해야함
* RowMapper가 호출되는 시점에서 ResultSet은 첫 번째 로우를 가리키므로, next()를 하지 않아도 됨
* queryForObject()는 SQL을 실행해서 받은 로우의 개수가 하나가 아니라면 EmptyResultDataAccessException 예외를 던지게 되어 있음

query()
* 모든 사용자 정보를 가져오는 getAll() 사용
* 사용자 정보를 List<User> 컬렉션 사용
* id 순으로 정렬(order by)
* 동등성 비교
* 바인딩할 파라미터가 있으면 두 번째 파라미터에 추가. 없으면 생략 가능


중복제거

3.7
* 스프링은 JDBC 코드 작성을 위해 JdbcTemplate을 기반으로 하는 다양한 템플릿과 콜백을 제공한다.
* 템플릿은 한 번에 하나 이상의 콜백을 사용할 수도 있고, 하나의 콜백을 여러번 호출할 수도 있다.
* 템플릿/콜백을 설계할 때는 템플릿과 콜백 사이에 주고받는 정보에 관심을 둬야 한다.

전략/템플릿 메소드
<img width="677" alt="스크린샷 2023-07-13 오전 8 50 50" src="https://github.com/FireInStove/toby-spring/assets/37101427/20e8f385-adad-4f46-85c5-77d5a2601a4a">

<img width="673" alt="스크린샷 2023-07-13 오전 8 52 41" src="https://github.com/FireInStove/toby-spring/assets/37101427/af3c89dc-d096-4582-9dbb-2af9ab6689ac">

4.1
* 예외 블랙홀
    *  try/catch만 씌워주고 아무 것도 안 한다. 최악의 코드라고 한다. 
자바에서 throws를 통해 발생시킬 수 있는 예외 3가지
1. Error : java.lang.Error클래스의 서브클래스들이다. 시스템적인 문제 상황(OutOfMemoryError 등)에서 발생하기 때문에 VM에서 주로 발생시킨다. 그렇기 때문에 애플리케이션 단에서 따로 처리할 수도 없고 해서도 안 된다.
2. Exception과 체크 예외(Checked Exception) : java.lang.Exception 클래스 및 서브클래스로 정의되는 예외들은 애플리케이션에서 발생하는 예외에서 사용된다.예외는 체크예외,언체크예외로 나뉘는데 Exception의 하위클래스들 중 RuntimeException을 상속하지 않은 예외들을 체크예외라고 하고 RuntimeException을 상속한 예외들을 언체크 예외라고한다. 체크 예외는 예외처리 코드가 필수이다. 안 그러면 컴파일 에러가 발생한다.(IOException, SQLException 등)
3. RuntimeException과 언체크/런타임 예외 : java.lang.RuntimeException 클래스를 상속한 예외들이다. 예외 강제가 없으며 프로그램 오류가 있을 때 발생하도록 되어 있다. NullPointException, IllegalArgumentException 등이 있다. 즉, 개발자 부주의로 인해 발생하는 예외이다.
 예외 복구
*  예외상황을 파악하고 문제를 해결해서 정상 상태로 돌려놓는 것이다. 요청 파일을 읽으려고 헀는데 문제가 발생하여 IOException이 발생할 경우 상황을 사용자에게 알려주고 다른 파일을 이용하도록 안내할 수 있다. 작업 흐름을 다른 작업 흐름으로 유도해주는 것이다. 
*  또한 네트워크 문제로 SQLException이 발생하면 재시도 코드를 통해 예외상황을 복구 시도할 수 있다. 다음과 같은 코드가 그런 예이다.

예외처리 회피
 예외처리를 자신이 담당하지 않고 자신을 호출한 쪽으로 던지는 것이다. throws 선언으로 예외발생시 알아서 던지거나 catch로 잡아서 로그를 찍어주고 rethrow하는 것이다. jdbcTemplate나 jdbcContext에서 콜백오브젝트가 SQLException을 템플릿에게 던지는데, 이런 경우 두 관계가 긴밀하게 역할분담을 하고 있기 때문이다. SQLException은 콜백의 책임이 아니라고 보는 것이다. 
 이런 경우를 제외하고 무조건 throws로 던져서 결국 컨트롤러까지 가서 서버에 전달하면 안 된다. 예외 복구처럼 목적이 명확해야 한다.
 
예외전환
 예외를 메소드 밖으로 던질 때 적절한 예외로 전환해서 던지는 것이다. 사용하는 이유는 크게 두 가지이다.
 첫번째로 내부에서 발생한 예외를 그대로 던질 때 서비스단 등에서 적절하게 의미 해석이 어려울 때, 의미를 분명하게 해주는 예외로 바꿔 던진다. 사용자 정보 등록 시에 중복된 아이디 값 때문에 SQLException이 난 경우 의미가 명확한 DuplicateKeyException으로 전환할 수 있다. 다음과 같다.
