### ISSUE TITLE
Chapter 4. 예외 ~ Chapter 5. 서비스 추상화

### ISSUE THREAD

**Issue by yougahee** [FireInStove/toby-spring#7]
## 👑 스터디장
- 가희 (@yougahee)

## 📖 스터디 범위
- 4.2 ~5.1

## 🕧 스터디 일정
- 23/7/20 09시 ~

**Comment by flyingtw** [comment]
# 4.2 예외 전환
- 예외 전환의 목적은 런타임 예외로 포장해서 굳이 필요하지 않은 try-catch를 줄이는것과 로우 레벨의 예외를 의미 있고 추상화된 예외로 바꿔서 던져주는것
- 복구가 불가능한 예외인 SQLException을 보기 쉬운 예외로 바꿔서 처리가능하게 바꿀 수 있다

## 4.2.1 JDBC의 한계
- JDBC는 자바를 이용해 DB에 접근하는 방법을 추상화된 API 형태로 정의
- 객체지향을 잘 살릴 수 있다.
### 비표준 SQL
- 대부분의 DB는 표준 SQL 뿐만 하니라 추가 기능들이 있다.
- 따라서 DAO를 DB별로 만들어 사용하거나 SQL을 외부에서 독립시켜서 바꿔서 쓰게 한다. -> 7장에서 한다고함;
### 호환성 없는 SQLException의 DB 에러 정보
- DB마다 DB벤더가 정희한 고유의 에러 코드를 사용한다.
- DB별로 에러 코드가 다르기 때문에 SQLException을 의 세분화하여 잡는건 DB마다 다른 방식으로 구현해야 한다.
- 따라서 SQLException은 예외 발생시의 DB 상태를 담은 SQL 상태정보를 부가적으로 제공한다.
- getSQLState()가 그 예시 - XOPEN SQL 스펙에 정의된 SQL 상태 코드를 따르도록 되어있다.

## 4.2.2 DB 에러 코드 매핑을 통한 전환
- 각 DB 별로 나오는 각기 다른 에러 코드를 스프링의 정의한 예외 클래스와 매핑하여 사용한다.
- DB가 달라지더라도 같은 종류의 에러라면 동일한 예외를 받을 수 있다. 
- 아직은 스프링의 에러 코드 매핑을 통한 DataAccessException 방식을 사용하는 것이 이상적이다 

## 4.2.3 DAO 인터페이스와 DataAccessException 계층구조
- DAO 로 인터페이스호 하여 메소드 구현을 추상화 하였지만, DB 기술(JPA, JDO등)이 던지는 예외가 각기 다르기 때문에 인터페이스에서는 통일된 SQLException을 던지게 할 수 없다.
- 가장 쉬운 방법은 throw Exception...
- 이외에도 계층 구조를 활용하여 이상적인  DAO를 만들 수 있다... 흠

## 4.2.4 기술에 독립적인 UserDao 만들기
- 인터페이스로 받아서 테스트하는게 좋다
- 테스트를 하며 큰 Exception을 통과하게 하거나 안하게 해서 세부 exception을 알 수 있다.
- 하지만 DuplicatekeyException은 아직 JDBC에서만 사용 가능하다.
- JDBC 말고도 다른 SQL 기술을 사용할대 DuplicationException 같은 특정 exception을 잡고 싶다면 dataSource를 넣어서 계층구조상에 같은 형태의 exception 이 있는 지 확인한다.. 흠


# 5.1 사용자 레벨 관리 기능 추가
- 이제 UserDao에 CRUD만 넣지 말고 구체적인 로직을 구현해보자 (활동에 따라 일괄적용되는 LEVEL을 넣었음)

## 5.1.1 필드 추가
- 레벨을 이늄타입으로 정하는게 좋다
- 오타조심

## 5.1.2 사용자 수정 기능 추가
- where 문을 빼먹지 말자 (update쿼리의 결과를 int로 받아서 테스트도 가능)

## 5.1.3 UserService.upgradeLevels()
- Service는 Dao인터페이스를 사용한다.
- UserDao 오브젝트의 DI가 가능하도록 수정자 메소드도 추가..

## 5.1.4 UserService.add()
- 최초 레벨 초기화 할때 파라미터를 받으면 저장을, 없으면 최초값을 넣는걸 service에서 한다.

## 5.1.5 코드 개선
- 로직상의 if/elseif/ else 문은 읽기 불편하다.
- 성격이 다른 블록이 섞여있기 때문이다....
- 각 기능별로 역할을 분리해서 메소드화 하니까 보기 편해졌다..!
- enum에 next를 넣는건 좋은 방식인것 같다.

**Comment by aimhigh53** [comment]
4.2
* 런타임 예외로 포장해 불필요한 catch/throws 를 줄여주는 것
* 로우레벨의 예외를 좀더 의미 있고 추상화된 예외로 바꿔서 던져주는 것
* DAO는 인터페이스를 사용해 구체적인 클래스 정보와 구현방법을 감추고 DI를 통해 제공
* 중복키 에러가 발생할 경우 기술마다 다른 Excption이 발생, DAO는 기술에따라 달라야함...
* JDBC → SQLException, JPA → PersistenceExcpetion. 하이버네이트 → HibernateExcpetion
* DataAccessException은 엑세스 기술의 종류와 관계 없이 일관된 예외가 발생하도록 만들어줌
* Spring은 이를 계층구조로 분류
* 낙관적인 락킹 (JPA같은 오브젝트/엔티티 단위로 정보를 업데이트 하는 경우)
두명 이상의 사용자가 동시조회하고 순차적으로 업데이트할때 뒤늦게 업데이트한것을 덮어쓰지 않도록 막아줌


4.3

* 예외를 잡아서 아무런 조치도 취하지 않거나 throws를 남발하는 것은 위험하다.
* 예외는 복구하거나 예외처리 오브젝트로 의도적으로 전달하거나 적절한 예외로 전환해야 한다.
* 좀 더 의미 있는 예외로 변경하거나, 불필요한 catch/throws를 피하기 위해 런타임 예외로 포장하는 두가지 방법의 예외 전환이 있다.
* 복구할 수 없는 예외는 가능한 한 빨리 런타임 예외로 전환하는 것이 바람직하다.
* 애플리케이션의 로직을 담기 위한 예외는 체크 예외로 만든다.
* JDBC의 SQLException은 대부분 복구할 수 없는 예외이므로 런타임 예외로 포장해야 한다.
* SQLException의 에러 코드는 DB에 종속되기 때문에 DB에 독립적인 예외로 전환될 필요가 있다.
* 스프링은 DataAccessException을 통해 DB에 독립적으로 적용 가능한 추상화된 런타임 예외 계층을 제공한다.
* DAO를 데이터 액세스 기술에서 독립시키려면 인터페이스 도입과 런타임 예외 전환, 기술에 독립적인 추상화된 예외로 전환이 필요하다.






5.1	

1. 코드에 중복된 건 없는지
2. 이해하기 불편하지 않은지
3. 자신이 있어야할 자리에 있는지
4. 변화에 쉽게 대응할 수 있는지

나머진… LEVEL … 난 플래티넘 회원이고 싶다

**Comment by kyueun** [comment]
## 예외 전환
### DB 에러 코드 매핑을 통한 전화
SQLException 발생 시, 각 에러 코드마다 의미가 드러나는 예외로 전환 가능
- DB마다 에러 코드가 다름 -> DB 별 에러 코드를 분류, DB에 독립적인 예외로 매핑 가능
- ```xml
    <bean id="Oracle" class="org.springframework.jdbc.support.SQLErrorCodes">
        <property name="badSqlGrammarCodes">
            <value>900, 903, 904</value>
        </property>
    </bean>
    ```

### 기술에 독립적인 UserDao 만들기
인터페이스 적용, 구현 클래스 개발 시 기술 적용

# 서비스 추상화
## 사용자 레벨 관리 기능 추가
사용자 관리 로직 등은 UserDaoJdbc 등과 같이 데이터 조작을 위한 클래스가 아닌 비즈니스 로직을 담을 별도 클래스에 구현해야 함

**Comment by yougahee** [comment]
## ✏️ 7주차 (4.2 ~ 5.1)

## 4.2 예외 전환

### 예외 전환의 목적
1. 런타임 예외로 포장해서 굳이 필요하지 않은 catch/throws를 줄여주는 것
2. 로우레벨의 예외를 좀 더 의미있고 추상화된 예외로 바꿔서 던져주는 것

### DB종류가 바뀔 때, DAO를 수정하지 않는 것이 어려운 이유
1. JDBC 코드에서 사용하는 SQL
	- 특별한 기능을 제공하는 함수를 SQL에 사용하려면 대부분 비표준 SQL 문장이 만들어짐.
2. SQLException 
	- 에러의 케이스는 많은데, 공통으로 SQLException을 던진다.
	- 각 DB마다 에러 코드와 메세지가 다르다


### 그렇다면,, 해결 방법은?
- DB별 에러코드를 매핑해주는 방법
	- ex) 중복 키 에러 코드 => MySQL - 100 / 오라클 - 300
	- 우리 서버에서는 DuplicateKeyException으로 던져주기
	``` java
		
		public void add() throws DuplicateKeyException {
			
		}
	```
- 그렇지만, interface로 만들고 구현을 하려고 할 때 throws exception이 각 DB기술마다 달라, 사용할 수 없게 된다. 
	``` java
		
		public void add() throws SQLException; // MySQL
		public void add() throws PersistentException; // JPA
	```
	- 단순하게 throws Exception으로 해결은 가능하나, 무책임하다.

### 데이터 액세스 예외 추상화
- 스프링의 DataAccessException
- 어떤 DB를 사용하던, 데이터 엑세스 기술에서 발생할 수 있는 대부분의 예외를 추상화하고 있다. 
- 의미가 같은 예외라면 일관된 예외가 발생하도록 만들어준다.
- 런타임 예외로 SQLException을 포장해주는 역할

### DataAccessException 사용 시 주의사항
- 근본적인 한계 때문에 완벽하다고 할 수 없음.
	- 실제로, JDBC만 적용되고 있고, JPA나 하이버네이트, JDO의 경우는 좀 더 포괄적인 예외로 던져지면서 활용 가치가 떨어진다.
- 미리 test를 만들어서 실제로 전환되는 예외 종류를 확인해볼 필요가 있다.


## 5.1 사용자 레벨 관리 기능 추가 (기능 추가에 대한 내용)
- LEVEL Enum을 생성하고 유저의 레벨을 올려주는 함수 구현
- 오브젝트와 메소드가 책임을 맡아 일하는 구조
- 오브젝트에게 데이터를 요구하지 않고 작업을 요청
- 테스트 코드에서의 중복도 제거를 해주자

**Comment by tmfrl1552** [comment]
## 4.2 예외 전환
### JDBC의 한계
현실적으로 DB를 자유롭게 바꿔서 사용할 수 있는 DB 프로그램을 작성하는 데 두가지 걸림돌 존재
1. JDBC 코드에서 사용하는 SQL
	* SQL은 어느 정도 표준화된 언어지만, 대부분의 DB는 표준을 따르지 않는 비표준 문법과 기능 제공
	* 비표준 SQL은 결국 DAO 코드에 들어가고, 특정 DB에 대한 종속적 코드가 됨
2. SQLException
	* DB마다 에러의 종류와 원인이 제각각
	* 호환성 없는 에러 코드와 표준을 잘 따르지 않는 상태 코드를 가진 SQLException만으로
	  DB에 독립적인 유연한 코드를 작성하는 건 불가능에 가까움.

<br>

### SQLException 비표준 에러코드와 SQL 상태 정보에 대한 해결책
DB별 에러 코드를 참고하여 발생한 예외의 원인이 무엇인지 해석해주는 기능 생성
* DB 종류에 상관 없이 동일한 상황에 일관된 예외를 전달 ➡️ 효과적인 대응 가능
* ex) 키 중복에 대한 SQLExeption을 의미가 분명히 들어나는'DuplicateKeyException' 로 예외 전환

<br>

스프링은 DB별 에러코드를 분류해서 스프링이 정한 예외 클래스와 매핑해놓은
에러 코드 매핑정보 테이블을 만들어두고 이를 이용.
* JdbcTemplate은 SQLException을 단지 런타임 예외인 DataAccessException으로 포장하는 것이 아니라
   DB의 에러 코드를 DataAccessException 계층 구조의 클래스 중 하나로 매핑.
	* JdbcTemplate : 스프링이 제공하는 JDBC용 기본 템플릿

<br>

### DAO 인터페이스와 DataAccessException 계층 구조
#### DataAccessException
* JDBC의 SQLException 전환 용도 뿐만 아니라
  JDBC 외의 자바 데이터 액세스 기술에서 발생하는 예외에도 적용
* 의미가 같은 예외라면 데이터 액세스 기술의 종류와 상관없이 일관된 예외가 발생하도록 만들어 줌
* '데이터 액세스 기술에 독립적인 추상화된 예외'를 제공

<br>

### DAO 인터페이스 분리

DAO를 따로 만들어서 사용하는 이유

* 데이터 액세스 로직을 담은 코드를 ➡️ 성격이 다른 코드에서 분리

<br>

DAO의 사용 기술과 구현 코드는 전략 패턴과 DI를 통해서 DAO를 사용하는 클라이언트에게 감출 수 있지만,
메소드 선언에 나타나는 예외정보가 문제가 될 수 있음
* 해결책
	* JDBC보다 늦게 등장한 JDO, Hibernate, JPA 등의 기술은
  	  SQLException 같은 체크 예외 대신 런타임 예외 사용
	* JDBC를 이용한 DAO에서는 모든 SQLException을 런타임 예외로 포장
	* 🔝 위와 같은 방식을 사용하면 메소드 선언 가능

* 추가 문제점
	* 데이터 액세스 기술이 달라지면 같은 상황에서도 다른 종류 예외 발생
	* DAO를 사용하는 클라이언트에서는 DAO 사용 기술에 따라 예외 처리 방법이 달라져야 함
		* DAO의 기술에 의존적

<br>

### 데이터 액세스 예외 추상화와 DataAccessException 계층 구조
스프링은 다양한 데이터 액세스 기술을 사용할 때 발생하는 예외들을 추상화하여
DataAccessException 계층 구조 안에 정리
* 여러 데이터 액세스 기술에 대해서 발생할 수 있는 유사한 예외를 추상화해서
  DataAccessException의 서브 클래스로 지정
* 즉, 공통적인 부분은 추상화하고, 데이터 액세스 기술에 대한 구체적인 예외는 추상화된 클래스의 구제척인 서브 예외클래스로 존재

<br>

### 🤓 결론 
```java
인터페이스 사용, 런타임 예외 전환, DataAccessException 예외 추상화 적용
➡️ 데이터 액세스 기술과 구현 방법에 독립적인 DAO 생성 가능

```

<br>

## 5. 서비스 추상화
### 사용자 레벨 관리 기능 추가
* 기능 추가에 따른 기존 코드 수정
	* 필드 추가 
	* 기능 추가에 따른 UserDaoTest 코드 수정
* UserService 코드 및 테스트 코드 생성
	* UserService : 사용자 레벨 업데이트 로직 구현된 서비스
* UserService 코드 및 테스트 코드 리팩토링

<br>

### 💡 느낀점
코드 작성 시에는 다음을 잘 고려하자!
```java
1. 확장성
2. 코드 수정에 따른 번거로움을 줄이기 위한 공통화
3. 기능 별로 책임을 잘 분리
```
