### ISSUE TITLE
Chapter 5. 서비스 추상화 전체

### ISSUE THREAD

**Issue by aimhigh53** [FireInStove/toby-spring#8]
## 👑 스터디장
- 인석

## 📖 스터디 범위
- 5장 전체

## 🕧 스터디 일정
- 23/7/27 09시 ~

**Comment by flyingtw** [comment]
# 5.2 트랜잭션 서비스 추상화
- 인프라 등의 문제가 발생하면 다시 돌릴 상황에선?


## 5.2.1 모 아니면 도
- 예외를 강제로 발생시키는 방법이 있다.
- UserService 를 이용하여 protected 메서드를 이용하여 상속을 통해 오버라이딩이 가능하게 하여 level에 접근 가능하게 한다.
- 트랜잭션 문제. 각 업그레이드 하는 단계가 트랙잭션으로 나눠져 있어 이미 Level이 업그레이드 된 회원은 업그레이드 된것이 문제이다.

## 5.2.2 트랜잭션 경계 설정
- DB의 sql 자체는 다중 로우로 요청할경우 후반 로우가 실패하면 이전 로우는 원복이 된다. 즉 트랜잭션이 보장된다.
- 하나의 sql qurey는 DB가 트랜잭션을 보장해준다고 믿을 수 있다.
- 뒤동선이 실패할경우 앞동선을 원복시키는것이 트랜잭션 롤백이라 한다.
- 반대로 여러가지 쿼리가 성공했을때 DB에게 성공했다고 알리는것을 트랜잭션 커밋이라고 한다.
- 트랜잭션이 시작되고 끝나는 부분을 트랜잭션의 경계라고 부른다.
- JDB는 setAutoCommit, commit 을 통해 트랜잭션을 시작하고 종료할 수 있다.
- 트랜잭션을 시작하려면 자동 커밋 옵션을 false로 세팅
- 이와같이 트랜잭션을 설정하는건 트랜잭션의 경계 설정이라고 한다.
- 하나의  DB커넥션 안에서 만들어지는 트랜잭션을 로컬 트랜잭션이라고 한다.
- 하나의 DAO 작업을 했을 경우엔 하나의 트랜잭션이 만들어지는 구조이다.
- Connection이 시작될 경우 트랜잭션이 시작되는 구조이기 때문에 upgrade 메서드 안에서 connection을 생성할 수 밖에 없다.
- Connection 오브젝트를 전달하는 순간 인터페이스로 만든 모든 로직이 번거로워지고 JPAtemplate도 사용할 수 없고 service 내에서 트랜잭션을 사용하지 않아도 될 메서드도 connection 오브젝트를 파라미터로 받아야 하는 번거로움이 있다.

## 5.2.3 트랜잭션 동기화
- upgrade 메서드의 트랜잭션 경계 설정은 유지하고, connection을 생성하고 commit하는건 유지하며 dao에 전달할때는 connection 오브젝트를 전달하지 않아도 되도록 spring은 지원한다.
- 독립적인 트랜잭션 동기화 방식. 
- 트랜잭션 동기화(TransactionSynchronization)에 service는 connection을 저장해두고 dao가 꺼내서 사용하게 한다.
- JDBCTemplate은 Connection을 닫지 않은 채로 작업을 마치고, UserService에서는 모든 단계가 마무리 되면 commit을 통해 최종 승인 시킨다.
- jdbctemplate은 트랜잭션 동기화 속에 속하게 되면 자동으로 트랜잭션을 생성하지 않는다.


## 5.2.4 트랜잭션 서비스 추상화
- 글로벌 트랜잭션이 필요하다.
- JTA가 제공하는 api로 트랜잭션 매니저를 이용하면 여러개의 DB의 트랜잭션을 관리할 수 있다.
- jdbc 자체가 sql 쿼리나는 추상화된 개념을 공통적으로 뽑아서 쓸 수 있게 만든거다.
- 
# 5.3 서비스 추상화와 단일 책임 원칙
- 계층별로 구분을 하자
- DI가 계층 구분을 깔끔하게 해주는 역할을 해준다.
- 단일책임 원칙이 각 역할을 구분하게 해준다.
- DI가 핵심이다.
# 5.4 메일 서비스 추상화
## 5.4.1 JavaMail을 이용한 메일 발송 기능
- 메일발송.. 자바메일..
- service안에 로직을 넣지 않는다!
## 5.3.2 JavaMail이 포함된 코드의 테스트
- 테스트용 메일 서버 역할을 하듯이 javaMail 이 정상적으로 수신을 받았다는걸 활용하여 테스트를 할 수 있다.
## 5.4.3 테스트를 위한 서비스 추상화
- javamail에 대한 서비스 추상화 인터페이스를 생성하여 테스트를 할 수 있다.
- 흠
## 5.4.4 테스트 대역
- userService가 원활하게 테스트 되게 하기 위하여 DummyMailSender를 이용하여 성공 처리하는 방식
- 스프링의 DI를 이용하여 어떤 방식으로든 접근 가능하게 구현한다.
- 자주 테스트가 가능하게 만드는 것들을 테스트 대역이라고 부른다.
- 대표적으론 테스트 스텁. 
- MockObject를 이용하여 간접적으로 출력 결과를 검증할 수 있다.

# 5.5 정리
- db트랜잭션 관리, MailSender 와 같은 예를 통해 각 계층별 기능을 나누는 법을 알 수 있었다.
- 서비스 추상화란 각 계층별로 역할을 나누고 DI를 통해 테스트도 수월하게 할 수 있다.

**Comment by yougahee** [comment]
## ✏️ 8주차 (5.2 ~ 5.4)

## 테스트용으로 클래스의 메소드를 만들어서 사용하고 싶다면!?!
- 테스트 클래스 내부에 스태틱 클래스를 만들어 테스트하자.
``` java
public class testService {

	@Test
	public void updateAllOrNothing() {
		// 아래 TestUserService를 가져와서 사용
		UserService UserService = new TestUserService();

		// 테스트할 내용
	}

	static class TestUserService extends UserService {
		// 테스트용 메서드 작성하기
	}

}
```

## 트랜잭션
- 트랜잭션
	- DB의 connection pool 중 하나를 가져와 사용
	- 롤백 : 작업의 시작 ~ 끝까지 이전 상태로 되돌리는 작업
	- 커밋 : SQL 수행작업이 다 성공적으로 마무리됐다고 DB에 알려줘서 작업을 확정
- 트랜잭션 경계설정 
	- 트랜잭션이 존재하는 범위 (즉, 트랜잭션이 시작하는 곳과 끝나는 곳)
	- setAutoCommit(false) ~ commit()/rollback()
	- 하나의 Connection이 만들어지고 닫히는 범위 안에서 존재함(=로컬 트랜잭션)
- 알아두기 
	- 기본적으로 따로 트랜잭션을 설정하지 않으면, 한 쿼리당 하나의 트랜잭션이 발생한다고 생각하면 된다.

## 트랜잭션 경계 설정의 문제점
1. JdbcTemplate 활용 불가 > 깔끔한 코드 분리 불가
2. UserService > 메소드에 Connection 파라미터 추가
3. UserDao > 데이터 액세스 기술에 독립적 X
4. DAO 메소드에 Connection 파라미터 > 테스트 코드에 영향


## 트랜잭션 동기화
- UserService에서 트랜잭션을 시작하기 위해 만든 Connection 오브젝트를 특별한 저장소에 보관해두고 이후 호출되는 메소드에서 가져다가 쓰는 것 
- 이를 사용하면, 파라미터를 통해 일일이 Connection 오브젝트를 전달할 필요가 없어진다.

- 멀티스레드 환경에서 트랜잭션 동기화
	- 스프링에서 TransactionSynchronizationManager 를 제공 

- DataSource
	- 커넥션 생성 시, 사용할 DataSource 
- DataSourceUtils > getConnection()
	- Connection 오브젝트 생성 및 transaction 동기화에 사용하도록 저장소에 바인딩

- jdbcTemplate
	- jdbcTemplate이 미리 생성돼서 DB 커넥션이나 트랜잭션이 없는 경우 직접 만들고, 이미 존재하면 가져와서 사용한다.

## 글로벌 트랜잭션
- 분산 트랜잭션은 11장에서 더 자세히.. 일단 넘어감

- JTA(Java Transaction API)
	- global transaction 처리
- PlatformTransactionManager
	- 트랜잭션 경계 설정을 위한 추상 Interface

## 트랜잭션 추상화
- PlatformTransactionManager > Interface


## 5.3 단일 책임 원칙
- 한가지 모듈은 하나의 책임만 가져야 한다.
- 장점
	- 어떤 변경이 필요할 때 수정 대상이 명확해진다.
	- 수정 범위가 적어지며, 버그가 일어날 확률이 낮다.

## 5.4 메일 서비스 추상화
- 개요 : 사용자의 레벨이 올라가면, 메일을 전송할 수 있게 해달라.
- 메일 서비스 추상화
	- MailSender 인터페이스를 구현
- 트랜잭션은 어떻게 적용할 것인가?
	1. 발송 대상을 저장해두고, 작업이 정상적으로 완료된 경우 send
	2. MailSender를 확장해서 트랜잭션 개념을 적용

- 의문점 : 메일 전송이 정상적으로 되는지에 대한 확인은 어떻게 할 수 있을까? 
- 한계 : 실제 메일이 잘 전송되어 내용도 잘 보내졌는지 까지 보기엔 테스트의 한계가 있다.


## 테스트 대역의 종류와 특징
1. stub
	- 테스트 대상 오브젝트의 의존 객체며, 테스트 동안 코드가 정상적으로 수행할 수 있도록 도움
	- 어떤 테스트에서는 객체를 리턴하기도, 에러를 내뱉기도 한다. 
	- 테스트 과정에 적극적으로 참여
2. mock 
	- 간접적으로 의존 오브젝트에 넘기는 값과 행위 자체에 대해서도 검증하고 싶다면 사용

**Comment by kyueun** [comment]
## 트랜잭션 서비스 추상화
테스트 시, 예외 발생시켜야 한다면 테스트용 서비스 생성, 메소드 오버라이딩
```java
static class TestUserService extends UserService {
    private String id;

    private TestUserService(String id) {
        this.id = id;
    }

    /*
    특정 조건에서 예외 발생하도록 기존 메소드 오버라이딩
    테스트를 위해 어플리케이션 코드를 바꾸지 않고 테스트용에서만 변경
    */
    @Override
    protected void upgradeLevel(User user) { 
        if (user.getId().equals(this.id)) throw new Exception();
        super.upgradeLevel(user);
    }
}
```

## 트랜잭션 경계설정
여러 SQL 사용되는 작업이 하나의 트랜잭션으로 묶일 수 있음

트랜잭션 경계 설정
- 트랜잭션의 시작 선언하고, 롤백(모든 작업 무효화) 또는 커밋(모든 작업 확정) 으로 종료하는 작업
- 문제점
    - JdbcTemplate 사용 불가
    - UserService 는 비즈니스 로직을 담고 있는 클래스지만 Connection 파라미터가 존재해야 함
    - UserDao 가 데이터 액세스 기술에 독립적이지 않게 됨
    - 테스트 코드에서 Connection 오브젝트를 만들어 호출해야 함

## 트랜잭션 동기화
Connection 파라미터 전달할 필요 없이, 별도 저장소에 보관해두고, 이후 호출되는 DAO 메소드에는 저장된 Connection을 가져다가 사용

스프링
- `TransactionSynchronizationManager` 클래스 통해 트랜잭션 동기화 작업

JdbcTemplate
- 미리 생성되어 저장소에 등록된 DB 커넥션이나 트랜잭션 없는 경우, JdbcTemplate 이 직접 DB 커넥션 만들고 시작
- 트랜잭션 동기화가 시작된 경우, 저장소에서 DB 커넥션을 가져와서 사용 = 이미 시작된 트랜잭션에 참여

## 트랜잭션 서비스 추상화
### 글로벌 트랜잭션
각 DB와 독립적으로 만들어지는 Connection이 아닌, 별도 트랜잭션 관리자를 통해 트랜잭션을 관리
- 자바는 JTA 등 제공

스프링
- 트랜잭션 경계설정 추상 인터페이스인 `PlatformTransactionManager`
- 기술 별 `PlatformTransactionManager` 구현한 트랜잭션 매니저 사용

## 서비스 추상화와 단일 책임 원칙
비즈니스 로직 / 하위 로우레벨 트랜잭션 기술 등 다른 계층의 특성을 갖는 코드 분리
수별적 / 수직적 모두 결합도를 낮추기 위해 DI 가 중요한 역할
- 관심, 책임, 성격이 다른 코드를 깔끔하게 분리

### 단일 책임 원칙
하나의 모듈은 하나의 책임을 가진다
- 변경 필요 시, 수정 대상 명확

## 메일 서비스 추상화
### JavaMail을 이용한 메일 발송 기능
JavaMail
- 자바 이메일 클래스
- 메일 전송 서버에 전송 요청 보냄

### JavaMail이 포함된 코드의 테스트
- 메일 전송 서버는 충분히 검증된 서비스
- JavaMail API 통해 요청이 들어간다는 것만 확인하면 실제 메일이 전송되는지 여부는 테스트 필요 X

### 테스트를 위한 서비스 추상화
- JavaMail은 확장, 지원 불가능한 표준 API
- 쉽게 테스트하기 위해 JavaMail에 대한 추상화 기능 제공 ex. `MailSender`
- 트랜잭션 적용 방식
    - 트랜잭션 작업 완료 시 메일 전송
    - 메일 전송에 트랜잭션 개념 적용

## 테스트 대역
테스트 대상이 의존하는 오브젝트를 DI를 통해 변경

### 테스트 대역
자주 테스트를 수행할 수 있도록 테스트 대상이 되는 오브젝트 기능 빠르게 수행 가능하도록 한 오브젝트

### 테스트 스텁
테스트 대상 오브젝트의 의존객체

### 목 오브젝트
실제 기능은 없고, 코드가 수행되도록 넘겨주는 출력 값만 보관해서 리턴하는 등 수행

**Comment by tmfrl1552** [comment]
## 트랜잭션 경계 설정
* 트랜잭션 롤백
	* 성공적으로 DB에서 수행되기 전에 문제가 발생할 경우, 앞에서 처리된 작업 모두 취소하는 작업
* 트랜잭션 커밋
	* 모든 SQL 수행 작업이 다 성공적으로 마무리됐다고 DB에 알려줘서 작업 확정

* 트랜잭션 경계
	* 애플리케이션 내에서 트랜잭션이 시작되고 끝나는 위치
	* JDBC에서 트랜잭션 시작 시, 자동 커밋 옵션을 false로 설정

* 트랜잭션 경계 설정
	* setAutoCommit(false)로 트랜잭션의 시작을 선언하고, commit() 또는 rollback()으로
	  트랜잭션을 종료하는 작업
	* 하나의 Connection이 만들어지고 닫히는 범위 안에 존재
	* DB 커넥션 안에서 만들어지는 트랜잭션 : 로컬 트랜잭션
<br>

## 트랜잭션 동기화
* Connection 오브젝트를 특별한 저장소에 보관해두고, 이후에 호출되는 
  DAO 메소드에서는 저장된 Connection을 가져다가 사용하게 하는 것
* 트랜잭션 동기화 저장소는 작업 스레드마다 독립적으로 Connection 오브젝트를 저장하고 관리하기 때문에
  다중 사용자를 처리하는 서버의 멀티 스레드 환경에서도 충돌이 날 염려는 없음.

<br>

## 트랜잭션 서비스 추상화
* 글로벌 트랜잭션(global transaction)
	* 별도의 트랜잭션 관리자를 통해 트랜잭션을 관리
	* 트랜잭션 매니저를 통해 여러 개의 DB가 참여하는 작업을 하나의 트랜잭션으로 관리
* 자바는 JDBC 외에 이런 글로벌 트랜잭션을 지원하는 트랜잭션 매니저를 지원하지 위한 API인 
  JTA 제공 (Java Transaction API)
* 트랜잭션 매니저는 DB와 메시징 서버를 제어하고 관리하는 각가의 리소스 매니저와 XA 프로토콜을 통해 연결
* 스프링이 제공하는 트랜잭션 경계설정을 위한 추상 인터페이스는 'PlatformTransactionManager'

<br>

## 단일 책임 원칙
### 단일 책임 원칙
* 하나의 모듈은 한 가지 책임을 가져야 한다.
* 장점
	* 단일 책임 원칙을 잘 지키고 있다면, 어떤 변경이 필요할 때 수정 대상 명확

<br>

## 메일 서비스 추상화

레벨 업그레이드 시, 업그레이드 안내 메일 발송 기능 추가

### JavaMail을 이용한 발송 기능 추가
* 테스트 시 매번 메일을 발송하는 일은 부하가 큰 작업이며, 많은 테스트시 실제 발송이 되므로 운영에 부담
	* 애플리케이션에서 자동화할 수 있는 프로세스는 결국 메일서버 내 요청이 잘 전송되었는지까지가 바람직
	* 테스트 메일 서버를 만들어, 네트워크 부하를 줄이고 테스트 간소화 필요

* JavaMail 클래스 대신, JavaMail 기능을 이용하는 MailSender 인터페이스 생성
	* 메일 발송시 사용되는 오브젝트인 Session / Transport 
	  ➡️ 인터페이스가 아닌 final로 정의된 클래스
	* JavaMail API 인터페이스를 상속받아 테스트용 클래스 구현하기에는 어려움

* MailSender 인터페이스 사용 시 장점
	* 다른 메일 서비스를 사용하더라도 MailSender 인터페이스만 구현한 구현체만 만들면 언제든 DI를 통해 갈아끼울 수 있음
	* MailSender 인터페이스 의존을 통해 기능을 확장해 놓으면, 다른 메일 서비스로도 똑같은 확장

<br>

### 테스트 대역
* 테스트 대역(test double)
	* 테스트 환경을 만들어주기 위한 오브젝트 
* 테스트 스텁(test stub)
	* 의존 객체로 테스트 동안 코드가 정상 동작하도록 돕는 오브젝트
* 목 오브젝트
	* 단순히 실행 결과만을 테스트하는 것이 아닌, 실행 과정에서 일어나는 커뮤니케이션을 테스트하도록 도와주는 오브젝트

**Comment by aimhigh53** [comment]
**5.2**

## JDBC 트랜잭션의 트랜잭션 경계설정
* setAutoCommit(false)로 트랜잭션의 시작을 선언하고 commit() 또는 rollback()으로 트랜잭션을 종료하는 작업을 트랜잭션 경계설정이라 한다.

1. JDBC API를 직접 이용하기 때문에 JPA나 다른 데이터 엑세스 기술에 독립적일 수가 없다.
2. 테스트 코드에서도 Connection  오브젝트를 일일이 만들어 줘야한다.
3. 쓸데없이 UserService의 함수끼리 Connection 파라미터를 전달해줘야 한다.

##  지금까지 데이터 엑세스 부분과 비즈니스 로직을 잘 분리, 유지할 수 있게 만든 코드를 만들었다. 

하지만, 고객측에서 DB연결 방법을 바꾸고 싶다는 요구가 온다면?
* DataSource 인터페이스와 DI를 적용한 덕분에 UserDao,UserService는 수정하지 않아도 된다.
* UserService에서 JDBC의 Connection을 이용한 트랜잭션 방식인 로컬 트랜잭션으로는 다른 DB의 트랜잭션을 보장해주지 못한다. 즉, 별도의 트랜 잭션 관리자를 통해 글로벌 트랜잭션이 필요하다.

##  트랜잭션 API의 의존관계 문제와 해결책
UserService는 UserDAO 인터페이스에만 의존하는 구조였다.
* DAO 클래스의 구현기술이 JDBC, 하이버네이트, 여타 기술로 바뀌더라도 UserService 코드는 영향을 받지 않는다. ( OCP 원칙 코드 )
* 문제는 JDBC에 종속적인 Connection을 이용한 트랜잭션 코드가 UserService에 등장하는 것이다.

##  트랜잭션 기술 설정의 분리
 UserService가 어떤 트랜잭션 매니저 구현 클래스를 사용할지를 스스로 알고 있다. 이는 DI 원칙에 위배된다. 자신이 사용할 구체적인 클래스를 스스로 결정하고 생성하지 말고 컨테이너를 통해 외부에서 제공받게 하는 스프링의 DI 방식으로 바꾸자.

**5.3 ~ 5.4**

## 수직, 수평 계층구조와 의존관계
1. 수평적 분리
    * UserDao와 UserService의 분리
    * 각각 담당하는 코드의 기능적인 관심에 따라 분리
    * 서로 불필요한 영향을 주지 않으며 독자적으로 확장이 가능
    * 같은 애플리케이션 로직을 담은 코드지만 내용에 따라 분리
2. 수직적 분리
    * 트랜잭션 추상화
    * 애플리케이션 비지니스 로직과 로우레벨의 트랜잭션 기술이라는 아예 다른 계층의 특성을 갖는 코드를 분리


## 사용자 관리 모듈의 의존관계
* 애플리케이션 계층 : UserService, UserDao
    * 애플리케이션의 로직
    * 인터페이스와 DI를 통해 연결됨으로써 결합도가 낮아졌다.
* UserDao는 DB 연결을 생성하는 방법에 대해 독립적이다.
    * DataSource 인터페이스와 DI를 통해 추상화된 방식으로 로우레벨의 DB 연결 기술을 사용하기 때문이다.
* UserService는 구체적인 트랜잭션 기술에 독립적이다.
    * PlatformTransactionManager 인터페이스를 통한 추상화 계층을 사이에 두고 사용하기 때문이다.


##  단일 책임 원칙
단일 책임 원칙은 하나의 모듈은 한 가지 책임을 가져야 한다는 의미이다. 하나의 모듈이 바뀌는 이유는 한 가지여야 한다고 설명할 수도 있다.
* UserService에서 JDBC Connection의 메소드를 직접 사용하는 트렉젠션 코드를 사용하고 있을 때를 생각해보자.
* UserService는 어떻게 사용자 레벨을 관리할 것인가, 어떻게 트랜잭션을 관리 할 것인가 두가지 책임을 가지고 있었다.
* 두가지 책임을 가지고 있다는 건 코드가 수정되야할 이유가 두가지라는 뜻이다.
    1. 사용자의 레벨 업그레이드 정책과 같은 사용자 관리 로직이 바뀔 때
    2. 트랜잭션 기술을 JDBC에서 JTA로 변경해야 할 때
* 하지만 트랙잭션 서비스의 추상화 방식을 도입하고, 이를 DI를 통해 외부로 제어하도록 만들고 난 뒤에는 JDBC에서 JTA로 바뀌더라도 UserService 코드는 단 한줄도 수정할 이유가 없었다. 즉, UserService는 오직 사용자 관리에 대한 책임만 가지며 단일 책임 원칙을 충실히 지키게 되었다.

## 단일 책임 원칙의 장점
* 어떤 변경이 필요할 때 수정 대상이 명확해진다.
    * 만약 DAO가 각각 수백 개가 되고, 서비스 클래스도 그만큼 많다고 가정해보자. 서비스 하나가 여러개의 DAO를 사용하는 경우가 많아 질 것이다. 이떄, DAO를 수정했는데 그에 의존하는 서비스 클래스를 수정해야 한다면.. DAO를 사용하는 모든 서비스 클래스를 수정해야한다. 또, 이 때문에 수많은 테스트도 수정해야 할 수도 있다.
* 단일 책임 원칙을 잘 지키는 코드를 만들려면 인터페이스를 도입하고 이를 DI로 연결해야 한다. 그 결과 단일 책임 원칙 뿐만 아니라 OCP도 잘 지키고, 모듈 간의 결합도가 낮아져 서로의 변경에 영향을 주지 않고 같은 이유로 변경이 단일 책임에 집중되는 응집도가 높은 코드가 나온다.


## 테스트를 위한 서비스 추상화
JavaMail 대신에 테스트에서 사용할, JavaMail 같은 인터페이스를 갖는 오브젝트를 만들어서 사용하면 문제는 모두 해결된다.
JavaMail을 이용한 테스트의 문제점
JavaMail의 API는 이 방법을 적용할 수 없다.
* 메일 발송을 위해 생성해야하는 Session은 인터페이스가 아닌 클래스이이며, 생성자 역시 private으로 선언되어 직접 생성도 불가능하다.
* 스태틱 팩토리 메소드를 이용한 오브젝트 생성만 가능하고 final클래스이기에 상속도 되지 않는다.
* JavaMail의 구현을 테스트용으로 바꿔치기하는 건 불가능 하다고 볼 수 밖에 없다.
트랜잭션을 적용하면서 살펴봤던 서비스 추상화를 이용하면 적용하면 된다.
메일 발송 기능 추상화
메일을 전송하는 메소드로만 구성된 인터페이스


* 비즈니스 로직과 데이터 액세스 로직은 분리되어야 함. 또한, 비즈니스 로직 내부에서도 책임과 역할에 따라 메소드로 분리되야 함
* 인터페이스와 DI를 이용하여 결합도를 낮춰야 함
* DAO를 사용하는 비즈니스 로직에는 트랜잭션이 필요함
* 트랜잭션의 시작과 종료를 지정하는 일을 트랜잭션 경계설정이라 함. 주로 경계설정은 비즈니스 로직에서 많이 발생됨
* 트랜잭션 정보를 담은 DAO에 전달하는 방법은 매우 비효율적이기 때문에, 스프링이 제공하는 트랜잭션 동기화 방법을 사용하는 것이 편리함
* 자바에서 사용되는 트랜잭션 API의 종류와 방법은 많음. 트랜잭션 방법이 변경되면 경계설정 코드도 변경돼야 함
* 트랜잭션 경계설정 코드가 비즈니스 로직 코드에 영향을 주지 않기 위해 스프링이 제공하는 트랜잭션 서비스 추상화를 이용함
* 서비스 추상화는 로우레벨의 트랜잭션과 API의 변화에 상관없이 일관된 API를 가진 추상화 계층을 도입함
* 서비스 추상화는 JavaMail과 같이 테스트하기 어려운 기술에도 적용할 수 있음. 테스트를 편리하게 도와주는 것 만으로도 서비스 추상화는 가치있음
* 테스트 대역은 테스트 대상이 사용하는 의존 오브젝트를 대체하는 것임
* 테스트 대역은 테스트 대상 오브젝트가 원활하게 동작할 수 있도록 도우면서 테스트를 위해 간접정 정보를 제공해주기도 함
* 테스트 대역 중에서 테스트 대상으로부터 전달받은 정보를 검증할 수 있도록 설계된 것을 목 오브젝트라 함
