### ISSUE TITLE
Chapter6. AOP

### ISSUE THREAD

**Issue by kyueun** [FireInStove/toby-spring#9]
## 👑 스터디장
- 규은

## 📖 스터디 범위
- 6.1 ~ 6.2

## 🕧 스터디 일정
- 23/8/3 09시 ~

**Comment by kyueun** [comment]
## 트랜잭션 코드의 분리
1. 트랜잭션 경계 설정의 코드 / 비즈니스 로직 코드 간 주고받는 정보 없음 -> 메소드 분리 가능
2. 기술적인 코드 / 로직적인 코드 분리 -> 클래스 분리
3. 구현 클래스에 의존적인 강한 결합 -> 약한 결합을 갖도록 DI 적용
4. 테스트 수정

## 고립된 단위 테스트
- 의존관계가 복잡하면 작은 단위의 테스트가 어려움
- 목 오브젝트 - 테스트를 의존 오브젝트, 서버 등에서 고립시킴

**Comment by yougahee** [comment]
## 6. AOP

### 상황1. UserService 인터페이스를 도입
- 방법
	- UserService용 Interface를 클라이언트에 노출하지 않고 런타임 시에 DI를 통해 적용하는 방법
- 사용하는 이유
	- 구현 클래스를 바꿔가면서 사용하기 위함.
- 더 나아가서
	- UserService Interface에 2개의 구현 클래스를 만들어보자.
	- 1개는 메인로직(레벨 증가) / 1개는 트랜잭션 적용 로직
	- Client -> UserServiceTx(트랜잭션) -> UserServiceImpl(메인로직)


### 궁금증
- @Autowired 를 인터페이스에 주입을 한다고 했을 때, 해당 인터페이스를 구현한 클래스가 2개 이상일 경우는 어떤 데이터를 가져올까? 
	- 필드 이름을 이용해 빈을 찾음.
- 필드 이름도 만약 인터페이스와 같다면?
	- springboot에서는 사용할 수 없다고 빨간줄이 뜬다. ^^
	- 구체화 하라고 메세지가 뜬다.
	- 필드 이름을 구체화 클래스로 바꿔주면 제대로 값이 들어가고 동작도 한다.


## 트랜잭션 경계설정 코드 분리의 장점
1. 비즈니스 로직과 트랜잭션 로직의 완벽한 분리
	- 트랜잭션 작업을 비즈니스 로직에서 신경을 쓸 필요가 없다.
2. 언제든지 트랜잭션을 도입할 수 있다. 
3. 비즈니스 로직에 대한 테스트를 손쉽게 할 수 있다.


## Mockito 프레임워크
- 고립된 테스트를 만들어주는 프레임워크 
- 목 클래스를 알아서 만들어 줌

``` java
// 아직 아무런 기능이 없음.
UserDao mockUserDao = mock(UserDao.class);

// 스텁 기능을 추가
when(mockUserDao.getAll()).thenReturn(this.users);

```

**Comment by tmfrl1552** [comment]
# Chapter6. AOP
## AOP 
> IoC/DI 서비스 추상화와 더불어 스프링의 3대 기반기술의 하나

### DI 적용을 이용한 트랜잭션 분리
* DI의 기본 아이디어는 실제 사용할 오브젝트의 클래스 정체는 감춘 채 인터페이스를 통해 간접으로 접근하는 것
* 구현 클래스는 얼마든지 외부에서 변경 가능

### 트랜잭션 분리에 따른 테스트 수정
* @Autowired는 기본적으로 타입을 이용해 빈을 찾지만 만약 타입으로 하나의 빈을 결정할 수 없는 경우에는
  필드 이름을 이용해 빈을 찾는다.

<br>

## 고립된 단위 테스트
> 가장 편하고 좋은 테스트 방법은 가능한 한 작은 단위로 쪼개서 테스트
> * 테스트 실패 시, 그 원인을 찾기 용이

### 테스트 수행 성능의 향상
* 고립된 테스트 진행 시 테스트가 다른 의존 대상에 영향을 받을 경우를 대비해 복잡하게 준비할 필요가 없음
* 테스트 성능도 크게 향상

### 단위 테스트와 통합 테스트
#### 단위 테스트
* 테스트 대상 클래스를 목 오브젝트 등의 테스트 대역을 이용해 의존 오브젝트나 외부의 리소스를 사용하지 않도록 고립시켜 테스트

#### 통합 테스트
* 두 개 이상의 성격이나 계층이 다른 오브젝트가 연동하도록 만들어 테스트하거나,
  또는 외부의 DB나 파일, 서비스 등의 리소스가 참여하는 테스트

#### 단위 테스트/통합 테스트 가이드라인
``` java
1. 항상 단위 테스트 먼저 고려
	* 테스트 작성 간단,
	* 실행 속도 빠름 
	* 테스트 대상 외의 코드나 환경으로부터 독립
	* ➡️ 빠른 시간에 효과적인 테스트를 작성하기에 유리
2. 외부 리소스를 사용해야만 가능한 테스트는 통합 테스트 진행
	* DAO는 DB까지 연동하는 테스트로 만드는 편이 효과적
	* DB 사용 테스트는 DB에 테스트 데이터 준비 및 DB 작업 확인을 위한 부가적인 작업 필요
3. 단위 테스트를 충분히 거쳤다면, 통합 테스트의 부담은 상대적으로 줄어듬
``` 


### 목 프레임워크
단위 테스트를 만들기 위해 스텁이나 목오브젝트의 사용은 필수적

#### Mockito 프레임 워크
* 번거로운 목 오브젝트를 편리하게 작성하도록 도와주는 목오브젝트 지원 프레임워크
* mock() 메소드
	* org.mockito.Matchers 클래스에 정의된 스태틱 메소드

**Comment by aimhigh53** [comment]
### 6.1 트랜잭션 코드의 분리

#### 메서드 분리하기
 - 트랜잭션의 경계를 설정하는 코드와 비즈니스 로직을 구분할 수 있다.
 - 그러나 트랜잭션 코드가 여전히 UserService 내부에 존재하는 것이 부담이다.

#### DI를 이용해 트랜잭션 분리하기
 - 현재 구현은 클라이언트가 UserService 클래스를 직접 참조하고 있다. 그래서 인터페이스에 의존하여 결합도를 낮추는 작업을 수행한다.
 - 지금 해결하고자 하는 문제는 비즈니스 로직을 담고 있는 코드와 트랜잭션 담당하는 코드를 분리하기 위함이다.
 - 그러기 위해 UserService를 구현한 UserServiceTx 클래스를 만든다.
   - 주입받는 UserService는 비즈니스 로직을 처리하는 구체 클래스고,
   - UserServiceTx는 트랜잭션만을 담당한다.
 - Client → UserServiceTx(트랜잭션 경계 설정) → UserService(비즈니스 로직)

#### 테스트 수정하기 : @Autowired

#### 트랜잭션 경계설정 코드 분리의 장점
 - 비즈니스 로직을 담당하는 UserServiceImpl 코드 작성시 트랜잭션에 대한 고민은 하지 않아도 된다.
 - 비즈니스 로직 테스트를 좀 더 쉽게 작성할 수 있다.


### 6.2 고립된 단위 테스트
테스트를 가장 쉽게 하는 방법은 가능한 작은 단위로 쪼개는 것이다. 테스트 실패 시 원인을 찾기 쉽기 때문이다. 하지만 작은 단위의 테스트를 작성하는게 항상 가능한 것은 아니다.

#### 복잡한 의존관계 속 테스트

테스트 대상을 다른클래스, 서버에 종속되지 않도록 고립시켜야함
Mock 객체 이외에 필요하지 않은 의존 객체와 서비스를 모두 제거
단위테스트와 통합테스트

테스트 클래스를 의존 객체나 외부 사용하지 않도록 고립하여 테스트 하는 것을 단위테스트
두개 이상의 다른 객체가 연동하여 테스트, 외부 DB 등 참여하는 테스트는 통합테스트
Mock 프레임워크

**Comment by flyingtw** [comment]
AOP는 어렵기로 악명 높다.
선언적 트랜잭션 기능이 유명하다.

## 6.1 트랜잭션 코드의 분리
- DB upgrade 기능을 분리하여 트랜잭션 연결과 DB 기능을 분리하자.
- 하지만, 트랜잭션을 담당하는 기술적인 코드가 아직 남아있다.
- DI 적용을 이용한 트랜잭션 분리
- 서비스 인터페이스를 만들어서 실제로직과 트랜잭션 로직을 각기 다른 구현체에 정의한다.
- 같은 인터페이스를 구현한 다른 서비스를 오브젝트를 DI 받아서 트랜잭션 기능을 추가할 수 있다!
- 트랜잭션 서비스를 우선적으로 사용하도록 프로퍼티 설정을 해야한다.
